### ISSUE TITLE
Using ocrmypdf API will result in OutputFileAccessError

### ISSUE THREAD

**Issue by aheinecke** [ocrmypdf/OCRmyPDF#1008]
This is how I invoke ocrmypdf: 
`ocrmypdf.ocr(quote(path_file), quote(path_file), language=lang, skip_text=True, deskew=True)`

I'm always getting ocrmypdf.exceptions.OutputFileAccessError: Output file location ('/file location') is not a writable file.

When I'm using the system call everything wents well. Where is the problem? I'm using ocrmypdf 13.7.0

**Comment by jbarlow83** [comment]
It looks like the `quote()` function is surrounding the file path with quotes, and causing the system to look for a file whose names is literally `'/file location'`.

Consider using pathlib.Path to hold your file paths.

**Comment by aheinecke** [comment]
Works better, thank you.
