### ISSUE TITLE
OCR picks up all the text, but alignment is off

### ISSUE THREAD

**Issue by nchammas** [ocrmypdf/OCRmyPDF#1009]
This is an amazing tool. Thank you for sharing it with the world.

Here is an example PDF:
* Original: [alignment.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/9448004/alignment.pdf)
* With OCR: [alignment - ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/9448008/alignment.-.ocr.pdf)

The OCR is working well, however the alignment seems to be off. Highlighting a bit of text or a word seems to miss the last character or so, even though if you try copying and pasting it's clear that you got everything.

Some examples:
![Screen Shot 2022-08-29 at 5 12 50 PM](https://user-images.githubusercontent.com/1039369/187301708-1fbedf06-15e9-4fb5-8748-d389d34109f0.png)
![Screen Shot 2022-08-29 at 5 13 02 PM](https://user-images.githubusercontent.com/1039369/187301707-fda67f42-aa83-43f9-a9df-45e3bab0bd8a.png)

In both these cases, the expected text is actually highlighted, even though it doesn't look like it. In other words, the full date string will actually be copied, as well as the full word "Multiple". But the highlight suggests that somehow the final letter or so wasn't picked up by OCR.

I'm running OCRmyPDF 13.7.0 and Preview 11.0 on macOS.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/2879

**Comment by jbarlow83** [comment]
Will be fixed by changes in #1194
