### ISSUE TITLE
Create Unicode maps for MikTeX/LaTeX generated PDFs with Bitmap fonts by OCR glyph by glyph

### ISSUE THREAD

**Issue by leozachl** [ocrmypdf/OCRmyPDF#1014]
We've got a lot of (old) PDFs with BitmapFonts (Type3), without encoding and unicode map.
Initial ASCII characters are looking good, but non ASCII characters and ligatures have random codepoints.
After 'optimizing' the PDF with gs or any other PDF tool the text is scrambled.

So my idea is to create unicode maps for these fonts by OCR each glyph with tesseract.
e.g.: https://www2.ub.tuwien.ac.at/TISS95327_orig.pdf
https://www2.ub.tuwien.ac.at/TISS95327_asura.pdf
here initially only ligatures (ff, fl, fi,.. ) are wrong

Any hints how to create the unicode objects and extend the font objects with pikepdf?

**Comment by jbarlow83** [comment]
Often for encoding issues it can be best to use `ocrmypdf --force-ocr` which will blow all of the old encoding, flatten to image and give you a modern PDF.

You can create any PDF data structure you need with pikepdf, and the PDF spec documents most of what is relevant for this problem, but it would still take quite a while to work out everything that needs. But my sense is answering your question with all relevant detail would take half a day of research. There are also some undocumented conventions, or at least as far I know, they're undocumented.

pdfminer.six can read all of the font and text data structures, but not write to any of them, so it could be useful as a reference and starting point for fixing them. It might also be you need to a little bit hacking like ocrmypdf already does in ocrmypdf.pdfinfo.layout.

I'd consider trying commercial tools for this application if that makes sense for you. Maybe there's something in Acrobat's Preflight tools or maybe Abbyy FineReader can redo the OCR.

Please note your URLs return a 403 status code so I was not able to view them.

**Comment by leozachl** [comment]
Yes I added `ocrmypdf --force-ocr ` as option to our PDF workflow.
Here  https://repositum.tuwien.at/handle/20.500.12708/78164 you can find the result.

I decided to use the Asura optimized/scrambled PDF. Asura is adding ToUnicode maps to all fonts.
So I only have to correct and extend the tables. If my code is usable not only for us you will find it on github or gitlab.

The URLs are now accessible
