### ISSUE TITLE
present OCRmyPDF at normconf

### ISSUE THREAD

**Issue by mu22le** [ocrmypdf/OCRmyPDF#1018]
Hi, 
[NormConf](https://normconf.com/) is the tech conference about all the stuff that matters in data and machine learning, but doesn't get the spotlight. a conference about all the mundane, behind-the-scenes, how-the-sausage-is-made, middlebrow, unsexy, normcore stuff in the data and ML parts of the tech world.

I think this tool is a fantastic candidate for a talk: a very useful tool more people should know about. Would you consider presenting one?

**Comment by jbarlow83** [comment]
Maybe next year!
