### ISSUE TITLE
Debian maintainer requested for OCRmyPDF and pikepdf

### ISSUE THREAD

**Issue by jbarlow83** [ocrmypdf/OCRmyPDF#1019]
The maintainer of the Debian package of ocrmypdf and pikepdf is looking for someone else to take over the work of maintaining downstream packages for Debian (and Ubuntu and other apt-based distributions).

If you are familiar with maintaining Debian packages, please consider contributing and helping ocrmypdf continue to be available on Debian. For details, please see here.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017872

**Comment by frrad** [comment]
Looks like the package was adopted by a new maintainer https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017872#15
