### ISSUE TITLE
Batch Processing: Help Adding Suffix To Output file

### ISSUE THREAD

**Issue by ariefcfa** [ocrmypdf/OCRmyPDF#1021]
From documentation site [https://ocrmypdf.readthedocs.io/en/v14.0.0/batch.html](https://ocrmypdf.readthedocs.io/en/v14.0.0/batch.html), to batch processing with `find` is:

```
find . -printf '%p\n' -name '*.pdf' -exec ocrmypdf '{}' '{}' \;
```

**My question:** how to add **suffix** to the `output` file? Like OriginalFilename**_OCR\<suffix\>**.pdf and saving it to my current working directory

My case are:
- using Termux on Android
- `working directory` is /sdcard
- sometimes need to OCR pdf file in ./Android/Media whatsapp folder

I mainly use Windows on desktop, so I test the terminal command on phone. This already takes time too long. Not familiar with linux terminal, I found it is not easy (like punctuation ` ' " are interpret differently) and maybe need to read the manual fully about find, printf, basename, brace expansion-substitution, a lot more (hard to do right now).

The best I can find right now is:

```
find ./Android/media -iname "*mykeyword*.pdf" -printf '%p\n' -exec ocrmypdf '{}' 'manually_type_the_filename.pdf' \;
```
*this save the `output` **manually_type_the_filename.pdf** in sdcard directory (which is my current working directory – my preferred location)*

Please kindly help. Thanks

**Comment by jbarlow83** [comment]
Install GNU parallel and use its renaming features:

```
find . -name '*.pdf' | parallel ocrmypdf '{}' '{.}_suffix.pdf'
```

**Comment by ariefcfa** [comment]
@jbarlow83 thanks.

But, this save the output to the original directory..
Is it possible to save the output to current directory, or /sdcard ?

sorry

**Comment by jbarlow83** [comment]
Please see the documentation on parallel for examples of how to change the output directory.
Maybe it was `'/sdcard/{/.}_suffix.pdf'`?

**Comment by ariefcfa** [comment]
holy hollywood! :)
it works! add /. inside the last placeholder

```
/sdcard $ find ./Android/media -iname '*bendera*.pdf' | parallel ocrmypdf '{}' '{/.}_ocr.pdf'                               Opened a file                                                 Start processing 4 pages concurrently
Opened a file                                                     4 Opened a file
    4 Opened a file                                               3 Opened a file                                               2 Opened a file
    1 Opened a file                                           Postprocessing...                                             Opened a file
Opened a file                                                 Opened a file
Opened a file                                                 Optimize ratio: 1.01 savings: 1.3%                            Opened a file
Output file is a PDF/A-2B (as expected)
Opened a file
Opened a file
```
I dont know why, i just type paste every command on google result... (don't worry i know do not blindly paste every code)
thanks a ton Dev, much appreciates for creating OCRmyPDF

best regards
