### ISSUE TITLE
ghostscript problem

### ISSUE THREAD

**Issue by navtis** [ocrmypdf/OCRmyPDF#1028]
Ghostscript 10.0 crashes with error 'rangecheck in .putdeviceprops' when called with -sColorConversionStrategy from _exec/ghostscript.py; this can be fixed for that version of gs by editing the parameter to be set with -d instead of -s (line 234 in ocrmypdf 13.4.1). But I don't know what version of gs this change began with, somewhere in the 9.xx series I believe.

**Comment by jbarlow83** [comment]
I don't see anything indicating -s is deprecated and 10.0 has been tested.
https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#color-conversion-and-management

Please provide a reproducible example.

**Comment by navtis** [comment]
I get the same behaviour without ocrmypdf, eg

```
gs -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.6  -dAutoRotatePages=/None -sColorConversionStrategy=/LeaveColorUnchanged  -dPDFSETTINGS=/ebook -sOutputFile=t1.pdf test.pdf
GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Unrecoverable error: rangecheck in .putdeviceprops
```
But swapping -s for -d and leaving everything else unchanged:
```
gs -dNOPAUSE -dBATCH -dSAFER -sDEVICE=pdfwrite -dCompatibilityLevel=1.6  -dAutoRotatePages=/None -dColorConversionStrategy=/LeaveColorUnchanged  -dPDFSETTINGS=/ebook -sOutputFile=t1.pdf test.pdf
GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 10.
Page 1
Page 2
Page 3
Page 4
Page 5
Page 6
Page 7
Page 8
Page 9
Page 10
```
Related problems have been reported elsewhere eg: https://stackoverflow.com/questions/64356914/ghostscript-d-vs-s-command-line-parameters

**Comment by jbarlow83** [comment]
The issue is not the slash, ocrmypdf uses -sColorConversionStrategy=`LeaveColorUnchanged` which is correct syntax.

I missed that you were using an old version of ocrmypdf. You need to upgrade to v14.0.1 to get ghostscript 10 support. Ghostscript changed how they report version numbers, so older versions of ocrmypdf fail to parse ghostscript's version and activate shims to support very old versions, which in turn break ghostscript.
