### ISSUE TITLE
How to reduce ram usage

### ISSUE THREAD

**Issue by alirf81** [ocrmypdf/OCRmyPDF#1029]
Hello
Thank you for your contribution.
I am using this project to ocr pdf files and it works pretty well.
But for some pdfs, the ram gets full (32GB) and the ocr fails.
I call Python API like following:
`ocrmypdf.ocr(pdf_path, out_path, output_type="pdf", redo_ocr=True, optimize=0)`
PDF for test:
https://drive.google.com/file/d/1jfw4PsYavEbaKeHuEf3XBldChxXVEwuh/view
Is there any way to reduce ram usage?

**Comment by jbarlow83** [comment]
If you limit the number of jobs (`--jobs N` where N is less than your CPU cores) then ram usage may be lower in exchange for limiting CPU cores available.
