### ISSUE TITLE
Ghostscript error + OCRmyPDF puts a space after every letter in the output.pdf file

### ISSUE THREAD

**Issue by moritz1000** [ocrmypdf/OCRmyPDF#1030]
Hello,

I have been  using OCRmyPDF every few weeks. Everthing used to work but as of today I have some issues:

_(Test files)_
[test_scan_no_ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/9938607/test_scan_no_ocr.pdf)
[test_scan_with_ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/9938608/test_scan_with_ocr.pdf)

I want to add OCR to `test_scan_no_ocr.pdf` via 
```
ocrmypdf test_scan_no_ocr.pdf test_scan_with_ocr.pdf 
```

I get a working `test_scan_with_ocr.pdf` output file but the text looks like this:

> B u t | m u s t e x p l a i n t o y o u h o w a l l t h i s m i s t a k e i d n e a o f d e n o u n c i p n l e g a s u ra e n d
> p r a i s i n g p a i n w a sb o r n a n d | w i l l g i v e y o u a c o m p l e a t e c c o u n o f t t h e s y s t e m a , n d
> e x p o u n t h d e a c t u a lt e a c h i n g o fs t h e g r e a te x p l o r e o r f t h e t r u t h , t h e m a s t e r - b u i l o d f e r
> h u m ah n a p p i n e [...]

so there is a space after every letter. This never happened to me before.

___

The command line ouput is:

```
ocrmypdf test_scan_no_ocr.pdf test_scan_with_ocr.pdf                                                                      ✔ 
Opened a file
Scanning contents: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 548.42page/s]
Opened a file
    1 Opened a file                                                                                                                                     
    1 Opened a file                                                                                                                                     
OCR: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:02<00:00,  2.63s/page]
Postprocessing...
Opened a file
PDF/A conversion: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.47page/s]
GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular

The following errors were encountered at least once while processing this file:
        object lacks a required Subtype

   
 This file had errors that were repaired or ignored.
   
 The file was produced by: 
   
 >>>> PoDoFo - http://podofo.sf.net <<<<
   
 Please notify the author of the software that produced this
   
 file that it does not conform to Adobe's published PDF
   
 specification.


Opened a file
Opened a file
Opened a file
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 82.35image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.24 savings: 19.4%
Opened a file
Output file is a PDF/A-2B (as expected)
Opened a file
Opened a file
```
___

I can't remember ever seeing the 
```
Loading font f-0-0 (or substitute) from /usr/share/ghostscript/Resource/Font/NimbusSans-Regular
```
part and nether the 

``` 
The file was produced by: 
   
 >>>> PoDoFo - http://podofo.sf.net <<<<
 ```
 one. 
 In one of my tests the ouput said that the file was produced by `IJ Scan Utility` instead of `PoDoFo`.
 ...
 actually I think I never saw anything regarding Ghostscript at all in my output.
 ___
 
 I am using: 
 Arch Linux
 ocrmypdf 14.0.1-1
 ghostscript 10.0.0-2

Can someone help me with this?

**Comment by jbarlow83** [comment]
The spacing issue is complex since where spaces are in PDF is, surprisingly, open to interpretation.

`--output-type hocr` often works on files that the regular PDF struggles with, but it only works on Latin alphabet languages so it's not the default.

**Comment by jbarlow83** [comment]
The Ghostscript error messages are likely as reported - there are problems with the input file on a structural/technical level, that makes the file problematic even if it displays correctly in many programs.

**Comment by moritz1000** [comment]
I just tried to use OCRmyPDF again and had no more Ghostscript error messages this time. 
Spacing between letters is good too!

So my problem is fixed but I don't know why. 
Maybe I still had a partial system upgrade running or all it took was just to restart the some times computer. 
Anyways thank you for your help @jbarlow83 and I think this issue can be closed.
