### ISSUE TITLE
ocrmypdf cannot convert pages with watermarks.

### ISSUE THREAD

**Issue by marlarius** [ocrmypdf/OCRmyPDF#1034]
[page-ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10012135/page-ocr.pdf)
I have some scanned magazines with a pink watermark on some of the pages. I have attached an example page which is already processed by ocrmypdf.

ocrmypdf cannot convert text on top of the watermark.

Lets try to search for the word "forbindelse" (connection in Danish) in the second line. You can find "forbind" but if you type the next letter, e, there is not match because the rest of the word is above the watermark.

Strangely enough it seems to have trouble converting text to the right of the watermark too. It can not find the word "max" for example, and you can also see it by double clicking on many words after the watermark. OCR'ed words are selectable, but these are not.

This is the command line:

`ocrmypdf -l dan --skip-text --deskew --optimize 2  output.pdf output-ocr.pdf`

I also tried with --remove-background but this option is not implemented.

Is there any way I can tweak the command to OCR the text above the watermarks?

**Comment by marlarius** [comment]
No comments?

**Comment by jbarlow83** [comment]
Apologies. I haven't be able to keep up with my open source projects lately.

You may be able to get better results with `--tesseract-thresholding` using either the option `adaptive-otsu` or `sauvola`.
These are only available with Tesseract 5, so you will need to make Tesseract 5 is installed too. scikit-image has a library of image thresholding tools as you that you could try using as preprocessing tools, if you don't mind coding something.

**Comment by marlarius** [comment]
Thanks, I will give the --tesseract-thresholding option a try.
