### ISSUE TITLE
read_params_file: Can't open pdf/txt -- new issue -- help!

### ISSUE THREAD

**Issue by yosamshiyam** [ocrmypdf/OCRmyPDF#1037]
I'm on a mac running ocrmypdf through homebrew.  

I was looking at a previous discussion about the “read_params_file: can't open pdf/txt” issue but did not understand at all the solution to the issue.

I'm not as computer savvy as I'd like to be, so it be great if someone could walk me through how I can get my tessdata files in working order and get ocrmypdf to not make this error and start functioning again.   As of right now, I can't seem to ocr in any language from any pdf.

**Comment by yosamshiyam** [comment]
the issue is number 773, fyi.

**Comment by jbarlow83** [comment]
Try reinstalling tesseract with homebrew.

**Comment by yosamshiyam** [comment]
Thanks.  Worked like a charm!

**Comment by yasoob** [comment]
@yosamshiyam feel free to close the if your problem is fixed 😊
