### ISSUE TITLE
Ignore Digital Signed Documents

### ISSUE THREAD

**Issue by flaviobrunopereira** [ocrmypdf/OCRmyPDF#1040]
Hi,

Is there a way to ignore digital signed documents? 
And was there any changes recently? I would swear a year ago digital signed documents would just thrown an error.

Thanks.

**Comment by jbarlow83** [comment]
Do you have an example file?

**Comment by farhills** [comment]
I've just come across this issue, numerous digitally signed files have been unintentionally clobbered.  I've sent you an email with a sample file, I prefer not to post publicly.

In my environment, it is the nextcloud Workflow OCR app calling ocrmypdf with the --skip-text flag.
![260091118-d27525bc-43e2-4808-abbe-cf079c0a2313](https://github.com/ocrmypdf/OCRmyPDF/assets/83388006/cff4aee0-a753-447e-acf1-20adc99589d9)
