### ISSUE TITLE
Spaces in Japanese

### ISSUE THREAD

**Issue by KajiyaOokami** [ocrmypdf/OCRmyPDF#1041]
Hi all!
I wonder if it is possible to do OCR having all spaces completely ignored in the outcome? Languages like Japanese do not really use any spaces (even after commas or periods), but currently OCRmyPDF seems to find spaces between almost every character, which is very problematic when you want to search for sentences/words in the document, or google translate parts of it...
Thank you in advance!

**Comment by KajiyaOokami** [comment]
oh, I forgot to give some example! For example, what should be copy-pasted from the output PDF as: 

"美学や社会学の分野では",

Appears instead as:

"美学 や 社会 学 の 分 野 で は".

And it is like that for the whole document.

**Comment by KajiyaOokami** [comment]
I have no programming knowledge at all, but upon researching a little bit more, I believe such problem comes not when the text is extracted from the input PDF, but when it is laid on the output PDF. I think so because if, for instance, the text is extracted from the input PDF but then visualized in the terminal, there are no spaces.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/2702

**Comment by jbarlow83** [comment]
duplicate - tesseract issue
