### ISSUE TITLE
OCR for Comic Book PDFs -- Possible Solution

### ISSUE THREAD

**Issue by yosamsimiti** [ocrmypdf/OCRmyPDF#1042]
One thing I felt ocrmypdf doesn't do well is ocr'ing comic books.  This is obviously on account of tesseract.  There is an open source app however I found that enables OCR-ing on PDF comic book files, in addition to CBR and related comic book formats.  Since everything is open source, perhaps one could draw code from that app and incorporate it into ocrmypdf.  I am not a coder on any level, so obviously don't know or understand the possible technicalities.  I just wanted to argue that the technology is out there, at least on macs. Here is the app:

http://dancingtortoise.com/simplecomic/

And here is the github page:

https://github.com/arauchfuss/Simple-Comic

Hope comic books thus can be incorporated in future iterations of your app.

**Comment by yosamsimiti** [comment]
oh sorry, the latest gen of the app can only be found on Apple's app store. not sure what people using other types of computers can do, but I just wanted to throw this information out there.

**Comment by jbarlow83** [comment]
Comic books are a special case that should be handled a dedicate app.
