### ISSUE TITLE
Is it possible to capture Tesseract messages and suggestions either as exceptions or exit codes?

### ISSUE THREAD

**Issue by sergeyyurkov1** [ocrmypdf/OCRmyPDF#1050]
**Is your feature request related to a problem? Please describe.**
Sometimes when running OCR jobs with redo_ocr, I can see certain suggestions like rescanning the file with force_ocr from OCRmyPDF and similar observations about the quality of text from Tesseract. Is it possible to somehow capture these messages, so that I can programmatically filter those files out and rerun OCR with the recommended parameters?

**Describe the solution you'd like**
A status code or custom exception to catch and retry the running job.

**Describe alternatives you've considered**
Filtering stdout and looking for said keywords.

**Example file**
N/A

**Additional context**
N/A

**Comment by jbarlow83** [comment]
Yes. OCRmyPDF uses the standard `logging` module. If you run ocrmypdf in a script (using the ocrmypdf.ocr API) you could subscribe to messages from tesseract (all of which are logged and grouped appropriately) and react accordingly. 

ocrmypdf.quality has an API for testing OCR output against a dictionary, which can be a strong indicator of how successful OCR was.

You could also write a plugin that subclasses the standard TesseractOcrEngine and customizes it to your needs.

The message force-ocr does not come from Tesseract but elsewhere in the program. It could also be intercepted by monitoring logs. Hope this helps.

**Comment by sergeyyurkov1** [comment]
Yes, thank you, that was very informative.
