### ISSUE TITLE
Feature request: Ask user what likely-incorrect words are

### ISSUE THREAD

**Issue by mattention** [ocrmypdf/OCRmyPDF#1051]
OCRmyPDF is great as it is. It is an excellent tool for OCRing PDFs without any human involvement.

However, if a human is available, their involvement could be put to good use.

**Problem**
Tesseract+OCRmyPDF doesn't OCR every word correctly when this is desired. When outputting to PDFs, correcting such PDFs is more difficult than correcting outputted text.

**Proposed solution**
Tesseract generates a low confidence value for words it has difficulty working out the glyphs for. I understand OCRmyPDF checks all words against a dictionary for the selected language as part of it's existing process.

A word that is likely wrong could have the part of the image containing it's sentence presented to the user (with the word identified with a red box), the user asked what the word is (like a CAPTCHA), and the OCR results amended. If a word the user provides isn't in the dictionary, they should be asked if they want to add it or not.

This would happen in parallel with the main processing. Sentences containing words identified for checking would cumulatively fill the screen, waiting for human response. 

The proposed functionality would obviously not be default, and should have appropriate user settings for adjustment.

**Describe alternatives you've considered**
Get OCRmyPDF to output hOCR and PDF files simultaneously, then go through pages manually using gImageReader. It would work. But more slowly than the proposed method would be.

**Comment by jbarlow83** [comment]
ocrmypdf has an option to feed a dictionary to Tesseract; what Tesseract does with the dictionary is its business (and depends on Tesseract version and settings). It does add some bias towards selecting words in that dictionary.

I don't think I will take any steps to make ocrmypdf interactive, but generating hOCR files would be doable.
