### ISSUE TITLE
Is it possible to add paddleocr as an option for ocr?

### ISSUE THREAD

**Issue by nissansz** [ocrmypdf/OCRmyPDF#1055]
Is it possible to add paddleocr as an option for ocr?

**Comment by jbarlow83** [comment]
This could be done with a plugin - the documentation describes the plugin architecture. 

At the moment I don't have the time to evaluate paddleocr or add it myself. If someone made a high quality plugin I'd be happy to consider adding it to the main project and I could give general advice about a PR.

**Comment by nissansz** [comment]
how to use plugin to pass image to other ocr engine and return result needed for ocrpdf?

**Comment by jbarlow83** [comment]
Documentation is here. You would define a new OcrEngine instance that describes paddleocr.
https://ocrmypdf.readthedocs.io/en/latest/plugins.html#ocrmypdf.pluginspec.get_ocr_engine

**Comment by nissansz** [comment]
result must be similar to Tesseract OCR? How about your another default option?
