### ISSUE TITLE
Error processing shell script on file

### ISSUE THREAD

**Issue by danilichti** [ocrmypdf/OCRmyPDF#1060]
Hi,

both ocrmypdf and tesseract have been installed with homebrew on my mac. 

When running the following shell scrip on a couple of PDF files using Hazel, I get the above error message.

`ocrmypdf -l deu+eng --redo-ocr "$1" "$1"` 
I also tried: 
`ocrmypdf -l deu+eng --force-ocr "$1" "$1"` 

This is one of the files I tried but received the error message: 
[Get_Started_With_Smallpdf.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10429816/Get_Started_With_Smallpdf.pdf)

**Comment by jbarlow83** [comment]
It looks like you included an example PDF. What's the actual error message?

**Comment by danilichti** [comment]
Sorry, I found the problem. 
Works perfectly now.
