### ISSUE TITLE
[QUESTION] Render hocr with python

### ISSUE THREAD

**Issue by jcuenod** [ocrmypdf/OCRmyPDF#1065]
I use `--pdf-renderer hocr` at the cli to better align characters. How can I do that in a python script:

```
import ocrmypdf

def ocr(infile, outfile):
    ocrmypdf.ocr(infile, outfile) # <-- add hocr here
```

I found https://stackoverflow.com/questions/70889590/hocr-output-from-ocrmypdf, but this seemed excessive so I am wondering if it is the best/only way.

**Comment by jbarlow83** [comment]
`ocrmypdf.ocr(infile, outfile, pdf_renderer='hocr')`

Most command line parameters can be fed in that way.

**Comment by jcuenod** [comment]
Thanks! Where is this documented?

**Comment by milahu** [comment]
> Where is this documented?

in the source code

https://github.com/ocrmypdf/OCRmyPDF/blob/f181307e5026366818c443b36bd3b5c5c46b508a/src/ocrmypdf/api.py#L231-L287
