### ISSUE TITLE
[BUG]  /dev/null gets deleted when run as root (inside a Docker container)

### ISSUE THREAD

**Issue by andymwood** [ocrmypdf/OCRmyPDF#1067]
**Describe the bug**
When running `ocrmypdf.ocr("file.pdf", os.devnull)` in a Python script as the root user, `/dev/null` gets deleted, breaking the operating system. (I'm doing this inside a Docker container...)

**To Reproduce**
```console
python -c 'import os, ocrmypdf; ocrmypdf.ocr("/name.pdf", os.devnull, sidecar="output.txt", output_type="none")'
...
FileNotFoundError: [Errno 2] No such file or directory: '/dev/null'
```

**Expected behavior**
`/dev/null` shouldn't be deleted.

**System (please complete the following information):**
 - OS: OpenSUSE Leap 15.4
 - Python version: 3.10.8
 - OCRmyPDF version: 14.0.2
 - Platform: x64

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
`pip install ocrmypdf`

**Additional context**
I tracked the problem down to the function `helper.is_file_writable`. I've got a fix [here](https://github.com/andymwood/OCRmyPDF/commit/8384f8daff1ad3696c485c76d3ea159a91ada040).

**Comment by jbarlow83** [comment]
Fixed in 997380
