### ISSUE TITLE
[BUG] Possible to force OCR without losing vector data?

### ISSUE THREAD

**Issue by moksamedia** [ocrmypdf/OCRmyPDF#1069]
(Sorry. Not exactly a bug but wasn't sure where to put this. More of a question.)

Is it possible to use the `--force-ocr` flag but not end up with a pdf of rasterized images? I realize you need to rasterize the page to perform the OCR, but is it possible to them map the OCR back to the original document?

My use case is, for example, this file: [https://wiki.learntibetanlanguage.org/napper-definitions.pdf](https://wiki.learntibetanlanguage.org/napper-definitions.pdf)

It contains a mix of English and Tibetan. The Tibetan was encoded with a non-Unicode font, so that it is not searchable nor can it be copied and pasted. This is a common problem in Tibetan studies as there are TONS of old PDFs with non-Unicode Tibetan characters.

I can force rasterization using `--force-ocr` and the OCR works great. However, this greatly increases the file size (450k to 3.3 MB). For this particular file that's not such a huge deal, but it can be a bigger problem with larger files. 

I tried `--redo-ocr` but that didn't seem to OCR the Tibetan.

**Comment by jbarlow83** [comment]
As currently implemented `--force-ocr` solves some problems like text with incorrect Unicode maps (looks fine, copy-pastes as gibberish) or PDFs that have their font rendered entire as vector art with no indication of text. Sometimes a PDF is in such bad shape, rasterizing is the best option. 

`--redo-ocr` is unfortunately limited in capabilities. At the time I worked it on the project was funded by a corporate sponsor, and without such participation now I can't spend that the time needed to make it more capable.

**Comment by RainyMeadows** [comment]
Will take a look, sometime.
