### ISSUE TITLE
[BUG] cannot ocr the numbers on left side of page

### ISSUE THREAD

**Issue by sushmitxo** [ocrmypdf/OCRmyPDF#1074]
**Describe the bug**
ocrmypdf does not ocr the numbers 1, 2, 3 till 9. it starts to ocr  the numbers from 10 

**To Reproduce**

```bash
ocrmypdf --output-type pdf --oversample 600 --remove-background --clean-final --force-ocr jrfps2021.pdf jrfps2021ocr1.pdf
```
NOTE: i have added so many arguments because ocrmypdf was unable to ocr the higlighted texts in my file. but upon running the above arguments, it is able to do so.

**Example file**
[jrfps2021.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10832280/jrfps2021.pdf)
[jrfps2021ocr1.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/10832265/jrfps2021ocr1.pdf)

**Expected behavior**
i expected it to ocr the numbers as well, like it normally does for other files.

**Screenshots**

**System**
 - OS: linux ubuntu
 - OCRmyPDF Version: ``10.3.1+dfsg``
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image? i used apt install ocrmypdf

**Comment by jbarlow83** [comment]
OCR is unfortunately not perfectly accurate, and there are cases that will fool the Tesseract OCR engine. The `--tesseract-thresholding` argument may help; this is available in recent versions of ocrmypdf (v14) and Tesseract (v5).
