### ISSUE TITLE
[BUG] PIL.Image.DecompressionBombError

### ISSUE THREAD

**Issue by JohnLockeG** [ocrmypdf/OCRmyPDF#1076]
**Describe the bug**
I'm using OCRmyPDF with synOCR in my Synology DS220+. I got an failure with an pdf i try to OCR.

> File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3164, in _decompression_bomb_check
>                       raise DecompressionBombError(msg)
>                   PIL.Image.DecompressionBombError: Image size (605118990 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.

**Example file**

My input file has personal information.

**System**
 - OS: DSM7
 - OCRmyPDF Version: jbarlow83/ocrmypdf:latest (2023-02-15T20:21:21)

**Comment by stumpylog** [comment]
You can set `--max-image-mpixels` with a value of 700 (more than 606) if you're sure of the source of the image.  It's an error for a reason after all.
