### ISSUE TITLE
JBIG2 not legally secure in many countries

### ISSUE THREAD

**Issue by dklinger** [ocrmypdf/OCRmyPDF#1077]
**Describe the bug**
Since the Xerox scan disaster in 2013, many countries have deemed JBIG2 compression, whether lossy or lossless, not legally secure. Is there a possibility to use another compression method than JBIG2 or is the only option to completely disable optimization with 0?

**Additional context**
Source: TR 03138 of the German BSI. Version 1.1 available in English here: https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03138/TR03138.pdf?__blob=publicationFile&v=1
Current version is 1.4.1, but it still contains the same restrictions.
The important part is on page 22. As JBIG2 uses Soft Pattern Matching in lossless mode, even lossless is affected.
![image](https://user-images.githubusercontent.com/2249766/223541764-b3268dff-411e-4bc2-ae1f-639b43f24ce9.png)

**Comment by jbarlow83** [comment]
I believe that the agl/jbig2enc executable does not use symbol coding unless the `--symbol-mode` option is issued -- in other words, in that implementation of JBIG2, lossy and symbol coding are synonymous, and without symbol coding, lossless is safe. OCRmyPDF only uses `--symbol-mode` when ``--jbig2-lossy`` and ``--optimize 3`` are set.

If you have information to suggest this is not the case, I'll be happy to look at it, but I have not seen anything to indicate JBIG2 lossless is unsafe.

**Comment by jbarlow83** [comment]
In any case, if you remove jbig2enc from your system, or hide it from ocrmypdf somehow, ocrmypdf will never attempt to encode JBIG2.
