### ISSUE TITLE
[BUG] pikepdf warning about missing decoders

### ISSUE THREAD

**Issue by ajweber** [ocrmypdf/OCRmyPDF#1078]
Attempting to use --optimize 3 on a PDF (on Windows x64) results in the following output at the end of processing:
`C:\Python311\Lib\site-packages\pikepdf\_methods.py:493:` UserWarning: pikepdf is missing some specialized decoders (probably JBIG2) so not all stream contents can be tested.
  self._decode_all_streams_and_discard()

 - OS: Windows 10
 - Python version: 3.11
 - OCRmyPDF version: 14.0.3
 - Platform: x64
 
Installed via choco/pip, then added directories to PATH. Installed and added jbig2.exe to PATH.

Are there any supplemental files I need for pikepdf to support JBIG2?

**Comment by jbarlow83** [comment]
The check that is raising this warning is attempting to confirm that a PDF containing JBIG2 is correctly formatted. Thus, without a JBIG2 decoder (like jbig2dec) the warning appears whenever JBIG2 is produced by optimization and a JBIG2 decoder was not found.

**Comment by ajweber** [comment]
Is there someplace I can download "jbig2dec" for Windows (or just python, etc.)?  The JBIG2 documentation for Windows installs is a little lacking. :)

**Comment by ajweber** [comment]
I found a binary and added it to the path and it seems to have picked it up.  Warning is gone.  Thanks.
