### ISSUE TITLE
[BUG] Snap Package not Working

### ISSUE THREAD

**Issue by lhhel9l3** [ocrmypdf/OCRmyPDF#1082]
**Describe the bug**
Snap package is broken

**To Reproduce**
```
$ snap install ocrmypdf
ocrmypdf v14.0.0+git5.110c75cb from James Barlow (shael7aerien) installed
$ ocrmypdf 
/snap/ocrmypdf/49/bin/python3: No module named ocrmypdf
```

**Expected behavior**
The snap package to work

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Python version: n/a (this should be bundled in the snap)
 - OCRmyPDF version: see above
 - Platform: x64

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

snap

**Additional context**
Let me know if you need any other details

**Comment by brlin-tw** [comment]
Hello, I've implemented a patch for this problem, feel free to test it and give feedback.

**Comment by brlin-tw** [comment]
The fix is not merged to the upstream yet, hence the edge version will not work.

I can provide you a l self built package to test.

**Comment by brlin-tw** [comment]
@lhhel9l3 

Here's a self-built snap that contains the patch: <https://drive.google.com/file/d/1oK-rer5Yko08aZ21eQP1e_LurqvCgbrr/view>

To minimize security risk, you may install and test the snap using the following instruction:

```bash
sudo snap install --dangerous /path/to/ocrmypdf_v14.0.4+git2.5880590_amd64.snap
sudo snap disconnect ocrmypdf:home # Disallow untrusted snap to access your home directory files
cp /path/to/document/to/test.pdf ~/snap/ocrmypdf/common
cd ~/snap/ocrmypdf/common
ocrmypdf test.pdf test.ocr.pdf
sudo snap remove ocrmypdf
```

**Comment by brlin-tw** [comment]
@lhhel9l3 That's fair.  Note that I'm not a maintainer of this project but instead a contributor that [once contributed to the snap package](https://github.com/ocrmypdf/OCRmyPDF/commit/1654324).

I'll let you know when the fix is merged upstream.
