### ISSUE TITLE
[BUG] #addopts = pytest -n "auto" no option?

### ISSUE THREAD

**Issue by shaynababe** [ocrmypdf/OCRmyPDF#1088]
**Describe the bug**
What's the problem?
-n not a pytest option
**To Reproduce**
Steps to reproduce the behavior.
pytest in root dir fails
**Expected behavior**
What did you expected to happen?
run the tests
**Screenshots**
![orc1](https://user-images.githubusercontent.com/120763310/228260408-917fb668-1d71-49b6-a380-15fdf776170f.png)

**System (please complete the following information):**
 - OS:
 - Python version:
 - OCRmyPDF version:
 - Platform: x64 or ARM
 - x64
 - PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
(base) z@spin7:~/tools/OCRmyPDF$ pytest
============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/z/tools/OCRmyPDF, configfile: pyproject.toml, testpaths: tests
plugins: anyio-3.6.2
collected 320 items                                                            

tests/test_acroform.py 

pyproject.toml - change
[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ["lib", ".pc", ".git", "venv", "output", "cache", "resources"]
testpaths = ["tests"]
#addopts = -n "auto"
markers = ["slow"]
filterwarnings = ["ignore:.*XMLParser.*:DeprecationWarning"]

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
mamba install and git clone
**Additional context**
running test now and scanning two files

**Comment by jbarlow83** [comment]
pytest-xdist needs to be installed, along with all of the other test dependencies in pyproject.toml [project.optional-dependencies], to run the tests. `pip install ocrmypdf[test]` is one way to install these components.
