### ISSUE TITLE
How to handle already ocred files efficiently?

### ISSUE THREAD

**Issue by drnicolas** [ocrmypdf/OCRmyPDF#1092]
**Is your feature request related to a problem? Please describe.**
I have a lot of PDF-files which have been processed already by ocrmypdf or are primarily digitally born.
But also there are PDFs which do NOT contain text.

What is the correct procedure on how to handle this?

I thought the resultcode 6 is teh solution, but I alse get error messages when trying to do ocrmypdf on an already processed file.

At the moment I add the "force_ocr" flag, but then I get crazy big files - normally factor 6 to 15 bigger than the original

What can I do ?

**Comment by jbarlow83** [comment]
ocrmypdf will not process files that have text already. It does return code 6 in this case, along with an explanatory error message. You can safely ignore the error message for files that return this code and trust that it is processing only files that need it. A mix of processed and unprocessed files is a common situation.

You may also find it help to write a script that uses the ocrmypdf.ocr API -- then you can configure logging and handle errors in a way that makes sense to you. For example, you could consume the error message.

If something is not working as you expect, I'll need more details or an example file.
