### ISSUE TITLE
Feature Request: Provide for usage with cloud-based OCR engines

### ISSUE THREAD

**Issue by simsong** [ocrmypdf/OCRmyPDF#1093]
**Is your feature request related to a problem? Please describe.**
Several studies have now indicated that the cloud-based OCR services offered from Amazon and Google and possibly others offer significantly better OCR performance than either commercial or open-source OCR engines that run on desktops.

**Describe the solution you'd like**
It would be useful if this program had the ability to use a cloud-based OCR engine.

**Describe alternatives you've considered**
To do this:
- [ ] The program would need a switch to support other OCR engines.
- [ ] There would need to be a way to specify credentials for the cloud engine (since they cost money)

**Comment by DarkPhyber-hg** [comment]
I was just looking for the same thing.  Unfortunately, there's not appetite for it with the lead dev of the project.  See #728

I did find a plugin on github that utilized google vision, unfortunately the results in my testing are worse than tesseract, and worse than the built in ocr in my scanner.

https://github.com/kkrell2016/ocrmypdf_plugin_GoogleVision

**Comment by simsong** [comment]
Huh. Thanks for that. I didn't find #728 when I opened this, but I think that it's a duplicate, so I'll close this issue. It's unfortunate that I can't add a label...

**Comment by simsong** [comment]
> @simsong I was just looking for the same thing. Unfortunately, there's not appetite for it with the lead dev of the project. See #728
> 
> I did find a plugin on github that utilized google vision, unfortunately the results in my testing are worse than tesseract, and worse than the built in ocr in my scanner.
> 
> https://github.com/kkrell2016/ocrmypdf_plugin_GoogleVision

I should add that I got accuracy to improve significantly by downloading the larger models.

**Comment by DarkPhyber-hg** [comment]
@simsong 
> I should add that I got accuracy to improve significantly by downloading the larger models.

yeah the other language models were still making a lot errors and jibberish, both the build in ocr with my scanner and the abby pdf conversion were far more accurate.

However, i think i settled on an option.  I found this python script that will use azure to make a searchable pdf.

https://techcommunity.microsoft.com/t5/ai-applied-ai-blog/generate-searchable-pdfs-with-azure-form-recognizer/ba-p/3652024

I'm using ocrmypdf via paperless-ngx.  What's going on in my use case is i'm running a script beforehand that pre-processes my pdf and sends it to azure, then ocrmypdf runs in skip-text mode and mainly as a means to convert my new azure-ocr'ed pdf into a pdf/a document.
