### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by pinballelectronica** [ocrmypdf/OCRmyPDF#1097]
Ubuntu 22.04 hangs wsl2

Scanning contents: 100%|██████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.55page/s]
Start processing 15 pages concurrently
OCR:   0%|                                                                                 | 0.0/15.0 [00:00<?, ?page/s]

I'd love for it to work with Ubuntu on Windows :)

64GB Swap

Actually I went to grab the ver and the VM 100% hung:

KeyboardInterrupt:
root@DESKTOP-F4MRTFM:/mnt/c/Users/dave/documents# ocrmypdf --help

<dead>

**Comment by pinballelectronica** [comment]
I'm going to go ahead and take that back- it does work but not with certain PDFS--I just happened to experience a crash with the first PDF I tested.  Do you want EXIF data or ?

**Comment by jbarlow83** [comment]
Can you paste the output of `qpdf --json yourfile.pdf` here? That will give me an idea of what's in the file without giving anything private away. If you can share the file (encrypt it to my GPG if you like) that's better.
