### ISSUE TITLE
Remove image layer after OCR?

### ISSUE THREAD

**Issue by Frooodle** [ocrmypdf/OCRmyPDF#1098]
When running application with parameters
ocrmypdf --verbose 2 --output-type pdf --force-ocr --language eng /tmp/input_13970005530238054469.pdf /tmp/output_3651620766075329861.pdfCommand

The output is a file which contains a image layerand then OCR layer ontop with text
This is fine normally but when i run the resultant document into a PDF to DocX converter (LibreOffice) this causes double the text per page as it renders the Image and OCR ontop of each other and slighly different.
I have also tested hocr render type with same result

Is OCRMyPDF able to remove the image layer after running OCR?

**Comment by jbarlow83** [comment]
In principle this could be done but I don't think I would. You can use Ghostscript pdfwrite -dFILTERIMAGES to remove all images from a PDF. 

Ocrmypdf does not have the ability to reconstruct a document with accurate fonts and text placement. Some ocr engines can do that if the input document image is very clean and uses only a small number of common fonts in a simple layout -- they can then replace the document image with equivalent text. However, if you discard the image, OCR errors become permanent. OCR isn't accurate enough in hard cases to risk that. 

If you're trying to rebuild a document from OCR best bet is to OCR, copy plain text, and let a word processor do a new layout.

**Comment by Frooodle** [comment]
thanks makes sense
