### ISSUE TITLE
Unknown .defaultpapersize: (A4). / Unrecoverable error: rangecheck in .putdeviceprops / SubprocessOutputError: Ghostscript PDF/A rendering failed

### ISSUE THREAD

**Issue by klartext** [ocrmypdf/OCRmyPDF#1099]
Hello,

since a while  (different OCRmyPDF versions) I have the same issue (error message) with a lot of different pdf-files.

```
Scanning contents: 100%| [...] 10/10 [00:05<00:00,  1.85page/s]
Start processing 4 pages concurrently
OCR: 100%| [...] 10.0/10.0 [01:08<00:00,  6.84s/page]
Postprocessing...
GPL Ghostscript 10.01.1 (2023-03-27)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Unknown .defaultpapersize: (A4).
Unrecoverable error: rangecheck in .putdeviceprops

SubprocessOutputError: Ghostscript PDF/A rendering failed
```

Current version is 13.4.1, but I had the same issue with some earlier versions too.

Other pdf-tools seem to have had similar issues:
  https://github.com/tavinus/pdfScale/issues/1

**Comment by jbarlow83** [comment]
This is almost certainly a Ghostscript issue

**Comment by klartext** [comment]
Is there a way to somehow extract the data that leads to this error?
If it's a ghostscript problem, I would like to test the problem and then create a bug issue for ghostscript then.

I wonder, why the problem is not already known (as it seems to me that it isn't).
Could that be a less general problem and maybe a  misconfiguration of ghostscrippt on my computer?
I can't remember, that I ever had touched `.putdeviceprops` in a ghostscript config. But maybe I did other configuration (paper size?) a while ago and that screwed up things?

So, if possible to separate the problem into OCRMyPDf and ghostscript, I would like to do that.
Can you give me a hint on this?
(Maybe verbosity settings or insert some hacks to extract data from OCRMyPDF, before the data is sent to ghostscript?)

**Comment by jbarlow83** [comment]
If you run with the arguments -v1 -k, the output will show temporary files and the exact commands used to send them to Ghostscript.

**Comment by klartext** [comment]
OK, this was a configuration problem of ghostscript.

When starting ghostscript alone, the error occured also!
Somehow ghostscript thinks it has to use A4 as default, which is good for me.
Some configuration elsewhere might be the reason (command 'paper' throws out A4).
So even I did not asked for A4 explicitly it seemed to be expected.
So the setting is fine, but ghostscript mourned about it.

I could locate the problem in the `gs_init.ps` file.
(On my system it's `/usr/share/ghostscript/Resource/Init/gs_init.ps`.)

There is `/DEFAULTPAPERSIZE (a4) def` but commented out.
When removing the comment symbol `%`, the problem disappeared.

**Comment by nQk2** [comment]
I get the same error (without "Unknown .defaultpapersize: (A4).")
So just:

```
Unrecoverable error: rangecheck in .putdeviceprops

SubprocessOutputError: Ghostscript PDF/A rendering failed
```

Fix needed!
