### ISSUE TITLE
How to get the deskew angle 

### ISSUE THREAD

**Issue by GoN49** [ocrmypdf/OCRmyPDF#1101]
Hi ,

First thanks for your code that pretty nice and work pretty well .

I use this command for deskew and auto rotate page :

**ocrmypdf --deskew -v 1 --rotate-pages --tesseract-timeout=0 --rotate-pages-threshold 5 --skip-text**

After reading the output of ocrmypdf i try to get information about the rotation that have been done and the deskew. For the rotation that easy in the output i can see "will rotate" and the page number . But for deskew angle i cannot get it event when i put the verbose level to 1 or 2.
I use the latest version of ocrmypdf 14.1.0.

Can you tell me how i can get the skew angle ?
Why i want to get this information ? that easy it's because if i auto rotate pdf and auto deskew a pdf but there is nothing to change on pdf , i don't need to modify the original pdf.
I try also to take of the --tesseract-timeout=0 but that not change anything i not get any information about skew angle.
Thank you if you have trick for this

**Comment by jbarlow83** [comment]
At the moment there is no way to get it, but if you want to do a PR to log this, that sounds like a reasonable thing to record. You could also plugins to access the information directly and customize behavior with scripting.
