### ISSUE TITLE
OCRmyPDF not rotating the file correctly using the version 14.2.1

### ISSUE THREAD

**Issue by gilsonbergamine** [ocrmypdf/OCRmyPDF#1105]
I have a scanned document where one of the pages is vertically written (see attached).

This is the code:
`ocrmypdf.ocr(path, output_path, output_type='pdf', skip_text=True, progress_bar=False, rotate_pages=True)`

This is the file:
[scanned_Vertical.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/11555978/scanned_Vertical.pdf)

After running the code, the pdf file is still not readable (the text can be selected, but the characters are unrecognisable). 
To test it, you can select any text, copy it (control + c), and paste it anywhere.

If I manually rotate the page to be horizontal, it works.

regards,

**Comment by jbarlow83** [comment]
Rotation is an imperfect process like OCR. Sometimes it guesses wrong. You will get better results from manually rotated.
