### ISSUE TITLE
[BUG] Frequently seeing `Syntax Error (91811): Too few (2) args to 'cm' operator`

### ISSUE THREAD

**Issue by deexpabada** [ocrmypdf/OCRmyPDF#1108]
**Describe the bug**
The `--redo-ocr` option generates invalid results for certain PDFs. I can generally open these PDFs without any issues, but when inspecting them with other tools like `pdfimages` or `mutool`, they generate errors similar to `Syntax Error (91811): Too few (2) args to 'cm' operator`.

Do you know what could be causing this? Is there a bug with `--redo-ocr` that is resulting in broken PDFs?

**To Reproduce**
Run `--redo-ocr` on a PDF and then run `pdfimages -list pdf_name.pdf`, which will output the errors. 

**Expected behavior**
I expect `--redo-ocr` to produce valid outputs.

**Screenshots**

**System (please complete the following information):**
 - OS:
 - Python version:
 - OCRmyPDF version:
 - Platform: x64 or ARM

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

**Additional context**

**Comment by jbarlow83** [comment]
What version of Ghostscript and OCRmyPDF is installed?
Can you provide an example PDF? Can you replicate using any of the PDFs from OCRmyPDF suit?

I was not able to replicate using Ghostscript 9.55 and the latest ocrmypdf

**Comment by jbarlow83** [comment]
Was probably an early GS 10.0 release and suspect issue fixed over there
