### ISSUE TITLE
鉴于很多使用者不会配置环境，我们在OCRmyPDF的基础上，集成了所需环境，并使用Electron开发了桌面端 [Electron version of OCRmyPDF]

### ISSUE THREAD

**Issue by FanQinFred** [ocrmypdf/OCRmyPDF#1109]
### What were you trying to do?

鉴于部分使用者不会配置环境，我们在OCRmyPDF的基础上，集成了所需环境，并使用Electron开发了桌面端
[Considering that some users are not proficient in configuring the environment, we have integrated the necessary environment based on OCRmyPDF and developed a desktop application using Electron.]
[OCRmyPDF-Desktop](https://github.com/FanQinFred/OCRmyPDF-Desktop)
https://github.com/FanQinFred/OCRmyPDF-Desktop
### Where are you installing from?

source build

### What operating system are you working on?

Windows

**Comment by jbarlow83** [comment]
你为OCRmyPDF创建的Electron界面的工作听起来很有趣。是否有一个GitHub存储库，我可以在那里查看它？

**Comment by FanQinFred** [comment]
> 你为OCRmyPDF创建的Electron界面的工作听起来很有趣。是否有一个GitHub存储库，我可以在那里查看它？

https://github.com/FanQinFred/OCRmyPDF-Desktop
这是OCRmyPDF-Desktop的GitHub存储库
