### ISSUE TITLE
[Bug]: Can not transfer image into editable text in pdf

### ISSUE THREAD

**Issue by ericosmic** [ocrmypdf/OCRmyPDF#1119]
### Describe the bug

I has some image-contain pdf files need to transfer into searchable pdf files ,  but failure to transfer image into searchable text in result pdf file.

### Steps to reproduce

```plain text
1. ocrmypdf  -s -l chi_sim --output-type pdf  ../testdata/zf/zf1.pdf  ../testdata/zf/zf1-ocr.pdf 
2. Open output pdf
3. The image-type title still can't be searched.
```

### Files

[zf1.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/11859032/zf1.pdf)

### How did you download and install the software?

`pip install ocrmypdf`
### OCRmyPDF version
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/35327931/5975bad3-3ae7-44cc-8435-553025127113)

### Relevant log output
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/35327931/c145c844-b600-4c31-9f2c-aa1a0184d782)

_No response_

**Comment by jbarlow83** [comment]
The file in question contains a mix of text and images. By using the option `-s` (`--skip-text`) you are telling ocrmypdf to skip pages that already have any text, such as both pages in your file. (`--skip-text` is useful when, for example, you have a PDF with some pages generated digitally and some scanned pages in the appendix -- then you would only want to perform on the pages that don't already have text..)

Try `--redo-ocr` (attempts to preserve existing text while searching images for new text) or `--force-ocr` (treats everything as an image).
