### ISSUE TITLE
orcmypdf not working in HTML/browser

### ISSUE THREAD

**Issue by Prabal1902** [ocrmypdf/OCRmyPDF#1120]
### What were you trying to do?

I tried using orcmypdf in browser via HTML using pyscript but it gives error code Y1001 : pure python wheel not found. Installing .whl file from Pypi doesn't help either.

### Where are you installing from?

source build

### What operating system are you working on?

Windows

**Comment by jbarlow83** [comment]
There is no way that will be possible. Ocrmypdf has many non Python dependencies.

**Comment by Prabal1902** [comment]
Is there a way to run ocrmypdf in a browser by putting the python code
inside a docker and running on a browser ?

**Comment by jbarlow83** [comment]
There's a demo web app in the misc/ folder. It's not suitable for production (a single OCR job will tie up the web interface), but it demonstrates how a web app could use ocrmypdf. 

Paperless-ngx is document management software that uses ocrmypdf for OCR if that is what you are looking for.

**Comment by Prabal1902** [comment]
Thanks, I'll check it out.
