### ISSUE TITLE
Confused about --unpaper-args

### ISSUE THREAD

**Issue by al1coch** [ocrmypdf/OCRmyPDF#1122]
### What were you trying to do?

The documentations says:

   "By default, OCRmyPDF uses only unpaper arguments that were found to be safe to use on almost all files without having to inspect every page of the file afterwards. This is particularly true when only --clean is used, since that instructs OCRmyPDF to only clean the image before OCR and not the final image."

Sorry if I understand this the wrong way.  For me, this does mean that one _has to use_ '--clean' if one wants to use some unpaper arguments.  However:

   $ ocrmypdf --unpaper-args '--verbose -vv' in.pdf out.pdf 

   --clean is required for --unpaper-args

Besides:

   $ ocrmypdf --unpaper-args '-v -vv' in.pdf out.pdf 

   usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI]
                   [...]

   ocrmypdf: error: argument --unpaper-args: expected one argument

(Perhaps it does not make much sense to use both, but 'unpaper -v -vv ...' works just fine [i.e., not using ocrmypdf])

   $ ocrmypdf --version
   14.2.1

   $ unpaper -V
   7.0.0

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Linux

**Comment by jbarlow83** [comment]
ocrmypdf --clean --unpaper-args '-v -vv' in.pdf out.pdf

**Comment by al1coch** [comment]
Thanks for the feedback.

jbarlow83 writes on Tue 27 Jun 2023 09:31:

 > ocrmypdf --clean --unpaper-args '-v -vv' in.pdf out.pdf

Yes, I did observe this.  Sorry for not having been clear enough.

My point was: the fact that --unpaper-args _requires_ --clean cannot
be deduced from the documentation alone (again, unless I do not
understand the documentation correctly).

A possibility for making this point fully explicit in the
documentation would be to change the following part:

   "However, if you wish to use the more aggressive options in unpaper,
   you may use --unpaper-args '...' to override the OCRmyPDF’s
   defaults [...]"
 
to something like

   "However, if you wish to use the more aggressive options in
   unpaper, you may use --unpaper-args '...' (in which case --clean is
   required) to override the OCRmyPDF’s defaults [...]"

Further, even if I did have concluded that --clean was required, I was
still confused by the error message generated by

   ocrmypdf --unpaper-args '-v -vv' in.pdf out.pdf

It seems to me that, as in the other cases, the message should also be

   --clean is required for --unpaper-args

and not

   ocrmypdf: error: argument --unpaper-args: expected one argument


-- 
EOST (École et Observatoire des Sciences de la Terre) 
ITE (Institut Terre & Environnement) | ***@***.***
5 rue René Descartes   [bureau 110]  | Phone: +33 (0)3 68 85 50 44 
F-67084 Strasbourg Cedex, France     | [ slot available for rent ]
