### ISSUE TITLE
[Feature]: Distribute on Scoop?

### ISSUE THREAD

**Issue by ShadowCreator250** [ocrmypdf/OCRmyPDF#1128]
### Describe the proposed feature

[ScoopInstaller/Scoop](https://github.com/ScoopInstaller/Scoop) is a command line program manager for Windows similar to [Chocolatey](https://chocolatey.org/). It would be nice to also have this tool available on there.

You don't have to write the scoop manifest yourself (you can, of course). I just thought it would be nice to ask for permission first.

**Comment by jbarlow83** [comment]
Sure, give it a shot. You'll want to make sure Ghostscript and Tesseract are installed independently, and to make it easier for users please include pngquant and jbig2enc if they are available.

ocrmypdf looks for Ghostscript and Tesseract by checking the standard locations and the registry. If scoop happens to install apps to other locations you might need a patch ocrmypdf/_exec/windows.py.
