### ISSUE TITLE
[Feature]: Add Gentoo Linux to section 'Installation' of README.md

### ISSUE THREAD

**Issue by fonic** [ocrmypdf/OCRmyPDF#1129]
### Describe the proposed feature

Add **Gentoo Linux** to section _Installation_ of `README.md`:

Gentoo Linux  |  Repository 'guru'

**Comment by jbarlow83** [comment]
Please open a PR with the recommended installation instructions - I'm not familiar enough with Gentoo to work it out.

**Comment by fonic** [comment]
Sure, I can do that. How about leaving this issue open until then?
