### ISSUE TITLE
[Bug]: Is jbig2 encoder being called?

### ISSUE THREAD

**Issue by gtusr** [ocrmypdf/OCRmyPDF#1133]
### What were you trying to do?

I have a simple 2 page document that is all monochrome text and was 'born digital' so I used the -f (force OCR) option to test how well I could compress this obviously bloated 1 MB file.

Neither the snap (I had to install the jbig2enc command as a separate snap) nor the docker image appear to be compressing the raster images of the text as jbig2 all that well since the best that I can achieve is a 600 KB result with optimize level 3 and the jbig2-lossy flag set.  

I managed to find "Running['jbig2', '--version']" in the verbose level 2 output but there is no summary output being returned from jbig2.  Also, optimizable images reports "JBIG2 groups: 0", which is concerning.     

When I look closely at the zoomed characters in the compressed output, I am not able to find any characters that share identical patterns of pixelation, which is another sign that the jbig2 encoder is not processing the glyphs.  

The version of jbig2 being reported in the docker image is 0.28 and ocrmypdf is 14.3.1.dev2

Any thoughts?

 

### Where are you installing from?

Docker container

### What operating system are you working on?

Linux

### Relevant log output

```plain text
DEBUG ocrmypdf - ocrmypdf 14.3.1.dev2+g32693b68.d20230801
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 5.3.2-8-gd1ab
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['pngquant', '--version']
  DEBUG ocrmypdf.subprocess - Found pngquant 2.12.2
  DEBUG ocrmypdf.subprocess - Running: ['jbig2', '--version']
  DEBUG ocrmypdf.subprocess - Found jbig2 0.28
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.55.0
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages in "/usr/share/tesseract-ocr/5/tessdata/" (7):
chi_sim
deu
eng
fra
osd
por
spa

   INFO ocrmypdf._validation - reading file from standard input
  DEBUG ocrmypdf.helpers - os.symlink(/tmp/ocrmypdf.io.0ruil20u/stdin, /tmp/ocrmypdf.io.0ruil20u/origin.pdf)
  DEBUG ocrmypdf.builtin_plugins.tesseract_ocr - Using Tesseract OpenMP thread limit 3
   INFO ocrmypdf._sync - Start processing 2 pages concurrently
WARNING ocrmypdf._pipeline -    1  page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
  DEBUG ocrmypdf._pipeline -    1  Rasterize with png16m, rotation 0
  DEBUG ocrmypdf.subprocess -    1  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r400.000000x400.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.0ruil20u/origin.pdf']
WARNING ocrmypdf._pipeline -    2  page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
  DEBUG ocrmypdf._pipeline -    2  Rasterize with png16m, rotation 0
  DEBUG ocrmypdf.subprocess -    2  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=png16m', '-dFirstPage=2', '-dLastPage=2', '-r400.000000x400.000000', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.0ruil20u/origin.pdf']
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2354
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2354
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'default_rgb.icc'
  DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'default_rgb.icc'
  DEBUG PIL.PngImagePlugin -    2  Compression method 0
  DEBUG PIL.PngImagePlugin -    1  Compression method 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2407 9
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2407 9
  DEBUG PIL.PngImagePlugin -    2  STREAM b'tEXt' 2428 31
  DEBUG PIL.PngImagePlugin -    1  STREAM b'tEXt' 2428 31
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2471 8192
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2471 8192
  DEBUG ocrmypdf._exec.ghostscript -    2  Rotating output by 0
  DEBUG ocrmypdf._exec.ghostscript -    1  Rotating output by 0
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2350
  DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    1  Compression method 0
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2403 9
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2424 65536
  DEBUG ocrmypdf._pipeline -    1  resolution (399.9992, 399.9992)
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2350
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    2  Compression method 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2403 9
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2424 65536
  DEBUG ocrmypdf._pipeline -    2  resolution (399.9992, 399.9992)
  DEBUG ocrmypdf._pipeline -    1  convert
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2350
  DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    1  Compression method 0
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2403 9
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2424 65536
  DEBUG img2pdf -    1  PIL format = PNG
  DEBUG img2pdf -    1  imgformat = PNG
  DEBUG img2pdf -    1  input dpi = 400 x 400
  DEBUG ocrmypdf._pipeline -    2  convert
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2350
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    2  Compression method 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2403 9
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2424 65536
  DEBUG img2pdf -    2  PIL format = PNG
  DEBUG img2pdf -    2  imgformat = PNG
  DEBUG img2pdf -    2  input dpi = 400 x 400
  DEBUG img2pdf -    1  rotation = 0°
  DEBUG img2pdf -    1  input colorspace = RGB
  DEBUG img2pdf -    1  width x height = 3400px x 4400px
  DEBUG img2pdf -    1  read_images() embeds a PNG
  DEBUG ocrmypdf._pipeline -    1  convert done
  DEBUG ocrmypdf.subprocess -    1  Running: ['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.0ruil20u/000001_ocr.png', '/tmp/ocrmypdf.io.0ruil20u/000001_ocr_tess', 'pdf', 'txt']
  DEBUG img2pdf -    2  rotation = 0°
  DEBUG img2pdf -    2  input colorspace = RGB
  DEBUG img2pdf -    2  width x height = 3400px x 4400px
  DEBUG img2pdf -    2  read_images() embeds a PNG
  DEBUG ocrmypdf._pipeline -    2  convert done
  DEBUG ocrmypdf.subprocess -    2  Running: ['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.0ruil20u/000002_ocr.png', '/tmp/ocrmypdf.io.0ruil20u/000002_ocr_tess', 'pdf', 'txt']
  DEBUG ocrmypdf._graft -    2  Emplacement update
  DEBUG ocrmypdf._graft -    2  Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0
  DEBUG ocrmypdf._graft -    2  Grafting
  DEBUG ocrmypdf._graft -    2  Page rotation: (content, auto) -> page = (0, 0) -> 0
  DEBUG ocrmypdf._graft -    1  Emplacement update
  DEBUG ocrmypdf._graft -    1  Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0
  DEBUG ocrmypdf._graft -    1  Grafting
  DEBUG ocrmypdf._graft -    1  Page rotation: (content, auto) -> page = (0, 0) -> 0
   INFO ocrmypdf._sync - Postprocessing...
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Brf4fMLei-KfK6mYJYbJQQ in page 0
  DEBUG ocrmypdf.optimize - xref 14: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Dwsk7YK5r9q-8JtI6Ni3Dg in page 1
  DEBUG ocrmypdf.optimize - xref 18: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Optimizable images: JPEGs: 0 PNGs: 0
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Brf4fMLei-KfK6mYJYbJQQ in page 0
  DEBUG ocrmypdf.optimize - xref 14: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Dwsk7YK5r9q-8JtI6Ni3Dg in page 1
  DEBUG ocrmypdf.optimize - xref 18: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Brf4fMLei-KfK6mYJYbJQQ in page 0
  DEBUG ocrmypdf.optimize - xref 14: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Recursing into Form XObject /OCR-Dwsk7YK5r9q-8JtI6Ni3Dg in page 1
  DEBUG ocrmypdf.optimize - xref 18: treating as an optimization candidate
  DEBUG ocrmypdf.optimize - Optimizable images: JBIG2 groups: 0
  DEBUG ocrmypdf.helpers - os.symlink(/tmp/ocrmypdf.io.0ruil20u/optimize.opt.pdf, /tmp/ocrmypdf.io.0ruil20u/optimize.pdf)
  DEBUG ocrmypdf.subprocess - Running: ['jbig2', '--version']
  DEBUG ocrmypdf.subprocess - Running: ['pngquant', '--version']
   INFO ocrmypdf._pipeline - Image optimization ratio: 1.00 savings: 0.0%
   INFO ocrmypdf._pipeline - Total file size ratio: 1.86 savings: 46.2%
  DEBUG ocrmypdf._pipeline - /tmp/ocrmypdf.io.0ruil20u/optimize.pdf -> -
   INFO ocrmypdf._sync - Output sent to stdout
```

**Comment by jbarlow83** [comment]
Since there are no images ocrmypdf promotes the page to 24-bit RGB. The result image compresses well but not to 1-bit so JBIG2 cannot be used. Maybe there's room in the relevant code to choose 1-bit mono if only black and text is present - I think that's a condition that is not tested. 

Any amount of color in the document will likely prevent the use of JBIG2 in this type of document.

**Comment by gtusr** [comment]
> Since there are no images ocrmypdf promotes the page to 24-bit RGB. 

I assume that this because steps later in the processing chain only work with 24-bit color input.

> The result image compresses well but not to 1-bit so JBIG2 cannot be used.   Maybe there's room in the relevant code to choose 1-bit mono if only black and text is present - I think that's a condition that is not tested.

> Any amount of color in the document will likely prevent the use of JBIG2 in this type of document.

There is no color in the original.  

To make sure I understand, are you saying that only a monochrome _scanned_ image of text can benefit from jbig2 processing in current state of ocrmypdf?  I thought that choosing the --force-ocr would cause ocrmypdf to treat the page as a (very clean) raster scanned image. 

The only reason I am doing this is that the 'born digital' text-only PDF's that are being produced by my tool are so bloated.  If you have any other suggestions for compressing them (zip doesn't help ... pdf/a -> pdf helps only a little bit), that uses ocrmypdf or otherwise, I'd be interested in hearing them.

**Comment by gtusr** [comment]
Using ghostscript to preprocess the pdf by rasterizing it to tiff was enough to trigger jbig2 encoding in ocrmypdf:

```gs -sDEVICE=tiffg4 -o sample.tif sample.pdf```

I realize that the primary purpose of ocrmypdf is to process scanned images of text with OCR, but some might find the jbig2 encoding feature of independent interest for compressing 'born digital' pdfs since there are not that many open source options in that space yet.

In which case, a comparison between ocrmypdf and archive-pdf-tools in the area of pdf compression would be useful for those concerned primarily with the latter: 

 github: [archive-pdf-tools](https://github.com/internetarchive/archive-pdf-tools)

**Comment by jbarlow83** [comment]
Currently, if there is any vector content on a page, the whole page is promoted to full color, rather than trying to figure out if a less palette would be sufficient.

archive-pdf-tools is great but you'll notice it's not conveniently packaged, mainly because it uses PyMuPDF. PyMuPDF is AGPLv3, which isn't license-compatible, and relies on static libraries - the vendor has said they don't want to support an ABI for MuPDF/libmupdf. Because of that awkward arrangement, Linux distributions don't want to or cannot as a matter of policy, create packages for PyMuPDF. They're also very shy around jbig2enc, even though the last known patent expired in 2017. ocrmypdf needs dependencies to be license-compatible and suitable for including in a distribution.

I had some brief discussion with its MerljinWajer about trying to spin off a reusable portion of archive-pdf-tools under a permissive license so ocrmypdf and archive-pdf-tools could both use and develop it (his idea, mainly), but it never went anywhere.

**Comment by gtusr** [comment]
Thanks for the perspective.  I'm going to take a deeper look at how archive-pdf-tools performs on complex document structures with mixed content since my primary interest is high-quality compression rather than OCR.  

Can you briefly elaborate though on what exactly makes the current licensing of PyMuPDF so awkward?

**Comment by jbarlow83** [comment]
OCRmyPDF would probably have to change to AGPL-3.0 to use PyMuPDF, because by using it, it would become a derivative work of PyMuPDF. I don't want to change the license.

The awkward part I mentioned is the technical restrictions. All Linux distributions expect libraries to be created as shared libraries with stable-ish ABIs so that other packages can link to them, and so that patching the library package benefits all users of the library. Artifex creates libmupdf not as a shared library, but an internal-use static library in building MuPDF. Nothing says PyMuPDF can't do this, but it's a hacky solution.

**Comment by gtusr** [comment]
As a sidenote, it would be helpful to let users access some of the parameters used to run jbig2enc from within ocrmypdf.

For example, when using --jbig2-lossy, the -t threshold parameter can significantly affect the tradeoff between document image fidelity and level of compression achieved.  In addition, if the upsampling used during jbig2 encoding of glyphs and other bitonal figures happens independently of any other upsampling that takes place while running ocrmypdf, it would be useful for users to be able to access that parameter as well.

**Comment by jbarlow83** [comment]
A future release will have access to the -t parameter
