### ISSUE TITLE
[Bug]: SubprocessOutputError when scanning a specific PDF

### ISSUE THREAD

**Issue by AgustinOrdonez** [ocrmypdf/OCRmyPDF#1139]
### Describe the bug

I am trying  to digitalize a book I have (As a scanned PDF) but I get a crash when it is about to finish (I see 99% (624/630) progress and then crash happens). I don't know if I can share PDF file since it is a book (which is not written/eddited by me), but I can run any test you tell me 

### Steps to reproduce

```plain text
1. Run ocrmypdf -l spa --output-type pdf -v 1 "Física clasica y moderna Gettys.pdf" testOCR.pdf
2. Wait until it is almost done
3. See crash
```

### How did you download and install the software?

From python's pip, I am on a Windows machine

### OCRmyPDF version

14.4.0

### Relevant log output

```plain text
629 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                     _graft.py:131
  629 Grafting                                                                                             _graft.py:237
  629 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                 _graft.py:155
  621 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                     _graft.py:131
  621 Grafting                                                                                             _graft.py:237
  621 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                 _graft.py:155
  622 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                     _graft.py:131
  622 Grafting                                                                                             _graft.py:237
  622 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                 _graft.py:155
  620  lots of diacritics - possibly poor OCR                                                           tesseract.py:259
  620 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                     _graft.py:131
  620 Grafting                                                                                             _graft.py:237
  620 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                 _graft.py:155
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸  99% 624/630 0:00:05
ExitCodeException                                                                                           _sync.py:430
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
407, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\subprocess\__init__.py",
line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '-l', 'spa',
'-c', 'textonly_pdf=1', 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.37js8ajc\\000623_ocr.png',
'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.37js8ajc\\000623_ocr_tess', 'pdf', 'txt']' returned
non-zero exit status 3221225477.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 391, in
run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 279, in
exec_concurrent
    executor(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_concurrent.py", line 85,
in __call__
    self._execute(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\concurrency.py",
line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 220, in
exec_page_sync
    (ocr_out, text_out) = ocr_engine_textonly_pdf(ocr_image_out, page_context)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_pipeline.py", line 714,
in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py"
, line 252, in generate_pdf
    tesseract.generate_pdf(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
419, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
```

**Comment by jbarlow83** [comment]
If you run with `--keep-temporary-files`, you will be able to isolate the file named `000623_ocr.png` which caused the exception. You could then try running the same command OCRmyPDF is attempting to run on this file. If that command, independent of OCRmyPDF, fails, then the issue is with Tesseract, and I would encourage you to submit the image to that 

You could then share this one page image of your with me (possibly, encrypting it for me) for further investigation.

To be clear, this issue cannot be resolved if you cannot share at least the offending page image with me or Tesseract.

**Comment by AgustinOrdonez** [comment]
I tried running `tesseract -l spa -c textonly_pdf=1 000626_ocr.png test626` and it did not fail, I then tried `tesseract -l spa -c textonly_pdf=1 000626_ocr.png test626 pdf txt' it didn't fail but I got a blank pdf. Here is that specific file
![000626_ocr](https://github.com/ocrmypdf/OCRmyPDF/assets/104699326/01396e48-62e4-4c43-b4a7-9c240435d769)

**Comment by jbarlow83** [comment]
The blank PDF is expected (the text is invisible, but you can select it). 

I suspect given the size of the file that you ran out of some system resource will processing this larger file -- temporary storage space, RAM.

**Comment by AgustinOrdonez** [comment]
My machine wasn't even close to max RAM, is there any option for setting max ram the program is allowed to use? I didn't get any notification from Windows defender (only antivirus I have)

**Comment by jbarlow83** [comment]
I'm only guessing.
You could try splitting the file in half to run OCR and then merging the pieces after.

**Comment by AgustinOrdonez** [comment]
Any recommendation on a (free)tool to split PDFs that big? The ones I regularly use are online and have a size limit

**Comment by jbarlow83** [comment]
qpdf works well.

pikepdf if you want a Python-scriptable version of the same tool, which incidentally I wrote and is used in ocrmypdf.

**Comment by AgustinOrdonez** [comment]
Sliced the pdf in half(320 pages), also got the same error:
```
  315 Grafting                                                                                             _graft.py:237
  315 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                 _graft.py:155
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺  98% 315/320 0:00:08
ExitCodeException                                                                                           _sync.py:430
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
407, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\subprocess\__init__.py",
line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '-l', 'spa',
'-c', 'textonly_pdf=1', 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.j6922_0b\\000306_ocr.png',
'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.j6922_0b\\000306_ocr_tess', 'pdf', 'txt']' returned
non-zero exit status 3221225477.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 391, in
run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 279, in
exec_concurrent
    executor(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_concurrent.py", line 85,
in __call__
    self._execute(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\concurrency.py",
line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 220, in
exec_page_sync
    (ocr_out, text_out) = ocr_engine_textonly_pdf(ocr_image_out, page_context)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_pipeline.py", line 714,
in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py"
, line 252, in generate_pdf
    tesseract.generate_pdf(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
419, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
```

**Comment by jbarlow83** [comment]
Error 3221225477 is an access violation. The input that triggers the error seems to not be consistently reproducible.

Unfortunately that makes it look like your hardware is responsible -- at higher temperatures after running OCR for a long time it becomes unstable and a memory error occurs.

You could try --jobs 1 to restrict ocrmypdf to one core and while it will take longer, it may avoid the issue.

**Comment by AgustinOrdonez** [comment]
I did memory tests this earlier this week and got no errors. Also it would be weird if RAM overheated with 13°C ambient. Will try --jobs 1 though

**Comment by AgustinOrdonez** [comment]
I did test with -- jobs 1 and this is the output (tested with full file and the one it is splitted):
'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.ir8w1g9_\\000520_ocr_tess', 'pdf', 'txt']
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━  82% 518/630 0:11:21
ExitCodeException                                                                                           _sync.py:430
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
407, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\subprocess\__init__.py",
line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '-l', 'spa',
'-c', 'textonly_pdf=1', 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.ir8w1g9_\\000519_ocr.png',
'C:\\Users\\Usuario\\AppData\\Local\\Temp\\ocrmypdf.io.ir8w1g9_\\000519_ocr_tess', 'pdf', 'txt']' returned
non-zero exit status 3221225477.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 391, in
run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 279, in
exec_concurrent
    executor(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_concurrent.py", line 85,
in __call__
    self._execute(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\concurrency.py",
line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_sync.py", line 220, in
exec_page_sync
    (ocr_out, text_out) = ocr_engine_textonly_pdf(ocr_image_out, page_context)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_pipeline.py", line 714,
in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File
"C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py"
, line 252, in generate_pdf
    tesseract.generate_pdf(
  File "C:\Users\Usuario\AppData\Roaming\Python\Python311\site-packages\ocrmypdf\_exec\tesseract.py", line
419, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
