### ISSUE TITLE
[Bug]: No error, but 0-byte PDF produced

### ISSUE THREAD

**Issue by matt-cassinelli** [ocrmypdf/OCRmyPDF#1141]
### Describe the bug

One of my PDF's causes OCRmyPDF to exit with no indication of what's wrong.
It seems to exit right before the _Postprocessing_ stage.
Unfortunately the file contains personal details that I don't want on the internet, but I've attached the output of `qpdf --json input.pdf`. I might be willing to email it?

### Steps to reproduce

1. Run `docker run --rm -i ocrmypdf --deskew --skip-text --max-image-mpixels 1000 --tesseract-downsample-large-images 
--verbose 1 - - <E:\OCR_Test\input.pdf >E:\OCR_Test\output5.pdf`
2. OCRmyPDF will exit early without displaying a reason. The final log message with -v 1 is _"28 Rotating output by 0"_, and the final line in _debug.log_ is "ocrmypdf._graft -   DEBUG -   28  Page rotation: (content, auto) -> page = (270, 0) -> 270".
3. Resulting PDF from stdout has 0 bytes.

### What I've tried

- Without `--max-image-mpixels 1000` (gives PIL DecompressionBomb warning)
- Windows and WSL releases (same issue)
- `--skip-big` (PDF is outputted, but with no OCR present)

### Files

[qpdf_output.txt](https://github.com/ocrmypdf/OCRmyPDF/files/12428883/qpdf_output.txt)
[verbose_1_output.txt](https://github.com/ocrmypdf/OCRmyPDF/files/12428886/verbose_1_output.txt)

### How did you download and install the software?

Docker container

### OCRmyPDF version

14.4.1.dev5+g3002409e.d20230822 (but also happens on 14.4.0)

**Comment by jbarlow83** [comment]
Most likely the container ran out of memory so it was terminated by the OS. Perhaps you could try running ocrmypdf directly on WSL without the Docker container as it will remove one source of resource limits.

The output file should not be considered valid unless the return code is also 0. The 0-byte output is just a consequence of using the shell redirect.

**Comment by matt-cassinelli** [comment]
Interesting; indeed it is a large file with many pages and high DPI images. I tried adding --memory=12g --oom-kill-disable --memory-swap=-1, and the WSL version but get the same issue. Any other ideas?

**Comment by jbarlow83** [comment]
Native Windows, perhaps, or see if WSL has helpful error logs.
It's often temporary storage that runs out.

**Comment by jbarlow83** [comment]
Closing on the assumption this is configuration related.

**Comment by matt-cassinelli** [comment]
Any ideas on what configuration I could change?
