### ISSUE TITLE
[Bug]: 不是bug 请问我这是出现了什么问题 [It's not a bug. Please tell me what's wrong.]

### ISSUE THREAD

**Issue by zhengqianmaifang** [ocrmypdf/OCRmyPDF#1142]
### What were you trying to do?

<img width="666" alt="f884ce38fb9d5a1eb82ab5c8e29c872" src="https://github.com/ocrmypdf/OCRmyPDF/assets/107344218/9353d40e-c031-4e08-8905-7dd85167b130">

### Where are you installing from?

Linux package manager (apt, dnf, etc.), Ubuntu snap

### What operating system are you working on?

Linux

**Comment by matt-cassinelli** [comment]
Add `--skip-text`, `--redo-ocr`, or `--force-ocr` to the arguments when running
