### ISSUE TITLE
[Bug]: AttributeError: '_idat' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by 875d** [ocrmypdf/OCRmyPDF#1147]
### Describe the bug

```
xref 2364: While extracting this image, an error occurred
Traceback (most recent call last):
  File "[HOME_FOLDER]/.pyenv/versions/env3.11.4/lib/python3.11/site-packages/PIL/ImageFile.py", line 515, in _save
    fh = fp.fileno()
         ^^^^^^^^^
AttributeError: '_idat' object has no attribute 'fileno'
```

### Steps to reproduce

Run 

```
    ret = ocrmypdf.ocr(
        input_file = my_input_file,
        output_file = my_output_file,
        force_ocr = True,
        optimize = opt,
        language = ["ita", "eng"],
        jobs = 12)
```

### Files

Cannot attach input file as it's copyrighted

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

14.4.0

**Comment by 875d** [comment]
More detailed log:

[ocrmypdf_log.log](https://github.com/ocrmypdf/OCRmyPDF/files/12511329/ocrmypdf_log.log)

**Comment by jbarlow83** [comment]
From the log the true issue appears to be

[Errno 28] No space left on device
xref 2368: While extracting this image, an error occurred

See the documentation for more information about how ocrmypdf uses temporary storage.

**Comment by 875d** [comment]
Yes looks like my PDF was too big (~1GB) to be processed. It didn't work even from the command line.
