### ISSUE TITLE
[Bug]: Always get "FileNoFoundError on input fiel

### ISSUE THREAD

**Issue by drnicolas** [ocrmypdf/OCRmyPDF#1156]
### What were you trying to do?

With ocrmypdf 14.2.2 installed on CentOS7 via snap, I always get a FilenotFoundError on the input file regardless which type (pdf or tif). The inputfile is definietly existing.

running with the  -v 2 option I get this:

 ERROR ocrmypdf._sync - ExitCodeException
Traceback (most recent call last):
  File "/snap/ocrmypdf/75/lib/python3.8/site-packages/ocrmypdf/_validation.py", line 274, in create_input_file
    safe_symlink(options.input_file, target)
  File "/snap/ocrmypdf/75/lib/python3.8/site-packages/ocrmypdf/helpers.py", line 153, in safe_symlink
    raise FileNotFoundError(f"trying to create a broken symlink to {input_file}")
FileNotFoundError: trying to create a broken symlink to fax000000016.tif

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/ocrmypdf/75/lib/python3.8/site-packages/ocrmypdf/_sync.py", line 368, in run_pipeline
    start_input_file, original_filename = create_input_file(options, work_folder)
  File "/snap/ocrmypdf/75/lib/python3.8/site-packages/ocrmypdf/_validation.py", line 288, in create_input_file
    raise InputFileError(msg) from e
ocrmypdf.exceptions.InputFileError: File not found - fax000000016.tif

So far, I was not successful to solve this problem.

### Where are you installing from?

Ubuntu snap

### What operating system are you working on?

Linux

**Comment by jbarlow83** [comment]
Please provide the exact command line you were using to execute the ocrmypdf snap.

**Comment by drnicolas** [comment]
This particular problem is solved – I cannot tell you how exactly.
I guess, it is something from using Sangoma FreePBX, which is CentOS7 based.

But I have another problem:

I am using a template form which has a Logo and some Text in the upper right corner.
The upper left corner is then printed with a pinwriter (has medical offices in Germany still rely on pinwrtiters!).
It is the patient’s personal data, so name etc. and some insurance number.
The rest of the sheet is again pre-printed text.

I have the issue, that this pin-writer “block” is  not recognized and does not contain text. Everything else is fine.
Is there a parameter for ocrmypdf which can improve the quality of text recognition In this situation?

The other idea is to use a new ribbon cartridge for the printer.

Greetings from Germany,
Nicolas Nickisch


Von: jbarlow83 ***@***.***>
Gesendet: Dienstag, 10. Oktober 2023 10:03
An: ocrmypdf/OCRmyPDF ***@***.***>
Cc: N. Nickisch (User) ***@***.***>; Author ***@***.***>
Betreff: Re: [ocrmypdf/OCRmyPDF] [Bug]: Always get "FileNoFoundError on input fiel (Issue #1156)


Please provide the exact command line you were using to execute the ocrmypdf snap.

**Comment by hugobuddel** [comment]
Ah, it does work when placing the pdf in my home directory! Probably something to do with snap containment that I have very limited understanding off.

I'm happy now.

For reproducibility: the previous example had the pdf in `/tmp`

**Comment by jbarlow83** [comment]
I added a test that will complain if the input file is not found and you're inside a snap container.
