### ISSUE TITLE
[Feature]: Manually correcting OCR errors

### ISSUE THREAD

**Issue by tslivnik** [ocrmypdf/OCRmyPDF#1158]
### Describe the proposed feature

I use OCRmyPDF and it's wonderful. Thank you. However, as all OCR software, occasionally, there will be OCR errors. And sometimes I know how to manually correct those. However, I don't know how to actually edit the OCR in the PDF file. It would be useful either to have a feature where OCRmyPDF exposes some of its internal files (which it already does) but to expose such intermediate OCR text files which are editable and could be re-inserted into the rest of the workflow after being manually corrected. Or, I think it would also enhance the program if you could add references to other tools which can be used to manually add corrections to the invisible text layer in the PDF file, like you reference GNU parallel and other programs. I currently don't know how to do this on a Linux computer, and even if Google could be my friend, probably finding the best solution isn't so easy and it would be helpful to users if you could direct us to the best tool. Thank you.

**Comment by jbarlow83** [comment]
The new experimental APIs introduced in 15.4.0 make it possible to edit OCR.

**Comment by femifrak** [comment]
Is there already some doc that describes the possibility how to edit OCR?

**Comment by jbarlow83** [comment]
You manually edit the hOCR file. That's it at this point.

The author of gscan2pdf approached me about using ocrmypdf to process PDFs so it will become the GUI that does this. This feature was added to support that.

**Comment by endolith** [comment]
https://github.com/ocrmypdf/OCRmyPDF/discussions/1254
