### ISSUE TITLE
[Bug]: ocrmypdf v15.1.0+git8.2b0e1498 (snap): GPL Ghostscript 9.55.0: Can't find initialization file gs_init.ps. ghostscript.py:118

### ISSUE THREAD

**Issue by zWhdmB5T** [ocrmypdf/OCRmyPDF#1167]
### System
* OS: openSUSE Leap 15.5 x86_64
* `ocrmypdf            v15.1.0+git8.2b0e1498       101    latest/stable  shael7aerien   -`
`snapd               2.60.4                      20290  latest/stable  canonical✓     snapd`

### Bug
* GPL Ghostscript 9.55.0: Can't find initialization file gs_init.ps. ghostscript.py:118

### Where are you installing from?

Ubuntu snap

### What operating system are you working on?

Linux

### Relevant log output

```plain text
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 184/184 0:00:00
Start processing 4 pages concurrently                                                                                                                                            _sync.py:265
    1 GPL Ghostscript 9.55.0: Can't find initialization file gs_init.ps.                                                                                                   ghostscript.py:118
                                                                                                                                                                                             
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%   0/184 -:--:--
SubprocessOutputError: Ghostscript rasterizing failed                                                                                                                            _sync.py:450
```

**Comment by jbarlow83** [comment]
Command line?

**Comment by zWhdmB5T** [comment]
Sorry…
my regular command line `/snap/bin/ocrmypdf --language deu+eng+grc+lat --output-type pdfa --rotate-pages --deskew --clean Test-PDF.pdf Test-PDF.pdf`
but also the same error for `/snap/bin/ocrmypdf Test-PDF.pdf Test-PDF.pdf` or `/snap/bin/ocrmypdf Test-PDF.pdf Test-PDF-out.pdf`

**Comment by zWhdmB5T** [comment]
addition:
OCRmyPDF was working properly and find around one week ago, back then it was version 14.x.y by snap (can't remember specific version).
It was recently updated automatically by snap to the version stated above and now throws the stated error. I haven't changed my system otherwise except for regular updates (but no installs or removes).
I almost always use the command `/snap/bin/ocrmypdf --language deu+eng+grc+lat --output-type pdfa --rotate-pages --deskew --clean Test-PDF.pdf Test-PDF.pdf`, I just shortened it for this case to `/snap/bin/ocrmypdf Test-PDF.pdf Test-PDF-out.pdf`.

**Comment by zWhdmB5T** [comment]
just FYI: I did snap revert to `ocrmypdf            v14.2.1+git4.5a82ad63       75     latest/stable  shael7aerien   -
`. Now, it works properly and fine again.

**Comment by jbarlow83** [comment]
Yes, the old image is based on Ubuntu 20.04 and new one is on 22.04. Ocrmypdf 15 doesn't support the 20.04 dependencies anymore, and the problem is something wrong with how Ghostscript is packaged in 22.04.

**Comment by Ccrlll** [comment]
may you're running it on root try running it on user

**Comment by jbarlow83** [comment]
@brlin-tw Any chance you can help with this since you previously helped with the ocrmypdf snap?

**Comment by brlin-tw** [comment]
Sure I'll check it out, no promises for any ETAs, though.

**Comment by loxK** [comment]
I have this exact issue, tried the pip3 version, same issue.

**Comment by zWhdmB5T** [comment]
There are new Snap releases at [Install OCRmyPDF on Linux | Snap Store](https://snapcraft.io/ocrmypdf)… Do they work? I am wondering a bit because @jbarlow83 hasn't said yet that the issue is resolved.

**Comment by jbarlow83** [comment]
The build script are configured to auto-release new versions of the main code, but I don't know much about snap or how to fix the snap-specific issues that are coming up. Snap is on the chopping block at this point - I tried to fix it, but I can't find answers to basic questions about how snap is supposed to work in its official documentation, so I'm hoping others with domain knowledge will be able to fix it.

**Comment by zWhdmB5T** [comment]
OK, understood. Maybe, @brlin-tw can help as you asked him before. Or someone else having knowledge about Snap.

Hopefully, this issue can be resolved, so I can upgrade from v14 to v15 of OCRmyPDF Snap.

**Comment by brlin-tw** [comment]
> @jbarlow83 @brlin-tw  Sorry for this inquiry. Any news on this issue?

Apologies for the ignorance, unfortunately I'm being out-of-capacity recently and got little time looking into it, I'll make sure to let you know if there's any progress(or, in a very unlikely event, not fixable).

**Comment by omidraha** [comment]
```
snap install ocrmypdf
```
```
 ocrmypdf --skip-text in.pdf  out.pdf
```


```

Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 91/91 0:00:00
Start processing 8 pages concurrently                                                                                              ocr.py:96
    1 Weight average image DPI is 321.7, max DPI is 600.0. The discrepancy may indicate a high detail region on this page,  _pipeline.py:477
but could also indicate a problem with the input PDF file. Page image will be rendered at 400.0 DPI.                                        
    2 GPL Ghostscript 9.55.0: Can't find initialization file gs_init.ps.                                                  ghostscript.py:139
                                                                                                                                            
   10 Weight average image DPI is 334.0, max DPI is 600.0. The discrepancy may indicate a high detail region on this page,  _pipeline.py:477
but could also indicate a problem with the input PDF file. Page image will be rendered at 400.0 DPI.                                        
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%  0/91 -:--:--
SubprocessOutputError: Ghostscript rasterizing failed  
```

**Comment by loxK** [comment]
@omidraha the fix is only available in the channel `latest/edge`. See the dates and version (before updating) :

```
# snap info ocrmypdf
name:      ocrmypdf
summary:   OCRmyPDF adds a searchable text layer to scanned PDF files
publisher: James Barlow (shael7aerien)
store-url: https://snapcraft.io/ocrmypdf
license:   MPL-2.0
description: |
  OCRmyPDF packaged for snap
commands:
  - ocrmypdf
snap-id:      4gaxtpdrLWomuJZubaPeur6sfzfkG1Do
tracking:     latest/stable
refresh-date: Il y a 44 jours, à 15 h 51 HNR
channels:
  latest/stable:    v16.1.2+git14.0e013df1 2024-04-19 (149) 411MB -
  latest/candidate: ↑                                             
  latest/beta:      ↑                                             
  latest/edge:      v16.3.1+git18.964b30ca 2024-06-12 (159) 409MB -
installed:          v16.1.2+git14.0e013df1            (149) 411MB -
```

To install it you have to :

`snap refresh ocrmypdf --channel latest/edge`

**Comment by zWhdmB5T** [comment]
@jbarlow83 @loxK @omidraha 
FYI: latest `latest/edge` does work fine here. (I originally opened this ticket…)
