### ISSUE TITLE
[Bug] [Help Needed] Command "ocrmypdf" not found [Windows 11] 

### ISSUE THREAD

**Issue by Alaiya** [ocrmypdf/OCRmyPDF#1168]
### What were you trying to do?

I am using Windows 11 and am trying to get ocrmypdf to work. I installed it according to the [installation guide](https://ocrmypdf.readthedocs.io/en/latest/installation.html), as I really need a way to use OCR on several scanned PDFs. But after having installed it as done, I am trying to use it via the command line and it just gives back the error "Cannot find the command ocrmypdf".

I am assuming this is an issue with the windows installation. So I might just using it wrong. 

But so far I have not managed to get it to work.

So, help is needed. Thank you in advance.

### Where are you installing from?

Wndows package manager (chocolatey, etc.)

### What operating system are you working on?

Windows

**Comment by jbarlow83** [comment]
From the command line, can you run any of these successfully?

`python`

`python -m ocrmypdf --help`

`python -c 'import ocrmypdf; print(ocrmypdf.__version__)'`

**Comment by jbarlow83** [comment]
closed due to response
