### ISSUE TITLE
Is building OCRmyPDF and it's dependencies in a docker environment less performant?

### ISSUE THREAD

**Issue by wadeflash12** [ocrmypdf/OCRmyPDF#1177]
### What were you trying to do?

Hello!

Reading the [docs](https://ocrmypdf.readthedocs.io/en/latest/docker.html), it mentions that `For users who already have Docker installed this may be an easy and convenient option. However, it is less performant than a system installation and may require Docker engine configuration`

Is it advisable to build ocrmypdf within a docker image? What are the performance issues? 

I'm building a custom OCR pipeline with custom deskew/rotate logic combined with OCRmypdf. 

### Where are you installing from?

Linux package manager (apt, dnf, etc.)

### What operating system are you working on?

Linux

**Comment by jbarlow83** [comment]
>Is it advisable to build ocrmypdf within a docker image?

I assume you meant run, not build. For your use case of adding custom logic and possibly difficult-to-install libraries, Docker probably makes sense.

>What are the performance issues?

I updated the documentation to answer your question. When the commit is pushed it will read:

>On platforms other than Linux, Docker runs in a virtual machine, and so may 
be less performant. You may also want to adjust the Docker virtual machine's
memory and CPU allocation. On Linux, the Docker image runs natively and
performance is comparable to a system installation.
