### ISSUE TITLE
[Bug]: "inplace" + --skip-text on PDF with only text modifies / outputs a file

### ISSUE THREAD

**Issue by jrz** [ocrmypdf/OCRmyPDF#1179]
### What were you trying to do?

I'm trying to ocr a bunch of files "in place" (according to the docs, you need to specify the input file twice).
The file already has text layers (either because of another app or ocrmypdf).

During execution, the log says:
`1 skipping all processing on this page                      _pipeline.py:318`
and
`Postprocessing...                                     _sync.py:314`

I did not specify any postprocessing options, and I get the same behaviour when using --output-type pdf.

It is not the behavior I was expecting. If it is "by design", there should be an extra flag:  --skip-alltext-document or something. It actually should already behaver correctly when setting --output-type pdf. According the docs: " 'pdf' attempts to preserve file contents as much as possible", but it doesn't. When skipping the complete document, the file should be untouched. This might be difficult when input = output file.. which is why there should be an --inplace option. With that option, you could also accept a list of files to OCR inplace.

Side note: --skip-text is not shown in the short usage screen (for ex. octmypdf --help..), although it is in ocrmypdf -h

Version 15.3.0

### Where are you installing from?

Homebrew

### What operating system are you working on?

macOS

### Relevant log output

```plain text
# File without any text, 1 page
# └──▶ ocrmypdf --skip-text --output-type pdf testfile1.pdf testfile1.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Postprocessing...                   _sync.py:314
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization ratio: 1.20 savings: 16.7%              _pipeline.py:1030
Total file size ratio: 1.19 savings: 16.1%                 _pipeline.py:1033

# └──▶ ocrmypdf --skip-text --output-type pdf testfile1.pdf testfile1.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Postprocessing...                   _sync.py:314
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization ratio: 1.00 savings: 0.5%               _pipeline.py:1030
Total file size ratio: 1.00 savings: -0.1%                 _pipeline.py:1033


# File with text layer from other app:

# └──▶ ocrmypdf --skip-text --output-type pdf testfile2.pdf testfile2.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3 0:00:00
Start processing 3 pages concurrently                           _sync.py:265
    1 skipping all processing on this page                  _pipeline.py:318
    2 skipping all processing on this page                  _pipeline.py:318
    3 skipping all processing on this page                  _pipeline.py:318
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3 0:00:00
Postprocessing...                   _sync.py:314
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization ratio: 1.00 savings: 0.0%               _pipeline.py:1030
Total file size ratio: 1.00 savings: 0.0%                  _pipeline.py:1033
```

**Comment by jbarlow83** [comment]
I understand this may be unexpected, but OCRmyPDF's assumption is that you must want something done to the file if you are invoking it with `--skip-text`, so the default behavior is to perform safe optimizations and fixes. The input file is not necessarily left unmodified even with `--skip-text` and that has never been the intention. 

It sounds like you might actually want to do just `ocrmypdf in.pdf in.pdf` without other arguments. That will make no changes and exit with an error code - it makes no changes in place.

I will clarify the help text: `'pdf' attempts to preserve file contents as much as possible` will become `'pdf' minimizes changes to the input file`.

>Side note: --skip-text is not shown in the short usage screen (for ex. octmypdf --help..), although it is in ocrmypdf -h

argparse displays only the short form, `-s` in this case, when a short form is available. Some day I will switch to typer and probably introduce something along the lines of  `--mode=skip-text | force-ocr | normal | ...`

**Comment by jbarlow83** [comment]
I see your point - on macOS any extended attributes will be overwritten if the output file is modified and this is not the expected behavior on that platform. (For example, if a file is tagged "Green" and then edited or duplicate in Preview, it retains this tag.)

I will see if I can file a way to copy extended attributes from input to output in a future release.

**Comment by jbarlow83** [comment]
I did add some code that improves the copying of attributes and I think ACLs.

macOS extended attributes cannot be copied with the standard Python library, however. There is a private library that takes of this but I'd prefer to not introduce a platform specific behavior difference. You can use the `tag` utility (I believe it's a built in macOS tool) in a script to tag files.
