### ISSUE TITLE
Does OCRmyPDF break macOS "Live Text" feature?

### ISSUE THREAD

**Issue by rennefJ** [ocrmypdf/OCRmyPDF#1182]
macOS on ARM CPUs comes with a feature called "live text".
https://support.apple.com/en-ca/guide/preview/prvw625a5b2c/mac
When I open a pdf processed by OCRmyPDF in preview, the "live text" feature does not seem to work anymore.
When I scan a file to pdf  using "Image capture" and use the builtin OCR, "live text" still works.
I can also reduce that pdf file size using a quartz filter and it still works.
I have tried a bunch of different options on OCRmyPDF, but I could not make the produced pdfs work with "live text.
Can someone confirm this behavior?

**Comment by jbarlow83** [comment]
I suspect macOS disables live text when text in the image has been recognized. When would you need both?

**Comment by rennefJ** [comment]
@jbarlow83  you are probably right.
At first I thought the live text feature has a more powerful recognition, especially for challenging cases, than the built-in from image-capture or OCRmyPDF. 
But I did some more tests, and it seems that when there is already an ocr layer present then preview uses that instead of generating one on the fly with live text.
I will keep an eye on this, but lets close this for now.
Thanks
