### ISSUE TITLE
[Bug]: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by MvCast** [ocrmypdf/OCRmyPDF#1184]
### Describe the bug

Hi there!,

I installed both Ghostscript and Tesseract throught scoop and OCRmyPDF with pip, although I first installed Tesseract through winget.

When I had Tesseract installed through winget, I got the "[WinError 2] ..." message when the program when starting to process pages. I then installed it through scoop and those went away, but I still get one and I don't know what could be going on.

The process seems to go through since I get an output file, but that error persists.

I have tried to update python and reinstalling both Tesseract and Ghostscript, but none of this has helped.

### Steps to reproduce

```plain text
1. Run ocrmypdf input.pdf output.pdf
```

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

15.4.0

### Relevant log output

```plain text
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 7/7 0:00:00
Start processing 7 pages concurrently                                                                          ocr.py:98
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 7/7 0:00:00
Postprocessing...                                                                                             ocr.py:147
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 7/7 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
[WinError 2] El sistema no puede encontrar el archivo especificado                                        _windows.py:92
Image optimization ratio: 1.50 savings: 33.4%                                                           _pipeline.py:904
Total file size ratio: 1.49 savings: 32.7%                                                              _pipeline.py:907
Output file is a PDF/A-2B (as expected)                                                                   _common.py:425
```

**Comment by jbarlow83** [comment]
The error is "file not found" probably from attempting to check for pngquant and jbig2; installing these would likely fix the issue. I don't know why a WinError appears rather than a FileNotFoundError. Could not reproduce on English Windows 10/Python 3.12.

What version of Python did you use? Maybe the older versions are quirky.

Either way it is harmless. If an explanation can be found as to why WinError appears I wlll attempt a fix.
