### ISSUE TITLE
[Bug]: Unable to install GhostScript using Winget

### ISSUE THREAD

**Issue by xd003** [ocrmypdf/OCRmyPDF#1198]
### What were you trying to do?

As per the documenation [here](https://docs.microsoft.com/en-us/windows/package-manager/winget/), i am trying to install OCRmyPDF on Windows using Winget. When trying to install ghostscript just as mentioned, it gives an error stating that the package was not found.

`~> winget install -e --id ArtifexSoftware.GhostScript `
`No package found matching input criteria.`

### Where are you installing from?

Wndows package manager (chocolatey, etc.)

### What operating system are you working on?

Windows

**Comment by jbarlow83** [comment]
Fixed v15.4.4

**Comment by xantilon** [comment]
the problem still (or again) exists
