### ISSUE TITLE
[Bug]: Progress Bar is missing when running in Google Colab

### ISSUE THREAD

**Issue by Warborn123** [ocrmypdf/OCRmyPDF#1199]
### What were you trying to do?

I found this .ipynb [link](https://colab.research.google.com/github/louispaulet/OCRmyPDF_google_colab/blob/main/PDF_OCR.ipynb) online, and it works really well with the file I tested, but I just can't enable the progress bar. 
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/54515949/fcb5ff5e-d03e-44f5-b03b-4f0556f3985f)

I was hoping to get something like this:
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/54515949/6c0f0c00-ec3a-47da-8964-56c9b86575fd)

### Where are you installing from?

Homebrew

**Comment by jbarlow83** [comment]
stale
