### ISSUE TITLE
I scan the documents with my Brother MFC-L8690CDW and it worked until v15.4.4

### ISSUE THREAD

**Issue by knabed** [ocrmypdf/OCRmyPDF#1210]
I scan the documents with my Brother MFC-L8690CDW and it worked until v15.4.4
I ran "ocrmypdf -frd -l deu+eng" with latest image on the file attached 
This problem applies on every scan since I used images after v15.4.4
[20231220_180411_printer_002441.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/13730206/20231220_180411_printer_002441.pdf)

_Originally posted by @knabed in https://github.com/ocrmypdf/OCRmyPDF/issues/1209#issuecomment-1864845921_

**Comment by jbarlow83** [comment]
Thanks for the information - Fixed in 16.0.1

```
OCR Texterkennung - Testdokument
Test von OCR-Lésungen, die von der Archivierungssoftware "Office Manager" unterstiitzt werden.

Konigs Wusterhausen im Juli 2011, Softwarebiiro Krekeler http://www.krekeler.de




Datum: 01.07.2011


Nummer: 01-23.456789


Zeichen:              0123456789

                      abcdefghijklmnopqrstuvwxyz


                      ABCDEFGHIJKLMNOPQURSTUVEXYZ


FlieStext: Mit diesem Test méchten wir die Erkennungsgenauigkeit unterschiedlicher OCR-

Programme testen, um unseren Anwendern Tipps fiir die Auswahl der richtigen Losung geben zu
konnen.


Tabelle:


Rechnungsnummer | AR1234
Lieferung vom              30.06.2011



Kleine SchriftgroRe
```
