### ISSUE TITLE
[Bug]: NotImplementedError

### ISSUE THREAD

**Issue by gdandersson** [ocrmypdf/OCRmyPDF#1211]
### What were you trying to do?

`NotImplementedError: Don't how to retrieve default /Decode array for image<pikepdf.PdfImage image mode=? size=3800x6400 at 0x1078b4440`

Running ocrmypdf on multiple PDF files (which contain data which can't be shared). Recently updated to v 16.0.0, which I think this bug coincided with.

### Where are you installing from?

Homebrew

### What operating system are you working on?

macOS

### Relevant log output

```plain text
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2 0:00:00
Start processing 2 pages concurrently                                                                                                                                                                                   ocr.py:98
    1 redoing OCR                                                                                                                                                                                                _pipeline.py:314
    2 redoing OCR                                                                                                                                                                                                _pipeline.py:314
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2 0:00:00
Postprocessing...                                                                                                                                                                                                      ocr.py:147
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2 0:00:00
xref 25: While extracting this image, an error occurred                                                                                                                                                           optimize.py:321
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ocrmypdf/16.0.0/libexec/lib/python3.12/site-packages/ocrmypdf/optimize.py", line 317, in extract_images
    result = extract_fn(
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ocrmypdf/16.0.0/libexec/lib/python3.12/site-packages/ocrmypdf/optimize.py", line 156, in extract_image_jbig2
    ext = pim.extract_to(stream=f)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 702, in extract_to
    return self._extract_to_stream(stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 642, in _extract_to_stream
    direct_extraction = self._extract_direct(stream=stream)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 534, in _extract_direct
    stream.write(self._generate_ccitt_header(data, icc=icc))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 769, in _generate_ccitt_header
    decode = self._decode_array
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 181, in _decode_array
    raise NotImplementedError(
NotImplementedError: Don't how to retrieve default /Decode array for image<pikepdf.PdfImage image mode=? size=4128x5752 at 0x1078b4440>
xref 22: While extracting this image, an error occurred                                                                                                                                                           optimize.py:321
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ocrmypdf/16.0.0/libexec/lib/python3.12/site-packages/ocrmypdf/optimize.py", line 317, in extract_images
    result = extract_fn(
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ocrmypdf/16.0.0/libexec/lib/python3.12/site-packages/ocrmypdf/optimize.py", line 156, in extract_image_jbig2
    ext = pim.extract_to(stream=f)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 702, in extract_to
    return self._extract_to_stream(stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 642, in _extract_to_stream
    direct_extraction = self._extract_direct(stream=stream)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 534, in _extract_direct
    stream.write(self._generate_ccitt_header(data, icc=icc))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 769, in _generate_ccitt_header
    decode = self._decode_array
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/img2pdf/libexec/lib/python3.12/site-packages/pikepdf/models/image.py", line 181, in _decode_array
    raise NotImplementedError(
NotImplementedError: Don't how to retrieve default /Decode array for image<pikepdf.PdfImage image mode=? size=3800x6400 at 0x1078b4440>
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization ratio: 1.67 savings: 40.0%                                                                                                                                                                    _pipeline.py:904
Total file size ratio: 1.64 savings: 39.2%                                                                                                                                                                       _pipeline.py:907
Output file is a PDF/A-2B (as expected)                                                                                                                                                                            _common.py:441
```

**Comment by jbarlow83** [comment]
Run `qpdf --json input.pdf` and paste results here. That shows some metadata but does not reveal private information and may be enough to see what's happening here.

Note that ocrmypdf was successful in processing the file. The error just means that 2 images could not be optimized because they use unusual PDF features.

**Comment by gdandersson** [comment]
`{
  "version": 2,
  "parameters": {
    "decodelevel": "generalized"
  },
  "pages": [
    {
      "contents": [
        "27 0 R",
        "28 0 R",
        "24 0 R"
      ],
      "images": [
        {
          "bitspercomponent": 8,
          "colorspace": "/DeviceRGB",
          "decodeparms": [
            null
          ],
          "filter": [
            "/DCTDecode"
          ],
          "filterable": false,
          "height": 3507,
          "name": "/Obj4",
          "object": "22 0 R",
          "width": 2480
        }
      ],
      "label": null,
      "object": "21 0 R",
      "outlines": [],
      "pageposfrom1": 1
    },
    {
      "contents": [
        "7 0 R",
        "8 0 R",
        "4 0 R"
      ],
      "images": [
        {
          "bitspercomponent": 8,
          "colorspace": "/DeviceRGB",
          "decodeparms": [
            null
          ],
          "filter": [
            "/DCTDecode"
          ],
          "filterable": false,
          "height": 3507,
          "name": "/Obj4",
          "object": "2 0 R",
          "width": 2480
        }
      ],
      "label": null,
      "object": "1 0 R",
      "outlines": [],
      "pageposfrom1": 2
    },
    {
      "contents": [
        "15 0 R",
        "16 0 R",
        "12 0 R"
      ],
      "images": [
        {
          "bitspercomponent": 8,
          "colorspace": "/DeviceRGB",
          "decodeparms": [
            null
          ],
          "filter": [
            "/DCTDecode"
          ],
          "filterable": false,
          "height": 3507,
          "name": "/Obj4",
          "object": "10 0 R",
          "width": 2480
        }
      ],
      "label": null,
      "object": "9 0 R",
      "outlines": [],
      "pageposfrom1": 3
    }
  ],
  "pagelabels": [],
  "acroform": {
    "fields": [],
    "hasacroform": false,
    "needappearances": false
  },
  "attachments": {},
  "encrypt": {
    "capabilities": {
      "accessibility": true,
      "extract": true,
      "modify": true,
      "modifyannotations": true,
      "modifyassembly": true,
      "modifyforms": true,
      "modifyother": true,
      "printhigh": true,
      "printlow": true
    },
    "encrypted": false,
    "ownerpasswordmatched": false,
    "parameters": {
      "P": 0,
      "R": 0,
      "V": 0,
      "bits": 0,
      "filemethod": "none",
      "key": null,
      "method": "none",
      "streammethod": "none",
      "stringmethod": "none"
    },
    "recovereduserpassword": null,
    "userpasswordmatched": false
  },
  "outlines": [],
  "qpdf": [
    {
      "jsonversion": 2,
      "pdfversion": "1.3",
      "pushedinheritedpageresources": false,
      "calledgetallpages": true,
      "maxobjectid": 28
    },
    {
      "obj:1 0 R": {
        "value": {
          "/Contents": [
            "7 0 R",
            "8 0 R",
            "4 0 R"
          ],
          "/MediaBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Parent": "17 0 R",
          "/Resources": {
            "/Font": {
              "/F3": "5 0 R"
            },
            "/ProcSet": [
              "/PDF",
              "/Text",
              "/ImageB",
              "/ImageC",
              "/ImageI"
            ],
            "/Subtype": "6 0 R",
            "/XObject": {
              "/Obj4": "2 0 R",
              "/Obj5": "3 0 R"
            }
          },
          "/Rotate": 0,
          "/TrimBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Type": "/Page"
        }
      },
      "obj:2 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 8,
            "/ColorSpace": "/DeviceRGB",
            "/Filter": "/DCTDecode",
            "/Height": 3507,
            "/Length": 277030,
            "/Name": "/Obj4",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 2480
          }
        }
      },
      "obj:3 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 1,
            "/DecodeParms": {
              "/Columns": 4176,
              "/K": -1
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 1488,
            "/ImageMask": true,
            "/Length": 12932,
            "/Name": "/Obj5",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 4176
          }
        }
      },
      "obj:4 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 790
          }
        }
      },
      "obj:5 0 R": {
        "value": {
          "/BaseFont": "/Helvetica",
          "/Encoding": "/WinAnsiEncoding",
          "/Subtype": "/Type1",
          "/Type": "/Font"
        }
      },
      "obj:6 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 234
          }
        }
      },
      "obj:7 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 35
          }
        }
      },
      "obj:8 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 84
          }
        }
      },
      "obj:9 0 R": {
        "value": {
          "/Contents": [
            "15 0 R",
            "16 0 R",
            "12 0 R"
          ],
          "/MediaBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Parent": "17 0 R",
          "/Resources": {
            "/Font": {
              "/F3": "13 0 R"
            },
            "/ProcSet": [
              "/PDF",
              "/Text",
              "/ImageB",
              "/ImageC",
              "/ImageI"
            ],
            "/Subtype": "14 0 R",
            "/XObject": {
              "/Obj4": "10 0 R",
              "/Obj5": "11 0 R"
            }
          },
          "/Rotate": 0,
          "/TrimBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Type": "/Page"
        }
      },
      "obj:10 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 8,
            "/ColorSpace": "/DeviceRGB",
            "/Filter": "/DCTDecode",
            "/Height": 3507,
            "/Length": 407248,
            "/Name": "/Obj4",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 2480
          }
        }
      },
      "obj:11 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 1,
            "/DecodeParms": {
              "/Columns": 4056,
              "/K": -1
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 5952,
            "/ImageMask": true,
            "/Length": 69814,
            "/Name": "/Obj5",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 4056
          }
        }
      },
      "obj:12 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 2929
          }
        }
      },
      "obj:13 0 R": {
        "value": {
          "/BaseFont": "/Helvetica",
          "/Encoding": "/WinAnsiEncoding",
          "/Subtype": "/Type1",
          "/Type": "/Font"
        }
      },
      "obj:14 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 780
          }
        }
      },
      "obj:15 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 35
          }
        }
      },
      "obj:16 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 84
          }
        }
      },
      "obj:17 0 R": {
        "value": {
          "/Count": 3,
          "/Kids": [
            "21 0 R",
            "1 0 R",
            "9 0 R"
          ],
          "/Type": "/Pages"
        }
      },
      "obj:18 0 R": {
        "value": {
          "/E": 402090,
          "/H": [
            655,
            146
          ],
          "/L": 1176807,
          "/Linearized": 1,
          "/N": 3,
          "/O": 21,
          "/T": 1176328
        }
      },
      "obj:19 0 R": {
        "value": {
          "/Pages": "17 0 R",
          "/Type": "/Catalog"
        }
      },
      "obj:20 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 68,
            "/S": 50
          }
        }
      },
      "obj:21 0 R": {
        "value": {
          "/Contents": [
            "27 0 R",
            "28 0 R",
            "24 0 R"
          ],
          "/MediaBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Parent": "17 0 R",
          "/Resources": {
            "/Font": {
              "/F3": "25 0 R"
            },
            "/ProcSet": [
              "/PDF",
              "/Text",
              "/ImageB",
              "/ImageC",
              "/ImageI"
            ],
            "/Subtype": "26 0 R",
            "/XObject": {
              "/Obj4": "22 0 R",
              "/Obj5": "23 0 R"
            }
          },
          "/Rotate": 0,
          "/TrimBox": [
            0,
            0,
            595.2,
            841.68
          ],
          "/Type": "/Page"
        }
      },
      "obj:22 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 8,
            "/ColorSpace": "/DeviceRGB",
            "/Filter": "/DCTDecode",
            "/Height": 3507,
            "/Length": 353889,
            "/Name": "/Obj4",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 2480
          }
        }
      },
      "obj:23 0 R": {
        "stream": {
          "dict": {
            "/BitsPerComponent": 1,
            "/DecodeParms": {
              "/Columns": 3816,
              "/K": -1
            },
            "/Filter": "/CCITTFaxDecode",
            "/Height": 6408,
            "/ImageMask": true,
            "/Length": 43160,
            "/Name": "/Obj5",
            "/Subtype": "/Image",
            "/Type": "/XObject",
            "/Width": 3816
          }
        }
      },
      "obj:24 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 2387
          }
        }
      },
      "obj:25 0 R": {
        "value": {
          "/BaseFont": "/Helvetica",
          "/Encoding": "/WinAnsiEncoding",
          "/Subtype": "/Type1",
          "/Type": "/Font"
        }
      },
      "obj:26 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 645
          }
        }
      },
      "obj:27 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 35
          }
        }
      },
      "obj:28 0 R": {
        "stream": {
          "dict": {
            "/Filter": "/FlateDecode",
            "/Length": 84
          }
        }
      },
      "trailer": {
        "value": {
          "/ID": [
            "b:e736941f8fa13f08849cc4683493f5a8",
            "b:102a9b5dac0b0f8c223f279a52c7f17f"
          ],
          "/Prev": 1176319,
          "/Root": "19 0 R",
          "/Size": 29
        }
      }
    }
  ]
}
`

Reason I reacted to this is because the quality of the OCR has gone down.. a lot. It fails quite miserably compared to the previous batch I did (language is swedish, if that makes a difference)

**Comment by jbarlow83** [comment]
Do you have 16.0.1?

**Comment by gdandersson** [comment]
This batch was run on 16.0.0, just upgraded to 16.0.1.post1 2 minutes ago

**Comment by gdandersson** [comment]
PikePDF version was 7.2, updated to 8.10.1, thinking that might be the problem. No difference..

**Comment by gdandersson** [comment]
Updated to version 16.0.2 of OCRmyPDF and that does seem to have solved the the problem(!)

**Comment by monneyboi** [comment]
I'm getting this same error on this [octatrack manual](https://cdn.www.elektron.se/media/downloads/octatrack-mkii/Octatrack-MKII-User-Manual_ENG_OS1.40A_210414.pdf)

Running on docker image:
```
jbarlow83/ocrmypdf-alpine   latest    5f5b2c3e2837   7 days ago          528MB
```

**Comment by jbarlow83** [comment]
@monneyboi For what I assume is the error you encountered, the errors are acceptable. They mean only that the optimizer can't optimize certain images - the file in question has images set up for high quality offset printing or something along those lines.
