### ISSUE TITLE
[Bug]: Persian rendering and text positioning errors in 16.0.1 with new renderer

### ISSUE THREAD

**Issue by Rosti2022** [ocrmypdf/OCRmyPDF#1214]
### Describe the bug

I am running 16.0.1, and the rendering of Persian text after OCR is still problematic with PDF viewers such as the default one on Mac OS, Preview. The characters are all stuck together, and the selectable rows are not aligned with the text on the page, making selecting and highlighting text problematic. The older renderer, sandwich, is more precise and separates words when used in tandem with very specific viewers, such as PDFPSKit-based ones. I have attached a sample OCRed PDF file. 

### Steps to reproduce

```plain text
Run OCRmyPDF normally on a given PDF file, with the new renderer introduced in 16.0.0
```

### Files

[DastanTestOCR.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/13759600/DastanTestOCR.pdf)

### How did you download and install the software?

Homebrew

### OCRmyPDF version

16.0.1.post1

**Comment by jbarlow83** [comment]
I'll manage this issue in #1216 which is mostly the same issue.
