### ISSUE TITLE
[Bug]: Every PDF I OCR has the text misaligned with the image.

### ISSUE THREAD

**Issue by advert665** [ocrmypdf/OCRmyPDF#1215]
### What were you trying to do?

![OCR](https://github.com/ocrmypdf/OCRmyPDF/assets/77785968/db843c06-e753-4b76-9379-3f4c6a70ac0e)

Thank you for making this app, it's very helpful. Unfortunately, every pdf I OCR, ends up with a misalignment with the text just below the image. This occurs on both Windows 11 (installed with pip) & MacOS (installed with homebrew). I'm using the standard command with no options, but have tried --deskew. Any other ideas on how to fix it? Thanks!

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Windows

**Comment by jbarlow83** [comment]
Wrong issue template, no test file, no test command line, no program version, can't help

**Comment by advert665** [comment]
Apologies, as the problem happened with every pdf I didn't think it was correct to select the 'issue with a specific pdf' template. Now resubmitted with all the information required. https://github.com/ocrmypdf/OCRmyPDF/issues/1216

**Comment by jbarlow83** [comment]
Sorry about that, a few other issues were reported today with inadequate details and so I got generally frustrated.

**Comment by advert665** [comment]
That's really no problem, very understandable! Thanks for fixing the issue!
