### ISSUE TITLE
[Feature]: Are tesseract scripts supported?

### ISSUE THREAD

**Issue by eightfiftytwo** [ocrmypdf/OCRmyPDF#1218]
### Describe the proposed feature

See https://github.com/tesseract-ocr/langdata_lstm/tree/main/script
Tesseract supports scripts like Hangul or Han characters.
[It seems like](https://groups.google.com/g/tesseract-ocr/c/aquIaYX-dZk) this could be a better option many non-latin languages.
I can't find documentation for this in ocrmypdf. If it is not supported would you consider it? Thank you.

**Comment by jbarlow83** [comment]
Yes. If you issue the  `-l anything` argument, ocrmypdf will forward the language request to Tesseract. If a custom language pack or fine tune or other customization is installed as a .traineddata where Tesseract can find it, then Tesseract will use it. It has worked this way for a long time. 

I'll update the documentation to mention this possibility.
