### ISSUE TITLE
[Bug]: Package 'pngquant' not found, exists on PATH

### ISSUE THREAD

**Issue by dumoulinalex** [ocrmypdf/OCRmyPDF#1219]
### What were you trying to do?

I wanted to try more aggressive lossy optimizations through the `--optimize` option. Using the option in a command however resulted in an error message stating the 'pngquant' cannot be found.

```
C:\Users\user>ocrmypdf -l fra --optimize 3 "D:\input.pdf" "D:\output.pdf"

The program 'pngquant' could not be executed or was not found on your
system PATH.  This program is required when you use the
--optimize {2,3} arguments.  You could try omitting these arguments, or install
the package.


If not already installed, install the Chocolatey package manager. Then use
a command prompt to install the missing package:
    choco install pngquant
Could not find program 'pngquant' on the PATH
```
The result is the same if `--optimize 2` is used.

I installed the `pngquant` package through `pip`, but still got the same error. I thought perhaps the path to the package isn't added to the PATH environment variable, but I can see the `pngquant` folder under the same directory as the `ocrmypdf` folder:

%USERPROFILE%\AppData\Local\Programs\Python\Python310\Lib\site-packages\

```
C:\Users\user>pip install pngquant
Requirement already satisfied: pngquant in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (1.0.7)
Requirement already satisfied: Pillow in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pngquant) (9.2.0)
```

I'm not sure where else to look to further drill down the issue.

I am using `-l fra` because the source material is in French. The file `input.pdf` is a scanned document saved as a PDF that doesn't contain recognized text but contains readable text.

My objective is to explore the file size savings that more aggressive optimization may provide. I am trying to go paperless and am still figuring what balance of loss of quality is tolerable for long term storage of lowly to mildly useful documents.

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Windows

### Relevant log output

```plain text
The program 'pngquant' could not be executed or was not found on your
system PATH.  This program is required when you use the
--optimize {2,3} arguments.  You could try omitting these arguments, or install
the package.


If not already installed, install the Chocolatey package manager. Then use
a command prompt to install the missing package:
    choco install pngquant
Could not find program 'pngquant' on the PATH
```

**Comment by jbarlow83** [comment]
You'll need to install pngquant using choco, winget, or a manual install.

Unfortunately there is a Python package named "pngquant" on PyPI. It looks like this is a
third party effort at wrapping pngquant in a Python package, but it has not been updated since 2019, so it's not reliable enough to use as a possible pngquant provider.
