### ISSUE TITLE
[Bug]: Conda - pikepdf is unavailable

### ISSUE THREAD

**Issue by kielbowicz** [ocrmypdf/OCRmyPDF#1232]
### What were you trying to do?

Hey!

I am haveing troubles to install ocrmypdf package via conda. I am getting info:
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/96266571/3ac137cc-b611-4a3f-a68f-85eba83f2484)

I have no idea about that, I cannot find this package dor conda env.

Thanks in advance if You have any ideas how to resolve it!

### Where are you installing from?

Conda

### What operating system are you working on?

Windows

### Relevant log output

```plain text
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides pikepdf needed by ocrmypdf-11.6.2-pyhd8ed1ab_0

Could not solve for environment specs
The following packages are incompatible
└─ ocrmypdf is not installable because there are no viable options
   ├─ ocrmypdf [11.6.2|11.7.0|...|12.4.0] would require
   │  └─ pikepdf, which does not exist (perhaps a missing channel);
   ├─ ocrmypdf [12.5.0|12.6.0|...|13.6.0] would require
   │  └─ pikepdf >=2.10 , which does not exist (perhaps a missing channel);
   └─ ocrmypdf [13.6.1|13.6.2|...|14.2.0] would require
      └─ pikepdf >=5.1 , which does not exist (perhaps a missing channel).
```

**Comment by jbarlow83** [comment]
I'm afraid you'll have to report this to conda, which has its own custom packaging process that is not working here; or use standard Python.
