### ISSUE TITLE
[Feature]: Explain on the docs how to change the language of OCR on watcher.py

### ISSUE THREAD

**Issue by iohann95** [ocrmypdf/OCRmyPDF#1235]
### Describe the proposed feature

Hello, good evening.

Watcher.py works great for me, but unfortunately, even trying very hard I can't seem to figure how how to change the defualt language of the OCR to some  other.

I already installed the language pack (tesseract-ocr-por) and it works great on normal ocrmypdf use but I can't seem to make it work on watcher.py.

thanks!!!

**Comment by jbarlow83** [comment]
`watcher.py --ocr-json-settings '{"language": "por"}'`

All arguments can be pass via `--ocr-json-settings`.
