### ISSUE TITLE
[Feature]: More Accessible Via Consistently connecting words to form sentences.

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [ocrmypdf/OCRmyPDF#1236]
### Describe the proposed feature

Hi there. First off, thanks for making this- it is a neat software that I'm sure is handy to many people. Unfortunately, it does not work for my use case. My professor scanned a textbook then I used your software to convert the PDF to an OCR ODF that I can highlight the text within and use my "Read Aloud" browser extension to read the text to me. Unfortunately, while it worked for the first page, the second page would only read aloud one word (pause) another word (pause) etc. It was much slower. 

![DOES_NOT_WORK](https://github.com/ocrmypdf/OCRmyPDF/assets/20747205/ee0bcd4d-1a7d-4b19-8733-e34d6a2ba2eb)

I then tried to copy/paste the page into a different text-to-speech website:
https://text-speech.net/

And it copied each word onto its own line:
![DOES_NOT_WORK2](https://github.com/ocrmypdf/OCRmyPDF/assets/20747205/8157de02-1a31-4e8f-b41c-04ac56a0b851)

While I probably could copy/paste the output into notepad++ and use some regex command to remove new lines and replace with spaces- that is beginning to be more time and hand intensive than I had initially hoped by using this software. 

Best regards,
Tom

**Comment by jbarlow83** [comment]
The text that appears in the clipboard is ultimately the responsibility of the PDF viewer -- the text cannot be specified exactly in the PDF, and is a matter of heuristic interpretation.

You may get better results on the latest version of ocrmypdf using the new hocr renderer (`--output hocr`) and also deskewing (`--deskew`) since there's a possibility your PDF viewer is interpreted each skewed line as a new line break.

Before we go further, which PDF viewer is that?

**Comment by PiggiesGoSqueal** [comment]
> The text that appears in the clipboard is ultimately the responsibility of the PDF viewer -- the text cannot be specified exactly in the PDF, and is a matter of heuristic interpretation.
> 
> You may get better results on the latest version of ocrmypdf using the new hocr renderer (`--output hocr`) and also deskewing (`--deskew`) since there's a possibility your PDF viewer is interpreted each skewed line as a new line break.
> 
> Before we go further, which PDF viewer is that?

The Firefox read aloud browser extension requires uploading a PDF to it in order to read aloud the PDF. That is what is shown in the image. I ended up dropping the class of this initial pdf was from. So I probably won't use this software. but thank you for the reply.
