### ISSUE TITLE
Doc suggestion: also great for just removing the text layer!

### ISSUE THREAD

**Issue by hmijail** [ocrmypdf/OCRmyPDF#1237]
### Describe the proposed feature

I just found that by using `--force-ocr --tesseract-timeout 0` the PDF is rendered as image-only, removing any text layer, and no new text is added, which is great for some cases and a bit of a blind spot in other tools. So adding a line about this in the cookbok might be useful.

My use cases: 
* some PDFs are too weird for Tesseract, but macOS' LiveText somehow does a good job with them. However LiveText won't activate if there's a text layer in the PDF. Hence, removing the text layer allows workflows through LiveText.
* There was a time where one could print a PDF as an image through a "virtual PDF printer" to generate purely image-based PDFs, without text layers. As of macOS 14 I couldn't find a way to do that anymore from free GUI tools.

**Comment by jbarlow83** [comment]
I mean, why not? Done for next release.
