### ISSUE TITLE
[Documentation]: Upgrade via pip after system install needs a different command

### ISSUE THREAD

**Issue by dajare** [ocrmypdf/OCRmyPDF#1249]
### Describe the proposed feature

I have just installed `ocrmypdf` on an Ubuntu 22.04 system, but it needed a slightly different approach from the docs. The currently available "platform" version is `13.4.0` (via `apt`); but the current ocrmypdf version is `16.0.4`.

The [docs say][1] that **if** the platform's version is behind the current version, **then** install your platform version _first_ to satisfy non-python dependencies, _then_ run `pip install --user ocrmypdf` to install the latest version.

But this failed for me, with the message: 

    Requirement already satisfied: ocrmypdf in /usr/lib/python3/dist-packages (13.4.0+dfsg)

So I ran `pip install --upgrade --user ocrmypdf`, and this did the job perfectly.

Should [the documentation][2] include the `--upgrade` switch?

[2]: https://github.com/ocrmypdf/OCRmyPDF/blob/0bc350f55e49baedfaaefd70e8ffc094e5ca2f53/docs/installation.rst?plain=1#L567
[1]: https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-with-python-pip

**Comment by jbarlow83** [comment]
Fixed in next release
