### ISSUE TITLE
[Bug]:  version confusion

### ISSUE THREAD

**Issue by branko623** [ocrmypdf/OCRmyPDF#1259]
### What were you trying to do?

I see other people had this issue long ago but Im having it now. 

qpdf --version
qpdf version 9.1.1

### Where are you installing from?

Linux package manager (apt, dnf, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
OCRmyPDF requires 'qpdf' 8.0.2 or higher.  Your system appears
to have 10.3.1.  Please update this program.
```

**Comment by jbarlow83** [comment]
Unfortunately, all versions involved here are too old for anyone to support. qpdf is now 11.x and ocrmypdf is 16.x
