### ISSUE TITLE
Error: jbig2 not found on path, even though installed

### ISSUE THREAD

**Issue by anaxonda** [ocrmypdf/OCRmyPDF#1262]
### What were you trying to do?

When running ocrmypdf commands that utilize jbig2, I get an error saying `The program 'jbig2' could not be executed or was not found on your system PATH.`

For example running this command: `ocrmypdf --deskew --clean --clean-final --skip-text --optimize 3 --output-type pdf out.pdf out_force.pdf
`

- `ocrmypdf` is version 16.1.1, installed from AUR.
- jbig2 is in path, located at `/usr/bin/jbig2` and `/usr/local/bin/jbig2`

### Where are you installing from?

Linux package manager (apt, dnf, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
The program 'jbig2' could not be executed or was not found on your                                      
system PATH.  This program is recommended when using the --optimize {2,3} |                             
--jbig2-lossy arguments,                                                                                
but not required, so we will proceed.  For best results, install the program.
```

**Comment by jbarlow83** [comment]
If jbig2 was installed using AUR, please report the issue to the package maintainer
https://aur.archlinux.org/packages/ocrmypdf?all_deps=1#pkgdeps

**Comment by jrwrigh** [comment]
I have the same issue, but I'm not sure how this would be a package manager issue. If the program is in the `PATH`, then it's in the `PATH`, regardless of what OS you're running.

You can install `jbig2` via a [non-AUR package](https://archlinux.org/packages/extra/x86_64/jbigkit/). Installing it both ways ends up with the same issue.

**Comment by jrwrigh** [comment]
Found the real cause of the issue: trying to run `jbig2 --version` results in:
```
❯ jbig2 --version
jbig2: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

So you're right that it's an upstream error. It'd be _nice_ if `ocrmypdf` could catch and report those errors (just check for a non-zero exit code) and then report the error. Which is looks the code _should_ be catching and reporting that kind of error:
https://github.com/ocrmypdf/OCRmyPDF/blob/067f429ddee0796027ed1a4bdc41cfed009572f4/src/ocrmypdf/subprocess/__init__.py#L173-L176
but for some reason it's not...

**Comment by jbarlow83** [comment]
It was catching that error but in the case of a version check failing we translate that to "program not available". I made it log the exception.
