### ISSUE TITLE
[Bug]: dpi-problem with rasterizing text

### ISSUE THREAD

**Issue by JoKalliauer** [ocrmypdf/OCRmyPDF#1264]
### Describe the bug

Input is badly rasterized

## Comparision ##
|Input|Output|
|----|----|
|[RGB.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419492/RGB.pdf)|[RGB_ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419493/RGB_ocr.pdf)|
|![grafik](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/4b112bc1-a34a-446c-b101-dd7a1cd41136)|![grafik](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/ae8abbc1-e101-4fef-a5d5-3b165a80ff67)|

## Error message ##
`page already has text! - rasterizing text and running OCR anyway` ` _pipeline.py:305`

`Weight average image DPI is 9.4, max DPI is 17.6. The discrepancy may indicate a high detail region on this page, but could also indicate a problem with the input PDF file. Page image will be rendered at 400.0 DPI.` `_pipeline.py:464`

### Steps to reproduce

1. `wget https://github.com/ocrmypdf/OCRmyPDF/files/14419492/RGB.pdf`
2. `ocrmypdf  --force-ocr  RGB.pdf RGB_ocr.pdf`
3. Open Page 5 of RGB_ocr.pdf

## Input ##
[RGB.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419492/RGB.pdf)
![grafik](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/8e20e72e-fbac-4381-8e37-c170a836723c)

## Output ##
[RGB_ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419493/RGB_ocr.pdf)
![grafik](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/ae8abbc1-e101-4fef-a5d5-3b165a80ff67)

## Source ## 
Website: https://www.ztakademie.at/zt-kurs/
Link: [https://www.ztakademie.at/seminare/anlage?c=DHGCwVZcAXVrPWr&id=11880](https://www.ztakademie.at/seminare/anlage?c=DHGCwVZcAXVrPWr&id=11880)

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

15.4.2

### Relevant log output

```plain text
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 8/8 0:00:00
Start processing 8 pages concurrently                                                                          ocr.py:98    1 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    2 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    2 Weight average image DPI is 10.4, max DPI is 19.2. The discrepancy may indicate a high detail     _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    3 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    4 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    3 Weight average image DPI is 10.6, max DPI is 18.6. The discrepancy may indicate a high detail     _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    4 Weight average image DPI is 9.6, max DPI is 18.6. The discrepancy may indicate a high detail      _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    5 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    6 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    5 Weight average image DPI is 9.4, max DPI is 17.6. The discrepancy may indicate a high detail      _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    7 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    8 page already has text! - rasterizing text and running OCR anyway                                  _pipeline.py:305    7 Weight average image DPI is 10.2, max DPI is 22.9. The discrepancy may indicate a high detail     _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    8 Weight average image DPI is 10.9, max DPI is 22.9. The discrepancy may indicate a high detail     _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
    6 Weight average image DPI is 11.7, max DPI is 22.9. The discrepancy may indicate a high detail     _pipeline.py:464region on this page, but could also indicate a problem with the input PDF file. Page image will be
rendered at 400.0 DPI.
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 8/8 0:00:00
Postprocessing...                                                                                             ocr.py:147Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 -:--:--
Image optimization ratio: 1.03 savings: 3.4%                                                            _pipeline.py:904Total file size ratio: 0.13 savings: -660.7%                                                            _pipeline.py:907Output file is a PDF/A-2B (as expected)                                                                   _common.py:441/home/jkalliau/.local/lib/python3.10/site-packages/pikepdf/_methods.py:495: UserWarning: pikepdf is      warnings.py:109missing some specialized decoders (probably JBIG2) so not all stream contents can be tested.
  self._decode_all_streams_and_discard()

The output file size is 7.61× larger than the input file.                                             _validation.py:375Possible reasons for this include:
--force-ocr was issued, causing transcoding.
PDF/A conversion was enabled. (Try `--output-type pdf`.)
```

**Comment by jbarlow83** [comment]
Ghostscript pngmonod fixes this file but need to review impact on a wider set of files.

**Comment by JoKalliauer** [comment]
The problem is imho that ocrmypdf exports pdf with rendered pages (which are used for ocr), instead of the original images.

The Original PDF-File contained 3079 images (1jpg  and 3078png), the output contains only 8 images (1jpg and 7png).

|Input|Output|
|----|----|
|[RGB.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419492/RGB.pdf)|[RGB_ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14419493/RGB_ocr.pdf)|
|[InputImages.zip](https://github.com/ocrmypdf/OCRmyPDF/files/14720368/InputImages.zip)|[OutputImages.zip](https://github.com/ocrmypdf/OCRmyPDF/files/14720375/OutputImages.zip)|
|![5-24](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/248d8efa-b0ca-4a95-9c6c-f3a53834a5d9)![5-26](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/34e2c256-e432-4dcf-b429-435dcbe251b2)![5-28](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/1022cfa1-712e-4215-bbf2-8785f3e11268)![5-32](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/e120953c-bdb9-4bab-9a45-189345660fee)![5-34](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/c962a8a5-c4ad-44b8-ab51-93ca3cce3eaf)![5-36](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/389552ef-04c9-42fd-86f9-12c31d20c3b7)      ![5-38](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/ecdf344d-c757-4198-96d8-0226beea1ba6)![5-40](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/e0e0c26c-6a95-4116-8e4f-742dc6bf1248)![5-42](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/4aaa04a5-21c1-48e8-9cb9-df4caa909bd3)|![5-1](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/578474ec-9c45-4d26-a6a4-caabe4877cd7)


1) Can I force ocrmypdf to output the "original" pngs (no visible difference), instead of the rendered pages?


2) Can you describe how I could use/test Ghostscipt's pngmonod ?

3) Do I understand it correctly:
pngmonod renders in the whole page (in this case containing several 8bit-grayscale-png) to a single 1bit-monochrome-png for OCR.

4) Can I change the minimum dpi (e.g. ≥96dpi)?

**Comment by jbarlow83** [comment]
To test, in ocrmypdf/_pipeline.py, manually changed the string 'pngmono' to 'pngmonod'. 
Both pngmono and pngmonod to the same thing, but use a different strategy for dithering grayscale.

**Comment by JoKalliauer** [comment]
> To test, in ocrmypdf/_pipeline.py, manually changed the string 'pngmono' to 'pngmonod'. Both pngmono and pngmonod to the same thing, but use a different strategy for dithering grayscale.

pngmonod improves the dithering, however the output-PDF still contains a rendered page instead of original PNGs

|Original PNG|PNG with transformation|pngmono|pngmonod|
|----|----|----|----|
|167x73|167x73|112x50|112x50|
|![5-36_invert](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/6783303a-b89e-4658-91b0-ee71887e7ecb)|![5-36_gray](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/87d030ec-46b8-4700-a115-920f6bc01f55)|![5-1_pngmono_trim](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/06344490-a698-43ea-b037-0663633a00ef)|![5-1_pngmonod_trimp](https://github.com/ocrmypdf/OCRmyPDF/assets/15687581/945e39ae-ff50-45d6-bbfb-634b56c42e24)|

pngmonod clearly improves dithering of the rendered page, however I would like to disable rendering the page at all.

The aim of this bug-report was to keep the original view (i.e. lossless) of the pdf. pngmonod improves the output, but also alters the visible Output. Maybe my request is out-of-scope:

**Is it possible to not alter the visable output of the pdf at all?**

**Comment by JoKalliauer** [comment]
@jbarlow83 : Using `--redo-ocr` instead of `--force-ocr` solved the problem.

Reading https://ocrmypdf.readthedocs.io/en/latest/advanced.html helped.
