### ISSUE TITLE
[Bug]: Missing support for certain unicode characters

### ISSUE THREAD

**Issue by vera-bernhard** [ocrmypdf/OCRmyPDF#1272]
### Describe the bug

I'm currently using `HocrTransform` and `.to_pdf` to create a searchable PDF form HOCR files created by our own custom ocr model. And it seems that there is missing support for certain Unicode characters.

For example the character ſ (U+017F, LATIN SMALL LETTER LONG S) in our HOCR is converted to an s (U+0073, LATIN SMALL LETTER S) in the PDF.

Here the line in our HOCr file:
`<span class="ocrx_word" id="word_1_1" title="bbox 124 414 300 451">Bauernſtube</span>`
Here the word (with the other s) from the pdf:
Bauernstube

Im using ocrmypdf==16.1.1 with Python3.10 in the following way:
```python
from ocrmypdf.hocrtransform import HocrTransform

hocr = HocrTransform(
        hocr_filename=hocr_file,
        dpi=DPI
    )
hocr.to_pdf(
        out_filename=pdf_file,
        image_filename=img_file,
    )
```
I have specified utf-8 twice in my hocr file:
```xml
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="utf-8" lang="utf-8">
	<head>
		<title />
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
```
What can I do to get the correct characters in the searchable PDF?

### Steps to reproduce

```plain text
1. Run 

from ocrmypdf.hocrtransform import HocrTransform

hocr = HocrTransform(
        hocr_filename=hocr_file,
        dpi=DPI
    )
hocr.to_pdf(
        out_filename=pdf_file,
        image_filename=img_file,
    )

2. Open pdf_file and compare characters to hocr file.
```

### Files

![screenshot_hocr](https://github.com/ocrmypdf/OCRmyPDF/assets/38719534/fab4cb15-cb17-4d27-8c2c-0a77931d85f3)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

16.1.1

### Relevant log output

pikepdf.Matrix(0.24, 0, 0, -0.24, 0, 519.84)
pikepdf.Matrix(1, 0, 0, 1, 552, 210)
...

**Comment by vera-bernhard** [comment]
ſ is actually not a ligature, rather a different realization of s (depending on the position in the word) which was common in Gothic script. I guess for a general context, the normalization to s makes sense but in my specific linguistic setting I would like to differentiate them.  According to what rules/resources are characters normalized in ocrmypdf?

**Comment by jbarlow83** [comment]
The rules are simply that the string is normalized to NFKC.
https://docs.python.org/3/library/unicodedata.html
Do you know of a normalization more suitable for German that would achieve the same objectives?

**Comment by vera-bernhard** [comment]
I see. After reconsideration, I also think the current normalization is the best option. Thanks for reaching out though.
