### ISSUE TITLE
Recommended settings for dealing with text superimposed on clipart?

### ISSUE THREAD

**Issue by MBYlt** [ocrmypdf/OCRmyPDF#1274]
OCRmyPDF is such an amazing tool, it does a great job of tying together tesseract and unpaper. Thank you for putting all the time and energy into it, it really shows!

I do have problems, though, when text I'm trying to OCR has clipart in the background. Oftentimes I find that tesseract just gives up.

I've attached a sample .PDF where a simple run of OCRmyPDF will result in tesseract just nope-ing out as soon as it sees the background images.

I know how I'd approach this in an image editor (contrast all the way up, raise brightness until the gray images vanish), but trying to translate that to command line arguments for unpaper is a real headtrip, and neither `--unpaper-args '--grayfilter-threshold 0.15'` nor `--unpaper-args '--grayfilter-threshold 0.95' `seem to make any difference in the end result, which means either `--grayfilter` doesn't work the way I think it works, or I'm formatting things wrong (my full command is `ocrmypdf --clean --pdf-renderer hocr --pdfa-image-compression lossless --unpaper-args '--grayfilter-threshold 0.15' one.pdf two.pdf`)

So does anyone have any recommended  `--unpaper-args` that would result in a better-OCR'd .PDF? Doesn't even have to be 100%, but I'd at least like to see tesseract *attempt* to OCR some of the superimposed text.

[monkeywrench.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14580047/monkeywrench.pdf)

**Comment by jbarlow83** [comment]
It works for me using
`ocrmypdf  --tesseract-thresholding sauvola ...`

**Comment by YutMarma** [comment]
> It works for me using `ocrmypdf --tesseract-thresholding sauvola ...`

Here's another (real-world this time) example - not quite the same, but it relates to the general question I have of useful `unpaper` args (and tesseract .cfg lines) to try when things go higgledy-piggledy:

[test.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14609343/test.pdf)


After `ocrmypdf --clean --tesseract-thresholding sauvola test.pdf output.pdf` I get only a few lines of text OCR'd. Based on what actually gets OCR'd, it looks like tesseract is getting thrown off by the script font ("My own journey") - all text up to that point is OCR'd, and the text on the same horizontal row is OCR'd, but after that it's just "nope".

Also, I really appreciate your time here. I get that you probably have about a gazillion other things to be doing, and this is possibly veering off into tesseract/unpaper support, so I'm not expecting a huge list of precise values that you painstakingly worked out through trial and error. Just the first few args you'd try, in your experience working with OCR, is fine. Point me at a fishing pole and maybe suggest a good lake, no need for a seven-course fish dinner!

I also get that this is an Issue tracker and, ergo, meant more for "bugs" than "user help", so again, if there's a better place to be asking this, let me know. :)
