### ISSUE TITLE
Allow resuming OCR after DecompressionBombError

### ISSUE THREAD

**Issue by user1823** [ocrmypdf/OCRmyPDF#1279]
### Describe the proposed feature

I was trying to OCR a large scanned PDF (1000+ pages, 300+ MB).

It was already OCRed. So, I used

```py
ocrmypdf --redo-ocr --output-type pdf input.pdf output.pdf
```

First, it took OCRmyPDF several minutes to scan the PDF. I don't know why it takes so long and what it actually does when scanning the PDF.

Then, it took over 30 minutes to reach up to page 500 and then suddenly the DecompressionBombError appeared and I lost all my progress.

I suggest adding the ability to resume OCR after such errors.

Version: 16.1.1
Installed using HomeBrew on M1 MacBook Air

As a side note, I wanted to mention that I had earlier OCRed the PDF using [pdf24 software](https://www.pdf24.org/en/) on Windows. It also uses Tesseract as the OCR engine. This software did the OCR without any issues in about 1 hour on my Windows laptop with a slower processor (Intel i3).

So, probably, OCRmyPDF also needs some optimizations for faster processing and/or dealing with the errors?

You may want to know the reason for re-performing the OCR. It was because the pdf24 app didn't place the OCR exactly below the text. It was quite close, but not exactly matching. I wanted to see if OCRmyPDF could place the text at a more accurate position.

**Comment by jbarlow83** [comment]
I understand it is frustrating when this happens, but this error is designed to protect users against malicious files so it does need to be there. There is a command line argument to adjust the limit.

The current design does not allow for execution to resume from an error of this type.

**Comment by user1823** [comment]
> The current design does not allow for execution to resume from an error of this type

Ok, if resuming is not possible, is it possible to get partially OCRed file?

I would prefer to split the file, run OCR on the remaining part and then join them together rather than rerunning the OCR on the complete file.

**Comment by jbarlow83** [comment]
You can use a program like qpdf to split PDFs and recombine them.
