### ISSUE TITLE
max_workers must be greater than 0

### ISSUE THREAD

**Issue by nope999** [ocrmypdf/OCRmyPDF#1283]
### What were you trying to do?

Hi, I am running ocrmypdf 16.1.2 on a Windows 64-bit with Tesseract 5.2.

When running
`ocrmypdf.ocr(i'nput_file.pdf', 'output_file.pdf', redo_ocr=True,  language='spa', progress_bar=True)`

I get error  File ~\.conda\envs\ocr\lib\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py:179 in validate
    tess_threads = clamp(options.jobs // len(pdfinfo), 1, 3)

Then I explicitly run 

```
import os
if not os.environ.get('OMP_THREAD_LIMIT', '').isnumeric():
    os.environ['OMP_THREAD_LIMIT'] = str(3)

```
Which then triggers this error 

  File ~\.conda\envs\ocr\lib\site-packages\ocrmypdf\builtin_plugins\concurrency.py:135 in _execute
    executor_class(

  File ~\.conda\envs\ocr\lib\concurrent\futures\thread.py:145 in __init__
    raise ValueError("max_workers must be greater than 0")  

### Where are you installing from?

pip

### What operating system are you working on?

Windows

**Comment by nope999** [comment]
I just realized that this is happening with certains pdfs, in other cases it's running fine.

**Comment by jbarlow83** [comment]
I'll reopen the issue when a test file and steps to reproduce are  provided.
