### ISSUE TITLE
[Feature]: Could watcher.py be enhanced to support the conversion of single or multi TIF and JPG files to PDF?

### ISSUE THREAD

**Issue by EvilQoo** [ocrmypdf/OCRmyPDF#1284]
### Describe the proposed feature

Could watcher.py be enhanced to support the conversion of single or multi TIF and JPG files to PDF?

**Comment by jbarlow83** [comment]
Using `python watcher.py --patterns '*.pdf,*.PDF,*.jpg,*.JPG'` would include and convert JPG.

I realized there is an issue in that watcher.py will not fix the filename extension for non-PDF. This will be fixed.

Converting TIFF to PDF is something I'm reluctant to set up - TIFF can contain multiple images, but it's not always clear whether the images represent pages, animation frames, different level of detail of the same image, or something else; and then the TIFF format itself is rather complex. You're best off using TIFF software to inspect incoming TIFFs. You could try img2pdf as well.
