### ISSUE TITLE
[Bug]: watcher.py requires the "ARCHIVE" folder to be assigned, even if the option is disabled

### ISSUE THREAD

**Issue by clodobox** [ocrmypdf/OCRmyPDF#1294]
It is currently indispensable to assign the OCR_ARCHIVE_DIRECTORY folder even if the OCR_ON_SUCCESS_ARCHIVE option is disabled.

This bug poses a problem for compatibility between versions.

**Comment by jbarlow83** [comment]
In the next major release (whenever it occurs), OCR_ON_SUCCESS_ARCHIVE will be removed. If OCR_ARCHIVE_DIRECTORY / --archive-dir is set issued, then archiving will occur.
