### ISSUE TITLE
[Feature]: JPEG XL support

### ISSUE THREAD

**Issue by Lyapsus** [ocrmypdf/OCRmyPDF#1301]
### Describe the proposed feature

https://en.wikipedia.org/wiki/JPEG_XL

**Comment by jbarlow83** [comment]
Until the PDF spec officially adds support for one of the many post-JPEG formats, there's not much one can do.

If you're looking to add support for OCRmyPDF to convert input JPEG X* to PDF, that should be instead be added to the img2pdf project, which OCRmyPDF uses when it needs to turn any image into a PDF. I recommended adding it to that project, and OCRmyPDF will benefit indirectly.

https://pypi.org/project/img2pdf/

**Comment by Lyapsus** [comment]
Fair point, sorry for half-assed research

**Comment by Lyapsus** [comment]
Get ready for a little rabbit hole: https://gitlab.mister-muffin.de/josch/img2pdf/issues/188
