### ISSUE TITLE
not user friendly 

### ISSUE THREAD

**Issue by abood-az** [ocrmypdf/OCRmyPDF#1302]
### Describe the bug

i cant tell where to put needed pdf files or how to set the path to them, and also it cant find 'tesseract

### Steps to reproduce

```plain text
1. Run ocrmypdf -v1 ...arguments... input.pdf output.pdf
2. Open output.pdf
3. ...
```

**Comment by jbarlow83** [comment]
[Have a look at the installation procedure for your platform](https://ocrmypdf.readthedocs.io/en/latest/installation.html)
