### ISSUE TITLE
[Bug]: conda installation

### ISSUE THREAD

**Issue by kevinkaw** [ocrmypdf/OCRmyPDF#1304]
### What were you trying to do?

I am trying to install OCRmyPDF in my chromebook with anaconda package.
conda version 24.1.2 and python 3.11.7.

From the documentation, I run the following code in my conda base environment `conda install ocrmypdf` and it gives me a `package not found` error.

From the conda page, last updated 1 year ago [https://anaconda.org/conda-forge/ocrmypdf](url).
Running `conda install conda-forge::ocrmypdf` or `conda install -c conda-forge ocrmypdf` gives a `solving environment: killed` error.

### Where are you installing from?

Conda

### What operating system are you working on?

Linux

### Relevant log output

```plain text
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: | Killed
```

**Comment by jbarlow83** [comment]
Please report this to conda -- they're a downstream packager of ocrmypdf, and they're the ones who will understand your issue and will be able to support you. Or try using a different installation method.

**Comment by kevinkaw** [comment]
Just did, it took me a while to find how to but I will post the instructions here for the benefit of future readers:
1. Go to [https://conda-forge.org/packages/?](url) and search "ocrmypdf". It does not work if you go directly to the conda-forge package page
2. open the "feedstock" github link
3. post issue there

here is the issue I posted: [https://github.com/conda-forge/ocrmypdf-feedstock/issues/52](url)
