### ISSUE TITLE
[Bug]: File size increased

### ISSUE THREAD

**Issue by user1823** [ocrmypdf/OCRmyPDF#1306]
### Describe the bug

When OCRing the following file, the file size increases. Strictly speaking, this is a GhostScript issue because rewriting the original PDF with gs produces a similar increase in file size.

However, I am reporting the issue here because ocrmypdf is forcing the PDF to be re-written by gs even though it is inefficient in dealing with this particular file.

### Steps to reproduce

```plain text
1. Run ocrmypdf --output-type pdf in.pdf ocr.pdf
2. See ocr.pdf (175 KB) is larger than in.pdf (159 KB).
3. Run gswin64.exe -sDEVICE=pdfwrite -dBATCH -dNOPAUSE -sOutputFile=out.pdf in.pdf
4. See out.pdf (173 KB) is larger than in.pdf (159 KB) but almost the same size as ocr.pdf (175 KB).
```

### Files

Original PDF: [in.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/15213276/in.pdf)
OCRed PDF: [ocr.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/15213277/ocr.pdf)
Original PDF rewritten using GS: [out.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/15213278/out.pdf)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

16.2.0

**Comment by jbarlow83** [comment]
The increases in file size are modest and necessary because we need to include the recognized text and resources to support that; in the case of PDF/A we also have to include a copy of sRGB.icc because the PDF/A spec says so.

ocrmypdf never promises that the output file will be smaller. In the typical case - especially without optimization - it needs to increase the file size by about 10-20 KB + 5 KB/page (not measured, off the top of my head).

**Comment by user1823** [comment]
> because we need to include the recognized text and resources to support that

But, in this case, the maximum contribution to the increase in file size is not by the recognized text but is due to rewriting of the PDF using GhostScript.

> The increases in file size are modest

I may seem modest in this sample file but the above sample is only one page from a large file (150 MB) which increased to about 175 MB due to the same issue.

> ocrmypdf never promises that the output file will be smaller. 

Yes, I understand. But here, it is being inefficient by rewriting the PDF using GhostScript because GhostScript produces a larger file size for this particular PDF.

**Comment by user1823** [comment]
You can have a look at this quote to better understand what I am talking about:

> The first thing to understand is that there is no guarantee that processing a PDF file with Ghostscript and the pdfwrite output device will produce a smaller file. In fact, it may even produce a larger file! As you’ll recall from the introduction, the actual operations written to the PDF file may not be the same as the original ones and, in fact, as the example showed, may be more verbose and, therefore larger.
> 
> In addition, at the time of writing, the pdfwrite device does not support either XrefStm (compressed xref tables) or ObjStm (a means of compressing other kinds of objects) in the PDF files it creates. If the original file did use those and used them effectively, it may well be smaller than the pdfwrite output.

Source: https://www.ghostscript.com/blog/optimizing-pdfs.html

The provided sample file is one example of the files that get larger in size when re-writtten with GS.

My proposal is to skip re-writing the file (if possible) in situations where re-writing it increases the file size.

**Comment by jbarlow83** [comment]
ocrmypdf produces PDF/A by default, not PDF, because people need it and require it. It's worked this way for almost 10 years, since v1.0 before I was involved. That behavior is not changing.

We perform all of the lossless optimizations discussed in that quote after Ghostscript runs. You can use the various optimization settings if file size is important.

**Comment by user1823** [comment]
> ocrmypdf produces PDF/A by default, not PDF

My command includes `--output-type pdf`. So, conversion to PDF/A is not the issue actually. 

> We perform all of the lossless optimizations discussed in that quote after Ghostscript runs. 

Is it possible to skip running GS on the file? Re-writing the file using GhostScript seems to be the main issue here. 

If ocrmypdf performs the optimizations mentioned in that quote, the following part of that quote may be more relevant:

> the actual operations written to the PDF file may not be the same as the original ones and, in fact, as the example showed, may be more verbose and, therefore larger.

The main question I want to get answered is **whether it is possible to skip re-writing the file with GS**.

**Comment by jbarlow83** [comment]
When you use `--output-type pdf`, the PDF does not pass through Ghostscript.
Ghostscript does get used to generate page images, but in the syntax above, those images would be discarded after OCR.

**Comment by user1823** [comment]
Thanks for the answers.

I now think that the increase in file size is actually due to the OCRed text, rather than inefficient conversion. To confirm this, I ran the same command with an added parameter `--tesseract-timeout=0`. This time, the file size decreased from 159 KB to 158 KB. So, just running the file through ocrmypdf is not causing the increased file size.

Sorry for the inconvenience.
