### ISSUE TITLE
Pushed docker image is always Ubuntu instead of alpine

### ISSUE THREAD

**Issue by vihtap** [ocrmypdf/OCRmyPDF#1317]
Hi,

I would like to point you only that the pushed docker image even if tagged as "alpine", contains the Ubuntu base image, not the alpine. It seems that the Dockerfile.alpine is not used at all or the tag on the pushed image is wrong.

https://hub.docker.com/layers/jbarlow83/ocrmypdf/alpine-arm/images/sha256-3ec1aa03cfa1aa8995db15ed3db4445bedec62ebe533e79d5f176ddda0b5135a?context=explore

![Screenshot 2024-05-22 112904](https://github.com/ocrmypdf/OCRmyPDF/assets/6613437/633415de-ea4d-41b1-97b6-7618c38902f0)

**Comment by jbarlow83** [comment]
Fixed in commit 0774bc7f
