### ISSUE TITLE
[Bug]: multiple spaces not supported for delimitation of bbox parameters

### ISSUE THREAD

**Issue by Tehgg** [ocrmypdf/OCRmyPDF#1322]
### Describe the bug

In the file `src/ocrmypdf/hocrtransform/_hocr.py`, line 67, the pattern for bbox is too restrictive compared to the spec of hOCR (see [this line](http://kba.github.io/hocr-spec/1.2/#grammardef-property-value)). I tried to combine ocrmypdf and doctr, but the hocr output of doctr contains several spaces to separate the parameters of bbox, and it wasn't working. It fails silently. (This doesn't seem to be intentional in the code of doctr though.)

So I think that
```python
box_pattern = re.compile(r'bbox (\d+) (\d+) (\d+) (\d+)')
```
should be changed to
```python
box_pattern = re.compile(r'bbox +(\d+) +(\d+) +(\d+) +(\d+)')
```

Maybe there are similar small problems.

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

16.3.1

**Comment by jbarlow83** [comment]
I will change this to be accepted. Note that the hOCR spec does not seem to actually permit multiple spaces or whitespace other than U+0020 between the markers but it seems harmless to allow.
