### ISSUE TITLE
[Bug]: --tesseract-pagesegmode is not sufficiently documented

### ISSUE THREAD

**Issue by thomas2net** [ocrmypdf/OCRmyPDF#1325]
### What were you trying to do?

Thanks for your latest ocrmypdf Documentation Release 16.3.2.dev9+g0774bc7 of June 1st, 2024.
I'm trying to specify bounding boxes for 2-column OCR. 
I understand how to do that for a single tiff page using: 
tesseract --psm 6 file.tif filebasename pdf
after specifying bounding boxes in a .uzn file having the same basename, e.g., file.uzn.
However, how does one do that using ocrmypdf? 
Can you please provide an example in the documentation?
Thank you very much.

### Where are you installing/running from?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

15.2.0+dfsg1

### What operating system are you working on?

Linux

### Operating system details and version

Ubuntu 24.04 LTS Linux 6.8.0-31-generic

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF

**Comment by jbarlow83** [comment]
As a requested I expanded the documentation on this item which was not mentioned on readthedocs at all.

A few specific details:

There is currently no way to pass .uzn files to ocrmypdf.

One major problem is that .uzn are in pixel coordinates, and PDF have their own coordinate system based on pages, which is rasterized to images at variable DPI. So a .uzn file would not be using the same coordinate as a PDF - some other solution would be need for zonal OCR.

ocrmypdf would need some sort of zone description in page coordinates, which it would translate to pixel coordinates and pass to tesseract, if this were implemented. I can't see this happening anytime soon, unfortunately.
