### ISSUE TITLE
[Bug]: ocrmypdf (16.3.1) and Tesseract 5.4.1

### ISSUE THREAD

**Issue by Johnnie390** [ocrmypdf/OCRmyPDF#1336]
### What were you trying to do?

Hello all,
please title, are there compatability issues here or do I have to wait for the next release, or minor version change of ocrmypdf?

Regards

J.

### Where are you installing/running from?

source build

### OCRmyPDF version

16.3.1

### What operating system are you working on?

Linux

### Operating system details and version

Debian kernel 6.9.4

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF

### Relevant log output

```plain text
No logs as yet, just wondering about compatability/dependency issues.
It would seem, even though I have compiled tesseract 5.4.1, when I do an apt install of ocrmypdf, it pulls in tesseract 5.3.x which is obviously not what I want..
The background is I have issues in Paperless-ngx.
"Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 568, in run

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 391, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 147, in consume_file

    msg = plugin.run()"
```

**Comment by jbarlow83** [comment]
I am waiting for Tesseract 5.4.1 to be more widely packaged.

You will need to ensure that the user account that runs paperless has its PATH set to give priority to tesseract 5.4.1. When you run `tesseract --version` from that user account you need the response to be 5.4.1.

If paperless is in some kind of container (Docker?) then you need to install tesseract inside that container somehow.

When you compile and install an application it typically is installed in /usr/local/bin, and while your main account may have this on PATH, typically daemon user accounts do not.

**Comment by Johnnie390** [comment]
Thanks for thje information. I will report back.

J.

**Comment by Johnnie390** [comment]
Paperless-ngx is indeed running in a docker container - that is the way it is packaged. I would prefer bare metal, but things are as they are...
I  will have to do some head-scratching here. I will report back.
Again, thanks for the information.

J.
