### ISSUE TITLE
[Feature]: Enable execution on GPU

### ISSUE THREAD

**Issue by danielfcastro** [ocrmypdf/OCRmyPDF#1343]
### Describe the proposed feature

When we run the conversion the process happens on CPU.  If we have a new feature to enable GPU processing than a new parameter would allow this without any breaking changes.

**Comment by shivams** [comment]
Did you checkout the OCRmyPDF's version which utilizes EasyOCR: https://github.com/ocrmypdf/OCRmyPDF-EasyOCR? It utilizes GPU.
