### ISSUE TITLE
[Bug]: problem with tif "DPI is not credible". Estimate dpi

### ISSUE THREAD

**Issue by drnicolas** [ocrmypdf/OCRmyPDF#1348]
### Describe the bug

crmypdf.exceptions.DpiError: Input file is an image, but the resolution (DPI) is not credible.  Estimate the resolution at which the image was scanned and specify it using --image-dpi.

During handling of the above exception, another exception occurred:

Traceback (most recent call last

### Steps to reproduce

```plain text
What can I do?
Sorry, I cannot post the file itself as it contains patients data
```

### OCRmyPDF version

15.x

**Comment by jbarlow83** [comment]
As the message says you need to specify the resolution. Guess 300 if unsure.

**Comment by drnicolas** [comment]
Typically I see this problem with documents which come from iphones as Mail-Attachments.
With faxes and scanned PDF normally it works fine.
What happens if I generally add this dpi parameter as you suggest?
Can it distort or do other crazy things with the documents?


Von: jbarlow83 ***@***.***>
Gesendet: Donnerstag, 4. Juli 2024 19:52
An: ocrmypdf/OCRmyPDF ***@***.***>
Cc: N. Nickisch (User) ***@***.***>; Author ***@***.***>
Betreff: Re: [ocrmypdf/OCRmyPDF] [Bug]: problem with tif "DPI is not credible". Estimate dpi (Issue #1348)


As the message says you need to specify the resolution. Guess 300 if unsure.

**Comment by jbarlow83** [comment]
The paper size will be incorrect if DPI is set incorrectly. If the paper size is wrong, PDF viewers may open the document at an unusual zoom.
