### ISSUE TITLE
[Bug]: files signed with a-trust are not recognised as digitally signed and hence processed

### ISSUE THREAD

**Issue by ferdiga** [ocrmypdf/OCRmyPDF#1352]
### Describe the bug

digital signed are processed by ocrmypdf, hence the signature becomes invalid.

on AMZON ubuntu pro
Linux 6.5.0-1022-aws x86_64 

### Steps to reproduce

```plain text
1. signed  files with https://www.a-trust.at/de/
2. used misc/ocr_batch.py sample file
3. files are processed - but shouldn't be according to ocrmypdf manual. 

signed scanned example files below
```

### Files

[test-scan-signed-private.pdf](https://github.com/user-attachments/files/16150740/test-scan-signed-private.pdf)
[test-scan-signed-public.pdf](https://github.com/user-attachments/files/16150741/test-scan-signed-public.pdf)

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

13.4.0+dfsg

**Comment by jbarlow83** [comment]
That version is too old to support. The current version refuses to process these files as expected.
