### ISSUE TITLE
--sidecar writes text content and messages to file

### ISSUE THREAD

**Issue by gerritgriebel** [ocrmypdf/OCRmyPDF#1353]
`ocrmypdf --pages 1 --quiet --force-ocr --sidecar out.txt in.pdf --output-type=none - > /dev/null`

results in a out.txt that contains the desired output but with a not wanted  "^L[OCR skipped on page(s) 2-5]" last line, where ^L is "Control-L" or "Form Feed".

**Comment by jbarlow83** [comment]
As designed. The form feed is a page separator.

**Comment by gerritgriebel** [comment]
I think such meta information should not be issued in the same file that contains the extracted text. Users have to write code to weed out the form fees char and the message.
