### ISSUE TITLE
[Bug]: subprocess.CalledProcessError: Command '['D:\\latex\\texlive\\2020\\bin\\win32\\jbig2.EXE', '--version']' returned non-zero exit status 3.

### ISSUE THREAD

**Issue by 459737087** [ocrmypdf/OCRmyPDF#1363]
### What were you trying to do?

import ocrmypdf

input_path = "手册.pdf"
output_path = "output.pdf"

if __name__ == '__main__':  # To ensure correct behavior on Windows and macOS
    ocrmypdf.ocr(input_path, output_path, deskew=True)

### Where are you installing/running from?

Wndows package manager (chocolatey, etc.)

### OCRmyPDF version

ocrmypdf           16.4.2.dev8+g5256e74d

### What operating system are you working on?

Windows

### Operating system details and version

10

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF
- [X] This issue is not about a specific input file

### Relevant log output

```plain text
Command '['D:\\latex\\texlive\\2020\\bin\\win32\\jbig2.EXE', '--version']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "D:\Lib\site-packages\ocrmypdf\subprocess\__init__.py", line 158, in get_version
    proc = run(
           ^^^^
  File "D:\Lib\site-packages\ocrmypdf\subprocess\__init__.py", line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\latex\\texlive\\2020\\bin\\win32\\jbig2.EXE', '--version']' returned non-zero exit status 3.
```

**Comment by jbarlow83** [comment]
The version jbig2.exe provided by this latex (texlive?) software happens to have the same name, but does not seem to be compatible.
