### ISSUE TITLE
[Query]: docker watched folder environment variables, optimize how?

### ISSUE THREAD

**Issue by jaxjexjox** [ocrmypdf/OCRmyPDF#1370]
### What were you trying to do?

I can see pretty good documentation here: https://ocrmypdf.readthedocs.io/en/latest/batch.html

Clearly outlining how to leave a nice little input / output style drop system for the docker version.
I'll be damned if I can find the enviroment variables which handle optimization? 

I can see things such as 
--env OCR_DESKEW=1  which is self explanatory but I've googled extensively and I don't see the 1/2/3 levels of optimization?

### Where are you installing/running from?

Docker container

### OCRmyPDF version

16.4.3.dev4+g3a75b207.d20240731  (05/Aug/2024)

### What operating system are you working on?

Linux

### Operating system details and version

22.04

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [ ] Python version is compatible with OCRmyPDF
- [X] This issue is not about a specific input file

### Relevant log output

```plain text
N/A

Curious about documentation, googled is getting 0 results for how to define optimization modes for this active tool monitoring folders.
```

**Comment by jbarlow83** [comment]
You can use `OCR_SETTINGS_JSON`. For example use `OCR_SETTINGS_JSON='{"optimize": "3"}'` to set `--optimize 3`.

You may need to double quote or play other tricks depending on which shell you use.

**Comment by jaxjexjox** [comment]
> You can use `OCR_SETTINGS_JSON`. For example use `OCR_SETTINGS_JSON='{"optimize": "3"}'` to set `--optimize 3`.
> 
> You may need to double quote or play other tricks depending on which shell you use.

Thanks for the help, I had some real issues with it working at all, regardless of the settings, truth be told. I'm unsure if it was a permissions issue or something else.

I think I've opted to run the command manually infrequently as I can't see me needing to use it too often.
Thanks again for this, I can't recall if this was my lack of reading documentation or there was a couple of the options you mentioned being missing from the example doco? It may be worth adding.

Thank you for the hard work!
