### ISSUE TITLE
does not ocr 90° rotated texts

### ISSUE THREAD

**Issue by stfnx** [ocrmypdf/OCRmyPDF#1373]
Hi,
I have assembly drawings of pcbs that look similar to [this](https://www.protoexpress.com/wp-content/uploads/2022/03/top-layer-assembly-drawing.jpg) (Example image found on Google). Typically the text is better readable than here. But the core essence is that there are many short strings like `R123, C51, IC2, Q200` etc. Some of them are in normal rotation and some of them are rotated 90°. 

I can not get it to ocr all of them. Most (not all) texts with normal rotation are processed. None of the rotated ones.

Is there anything I could do to get this to work?

**Comment by jbarlow83** [comment]
This is a limitation of the Tesseract OCR engine - can't do anything about it at this time.
