### ISSUE TITLE
[Feature]: Result Improvement with OpenCV + Pillow Preprocessing 

### ISSUE THREAD

**Issue by vishaldwdi** [ocrmypdf/OCRmyPDF#1374]
### Describe the proposed feature

I am requesting this particular feature after I observed rate of result quality improvement by 52%.

Inclusion of OpenCV + Pillow Preprocessing prior to Tesseract OCR improves results by great margin. I got excited after personally observing it during test. I desperately need this to be included to have a good app.

**Comment by vishaldwdi** [comment]
'pip install opencv-python pillow pytesseract numpy

import cv2
import numpy as np
from PIL import Image
import pytesseract

# Set the path to the Tesseract executable (adjust if necessary)
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'  # For Windows
# For Linux or macOS, you might not need to set this path

def preprocess_image(image_path):
    # Open the image with Pillow
    pil_image = Image.open(image_path).convert('RGB')
    
    # Convert the Pillow image to an OpenCV format (numpy array)
    opencv_image = np.array(pil_image)
    
    # Convert to grayscale
    gray_image = cv2.cvtColor(opencv_image, cv2.COLOR_RGB2GRAY)
    
    # Apply thresholding (binary thresholding)
    _, thresh_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY_INV)
    
    # Apply dilation (optional, based on the image quality and text size)
    kernel = np.ones((3, 3), np.uint8)  # Adjust kernel size as needed
    dilated_image = cv2.dilate(thresh_image, kernel, iterations=1)
    
    return dilated_image

def extract_text_from_image(preprocessed_image):
    # Convert the OpenCV image (numpy array) to a Pillow image
    pil_image = Image.fromarray(preprocessed_image)
    
    # Use Tesseract to extract text
    text = pytesseract.image_to_string(pil_image)
    
    return text

def main(image_path):
    preprocessed_image = preprocess_image(image_path)
    text = extract_text_from_image(preprocessed_image)
    print("Extracted Text:")
    print(text)

if __name__ == "__main__":
    image_path = 'path_to_your_image.jpg'  # Update this path to your image
    main(image_path)

'

**Comment by vishaldwdi** [comment]
import cv2
import numpy as np
from PIL import Image
import pytesseract

# Set the path to the Tesseract executable (adjust if necessary)
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'  # For Windows
# For Linux or macOS, you might not need to set this path

def preprocess_image(image_path):
    # Open the image with Pillow
    pil_image = Image.open(image_path).convert('RGB')
    
    # Convert the Pillow image to an OpenCV format (numpy array)
    opencv_image = np.array(pil_image)
    
    # Convert to grayscale
    gray_image = cv2.cvtColor(opencv_image, cv2.COLOR_RGB2GRAY)
    
    # Apply thresholding (binary thresholding)
    _, thresh_image = cv2.threshold(gray_image, 128, 255, cv2.THRESH_BINARY_INV)
    
    # Apply dilation (optional, based on the image quality and text size)
    kernel = np.ones((3, 3), np.uint8)  # Adjust kernel size as needed
    dilated_image = cv2.dilate(thresh_image, kernel, iterations=1)
    
    return dilated_image

def extract_text_from_image(preprocessed_image):
    # Convert the OpenCV image (numpy array) to a Pillow image
    pil_image = Image.fromarray(preprocessed_image)
    
    # Use Tesseract to extract text
    text = pytesseract.image_to_string(pil_image)
    
    return text

def main(image_path):
    preprocessed_image = preprocess_image(image_path)
    text = extract_text_from_image(preprocessed_image)
    print("Extracted Text:")
    print(text)

if __name__ == "__main__":
    image_path = 'path_to_your_image.jpg'  # Update this path to your image
    main(image_path)

**Comment by jbarlow83** [comment]
Thanks for the explanation.
While you have seen accuracy improvements from these settings, that does not mean that they are fully general and will be beneficial to all users. Also, OpenCV is a fairly large and complex dependency with possible GPU dependencies, and I'm a bit reluctant to make it a hard dependency. 

What you are proposing could work as an OCRmyPDF plugin, hooking `filter_ocr_image`,  if you wanted to go that route.
