### ISSUE TITLE
[Bug]: ocrmypdf: error: unrecognized arguments: input.pdf output.pdf

### ISSUE THREAD

**Issue by KNDaniel** [ocrmypdf/OCRmyPDF#1375]
### Describe the bug

From the cmd of windows I tried:

C:\Users\danie\Desktop>ocrmypdf -2 spa AAA.pdf BBB.pdf
usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI] [--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3,none}]
                [--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]] [--title TITLE] [--author AUTHOR]
                [--subject SUBJECT] [--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c] [-i]
                [--unpaper-args UNPAPER_ARGS] [--oversample DPI] [--remove-vectors] [-f] [-s] [--redo-ocr]
                [--skip-big MPixels] [--invalidate-digital-signatures] [--pages PAGES] [--max-image-mpixels MPixels]
                [--pdf-renderer {auto,hocr,sandwich,hocrdebug}] [--rotate-pages-threshold CONFIDENCE]
                [--fast-web-view MEGABYTES] [--continue-on-soft-render-error] [--plugin PLUGINS] [-k]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM] [--tesseract-oem MODE]
                [--tesseract-thresholding METHOD] [--tesseract-timeout SECONDS] [--tesseract-non-ocr-timeout SECONDS]
                [--tesseract-downsample-large-images | --no-tesseract-downsample-large-images]
                [--tesseract-downsample-above TESSERACT_DOWNSAMPLE_ABOVE] [--user-words FILE] [--user-patterns FILE]
                [-O {0,1,2,3}] [--jpeg-quality Q] [--png-quality Q] [--jbig2-lossy] [--jbig2-threshold T]
                [--color-conversion-strategy STRATEGY] [--pdfa-image-compression {auto,jpeg,lossless}]
                input_pdf_or_image output_pdf
ocrmypdf: error: unrecognized arguments: AAA.pdf BBB.pdf

The  C:\Users\danie\Desktop is the directory where I have AAA.pdf (the pdf that I tried to OCR) and BBB.pdf is the output.pdf I want.

Is my command wrong write or I miss something, please help.

I don't speak English very well

### Steps to reproduce

```plain text
1. I run C:\Users\danie\Desktop>ocrmypdf -2 spa AAA.pdf BBB.pdf from the cmd of windows.
2. Result in the error ocrmypdf: error: unrecognized arguments: AAA.pdf BBB.pdf
```

### How did you download and install the software?

Windows package manager (chocolatey, etc.)

### OCRmyPDF version

16.4.3

### Relevant log output

```plain text
C:\Users\danie\Desktop>ocrmypdf -2 spa AAA.pdf BBB.pdf
usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI] [--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3,none}]
                [--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]] [--title TITLE] [--author AUTHOR]
                [--subject SUBJECT] [--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c] [-i]
                [--unpaper-args UNPAPER_ARGS] [--oversample DPI] [--remove-vectors] [-f] [-s] [--redo-ocr]
                [--skip-big MPixels] [--invalidate-digital-signatures] [--pages PAGES] [--max-image-mpixels MPixels]
                [--pdf-renderer {auto,hocr,sandwich,hocrdebug}] [--rotate-pages-threshold CONFIDENCE]
                [--fast-web-view MEGABYTES] [--continue-on-soft-render-error] [--plugin PLUGINS] [-k]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM] [--tesseract-oem MODE]
                [--tesseract-thresholding METHOD] [--tesseract-timeout SECONDS] [--tesseract-non-ocr-timeout SECONDS]
                [--tesseract-downsample-large-images | --no-tesseract-downsample-large-images]
                [--tesseract-downsample-above TESSERACT_DOWNSAMPLE_ABOVE] [--user-words FILE] [--user-patterns FILE]
                [-O {0,1,2,3}] [--jpeg-quality Q] [--png-quality Q] [--jbig2-lossy] [--jbig2-threshold T]
                [--color-conversion-strategy STRATEGY] [--pdfa-image-compression {auto,jpeg,lossless}]
                input_pdf_or_image output_pdf
ocrmypdf: error: unrecognized arguments: AAA.pdf BBB.pdf
```

**Comment by jbarlow83** [comment]
The ```
-2
```

Is not a valid argument.

**Comment by KNDaniel** [comment]
Thanks for support.

I tried to OCR a PDF in spa and level two lossy optimization, what should I do?
