### ISSUE TITLE
[3rdparty]: 当使用ocrmypdf输入 PDF 为中文时，结果 复制PDF 中有额外的空格

### ISSUE THREAD

**Issue by deict** [ocrmypdf/OCRmyPDF#1390]
### Simple sanity checks

- [X] This is an issue with an app that uses OCRmyPDF for OCR
- [ ] I am using a recent version of the third party app
- [ ] I will include a file that reproduces the issuse

### Describe the bug

生成的pdf![image](https://github.com/user-attachments/assets/f1d59760-606a-4597-91c9-27f2408b58df)
复制的内容‘短期负荷预测: 影响 负荷的因素 很 多,存 在 着 不确定性,首 先 需要 进行一定 的 数据清洗,
过滤 掉 一 些 数据,然 后 进行 特征 选择, 选取上 一 天 的 负荷、最 高 温度,最 低温 度 、白 天风力、
夜间 风力,对 于 时间 维度上’

### Steps to reproduce

```plain text
1. Import attached file into Paperless-ngx
2. Trigger OCR
3. Check log file
4. ...
.\ocrmypdf -l chi_sim --output-type pdf C:/Users/15179/Pictures/pp.pdf C:/Users/15179/Pictures/999.pdf
```

**Comment by jbarlow83** [comment]
No OCRmyPDF version or reproducible file - can't test.
