### ISSUE TITLE
[Feature]: Align pages to text baseline

### ISSUE THREAD

**Issue by swxxii** [ocrmypdf/OCRmyPDF#1394]
### Describe the proposed feature

This utility is great thank you! But it doesn't always rotate pages so that the text baseline is horizontal. Is it supposed to do this? If not it would be great to get this feature!

**Comment by jbarlow83** [comment]
`--deskew` does this. 

It does not always work because there is not always a single angle that will deskew a page.

**Comment by swxxii** [comment]
Actually it could just be one of my PDFs that is not behaving nicely, the others seem to be working! sorry to bother
