### ISSUE TITLE
[Feature]: support for Apple vision framework

### ISSUE THREAD

**Issue by santiagozky** [ocrmypdf/OCRmyPDF#1405]
### Describe the proposed feature

Hello,

I was playing around with some PDFs and while the results were mostly acceptable, they did have some issues.
just for curiousity I noticed that text that this software fails to detect is nicely detected by Apple's preview app with no issues. So I gave a try [this tool ](https://github.com/tddschn/apple-vision-utils) on some images and it seems to do a great work

I think supporting [Apple Vision framework](https://developer.apple.com/documentation/vision/recognizing-text-in-images) would be an interesting feature for this software.

**Comment by jbarlow83** [comment]
There's a plugin interface that could support this. I'd be happy to offer quick guidance for development as well. 

I can't see ever implementing it myself since it would only benefit a small slice of the user base.

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
