### ISSUE TITLE
Data privacy when using OCRmyPDF

### ISSUE THREAD

**Issue by etroci** [ocrmypdf/OCRmyPDF#1407]
Hello,

I would like to use the software to read PDFs containing proprietary information however I'm concerned about sending the PDFs over to tesseract or anywhere other than my local machine for that matter. 

I've read online that OCRmyPDF uses the models locally and no PDF information is sent over the internet, however I couldn't find an official source for this, and I would like to be able to verify it myself if you could direct me to that code. Apologies as I am not too familiar with the technology and am not sure where else to pose my question.

Please let me know if you can and thank you for the great work you're doing as this tool is exactly what I need if secure.

**Comment by jbarlow83** [comment]
Ocrmypdf does not send any of your data over the internet at any time. The processing is entirely local.

**Comment by jbarlow83** [comment]
If you want to verify this, you could run ocrmypdf with your wifi or network disabled, or sandbox it in some way.
