### ISSUE TITLE
[Bug]: "remove-background is temporarily not implemented" error on linux

### ISSUE THREAD

**Issue by dimyself** [ocrmypdf/OCRmyPDF#1412]
### Describe the bug

I apologize if this is mentioned somewhere... but I searched the issues and I can't tell if it is supposed to be working or not?

This is on Arch linux, AUR installed. versions - 16.4.3

I want to remove "background noise" from my scanned pdfs (page folds, light marks, bends, etc).

Is remove-background supposed to be working, or it isn't currently implemented? 

If its not currently working, is there sometrhing else I can use in ocrmypdf or a different utility / tool / command to further reduce background noise?

Thank you!

### Steps to reproduce

```
ocrmypdf  -l eng --clean --clean-final  --output-type pdf  input.pdf  ouput.pdf  --jbig2-lossy -v 1 -O3 --deskew --remove-background
```

**Comment by jbarlow83** [comment]
I removed the library that provided background removal, and haven't had a chance to replace it. Unfortunately it's been temporarily not implemented for a few years now.

**Comment by dimyself** [comment]
no problem,thanks for your response! Do you know of another way / program
to replace "remove-background"? I ended up using gimp to edit all the pages
of my pdf to make it black/white and remove noise. I would like to find an
easier way to do it if possible.

Also, I have a scanned pdf that is skewed / bent pages. I used deskew when
running ocrmypdf... but it didn't seem to change the skewed wrIting much,
if at all.

Thank you!
