### ISSUE TITLE
[Feature]: Show page numbers when detecting rotation 

### ISSUE THREAD

**Issue by tsoernes** [ocrmypdf/OCRmyPDF#1422]
### Describe the proposed feature

In the output
page is facing ⇧, confidence 11.26 - no change
page is facing ⇧, confidence 14.80 - rotation appears correct
page is facing ⇧, confidence 8.30 - no change
page is facing ⇧, confidence 9.41 - no change
page is facing ⇧, confidence 11.64 - no change
page is facing ⇧, confidence 10.77 - no change
page is facing ⇧, confidence 11.53 - no change
it would be great with page numbers, also, if the page-numbers are 0-indexed or 1-indexed

**Comment by jbarlow83** [comment]
The page number is injected in logging data and we rely on the logging formatter to render it. If you customize logging in some way, you might end up suppressing the page number.
