### ISSUE TITLE
[Bug]: Docker container entry point

### ISSUE THREAD

**Issue by sneakpodbob** [ocrmypdf/OCRmyPDF#1426]
### What were you trying to do?

The current "latest" docker container is missing the entry point watcher.py.
Commit c8c53d3 seems to fix that issue, but the automatic build/publish workflow seems to fail currently so no new version has been published since that change.

### Where are you installing/running from?

Docker container

### OCRmyPDF version

docker container jbarlow83/ocrmypdf:latest sha256:00be394d4c225c18279227c64e0ead6c998cb1d362833a41c57ac29092db502a

### What operating system are you working on?

Linux

### Operating system details and version

Synology DSM7

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF
- [X] This issue is not about a specific input file

### Relevant log output

```plain text
python3: can't open file '/app/watcher.py': [Errno 2] No such file or directory
```

**Comment by jbarlow83** [comment]
Fixed
