### ISSUE TITLE
[Feature]: Add drop caps support

### ISSUE THREAD

**Issue by 4F2E4A2E** [ocrmypdf/OCRmyPDF#1430]
### Describe the proposed feature

I would like to request a feature which helps recognize drop caps as described in here: 
https://github.com/tesseract-ocr/tesstrain/issues/404

**Comment by jbarlow83** [comment]
Depends on Tesseract recognizing them, which it currently does not do AFAIK.

**Comment by 4F2E4A2E** [comment]
Thanks, for your reply. I guess I'll have to write an plugin for that.
