### ISSUE TITLE
[Bug]: pikepdf PdfMatrix module unavailale 

### ISSUE THREAD

**Issue by IsaacSugden** [ocrmypdf/OCRmyPDF#1432]
### What were you trying to do?

a fresh install:

- conda create -n OCR
- conda activate OCR
- conda install conda-forge::ocrmypdf

gets the following error:
 "    from pikepdf import (
ImportError: cannot import name 'PdfMatrix' from 'pikepdf' (XXX/OCR/lib/python3.11/site-packages/pikepdf/__init__.py)"
and viewing that file, there are indeed many modules with "Pdf" prefix, but no "PdfMatrix", so I suspect its a version issue.
conda list gives, for what I'm guessing are the relevant parts:
python                    3.11.10
ocrmypdf                  14.2.0
pikepdf                   9.3.0

I assume a dependency needs to be updated, but would appreciate any help from those more informed on what 

### Where are you installing/running from?

Conda

### What operating system are you working on?

Linux

### Operating system details and version

5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Simple sanity checks

- [ ] Operating system is currently supported by its vendor (not end of life)
- [ ] Python version is compatible with OCRmyPDF
- [ ] This issue is not about a specific input file

### Relevant log output

```plain text
Traceback (most recent call last):
  File "/home/isugden/csd-python-api_miniconda/envs/OCR/bin/ocrmypdf", line 6, in <module>
    from ocrmypdf.__main__ import run
  File "/home/isugden/csd-python-api_miniconda/envs/OCR/lib/python3.11/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, pdfa, pdfinfo
  File "/home/isugden/csd-python-api_miniconda/envs/OCR/lib/python3.11/site-packages/ocrmypdf/pdfinfo/__init__.py", line 9, in <module>
    from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PageInfo, PdfInfo
  File "/home/isugden/csd-python-api_miniconda/envs/OCR/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 23, in <module>
    from pikepdf import (
ImportError: cannot import name 'PdfMatrix' from 'pikepdf' (/home/isugden/csd-python-api_miniconda/envs/OCR/lib/python3.11/site-packages/pikepdf/__init__.py)
```

**Comment by jbarlow83** [comment]
The ocrmypdf version is too old for that pikepdf version. 

If conda doesn't have compatible versions available they need to update. Not something I can control.

**Comment by IsaacSugden** [comment]
Thankyou for a lightning reply! Built from package (sudo apt install ocrmypdf) and running:
ocrmypdf --version
returns:
9.6.0+dfsg
without errors so I am sure I'll be fine from here. I'm not sure how to inform conda of the need to update, but hopefully this thread will help others
