### ISSUE TITLE
Documentation for ''ocrmypdf.ocr()" not found

### ISSUE THREAD

**Issue by fatsciock** [ocrmypdf/OCRmyPDF#1437]
I'm using the `ocrmypdf.ocr()` method in your library, and I noticed the following comment in the code:

"For most arguments, see documentation for the equivalent command line parameter."

However, it is unclear where the documentation for these arguments can be found. I have searched the OCRmyPDF documentation but I can't find the CLI command docs.

Could you please clarify where this documentation can be located, or if it's missing, provide more details or a reference link? 

Thank you for your help!

**Comment by jbarlow83** [comment]
`ocrmypdf --help`

[ocrmypdf.readthedocs.io](https://ocrmypdf.readthedocs.io/en/latest/cookbook.html) is mainly about the CLI.

There's a near 1:1 mapping between CLI arguments and API.

`ocrmypdf.ocr('in.pdf', 'out.pdf', output_type='pdfa')` <---> `ocrmypdf in.pdf out.pdf --output-type pdfa`

**Comment by fatsciock** [comment]
Thank you very much for the answer, and sorry for the dumb question😅
