### ISSUE TITLE
Larger than input file using "--output-type pdf" with "--deskew --clean --remove-background"

### ISSUE THREAD

**Issue by jmrichardson** [ocrmypdf/OCRmyPDF#261]
I am getting a larger pdf with highlighter on text scanned PDF:

> ocrmypdf --deskew --clean --remove-background --output-type pdf text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
> WARNING - The output file size is 1.48× larger than the input file.
> No reason for this increase is known.  Please report this issue.

Using any of the "--deskew --remove-background" arguments (one or both) results in a larger PDF:  

> ocrmypdf --deskew --output-type pdf text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
> WARNING - The output file size is 3.00× larger than the input file.
> No reason for this increase is known.  Please report this issue.

> ocrmypdf --remove-background --output-type pdf text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
> WARNING - The output file size is 1.48× larger than the input file.
> No reason for this increase is known.  Please report this issue.

> ocrmypdf --deskew --remove-background --output-type pdf text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
> WARNING - The output file size is 1.48× larger than the input file.
> No reason for this increase is known.  Please report this issue.

However, "--clean" does not increase the size:

> ocrmypdf --clean --output-type pdf text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR

Also, without "--output-type pdf", the file size is smaller:

> ocrmypdf --deskew --clean --remove-background  text_with_highlighter.pdf new.pdf
> WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
>    INFO - Output file is a PDF/A-2B (as expected)

Unfortunately, the PDF is sensitive and can't share.  I was hoping for some advice if this is a known issue?

**Comment by jbarlow83** [comment]
Some scanners save PDFs with color segmentation, meaning the page is broken up into color, gray and mono regions. If you use image processing, all of the segments images have to be flattened and promoted to the highest colorspace and encoding level. The output of ``pdfimages -list input.pdf`` would confirm, where ``pdfimages`` comes from the Poppler tool suite.

If the highlight is done in software, the program that does the highlight may be added an image to represent the highlight. If so, that would trigger color promotion.

**Comment by jmrichardson** [comment]
I am not sure how to interpret the output, but your response makes sense.  here is the output:

> pdfimages -list text_with_highlighter.pdf
> page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
> --------------------------------------------------------------------------------------------
>    1     0 image    2563  3309  rgb     3   8  jpeg   no        12  0   301   300 1201K 4.8%

So, If I understand correctly, the color image is segmented, flattened and promoted as you mentioned to be OCRd.  After it is OCRd, the images used for the OCR (highest color space encoding) are re-packed into the PDF instead of the original image?

**Comment by jbarlow83** [comment]
Oh, your case was simpler than I was expecting. Your scanner software is not doing color segmentation; that's just one full page color image.

I believe what's happening here is that the input JPEG was saved at a medium quality setting. My crude heuristic formula says the quality was about 75, given the file size, If ocrmypdf is asked to alter the JPEG it saves at high quality, 90 I think.

In cases where ocrmypdf can copy the JPEG without transcoding it does and produces a similar sized file; when it has to decode, apply image processing, and re-encode, the file might grow. 

Although I'm unsure as to why deskew causes such a large increase. Could you check `pdfimages -list` on the output of ``ocrmypdf --deskew --output-type pdf text_with_highlighter.pdf new.pdf``?

**Comment by jmrichardson** [comment]
Hi, sorry for the delay in replying back (traveling).  Here is the output:

```
$ pdfimages -list new.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2563  3309  rgb     3   8  image  no        10  0   300   300 3616K  15%
```

**Comment by jmrichardson** [comment]
I think the leptonica pix.deskew function in leptonica.py is returning larger images (gray to rgb).  Here is another example of a pdf that is 11.88x larger than the orginal with the --deskew option only:

```
$ ocrmypdf --deskew 1623.pdf new.pdf
WARNING -    2: [tesseract] unsure about page orientation
WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
   INFO - Output file is a PDF/A-2B (as expected)
WARNING -         The output file size is 11.88× larger than the input file.
        Possible reasons for this include:
The argument --deskew was issued, causing transcoding.
```

Image lists:

```
$ pdfimages -list 1623.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image       1     1  gray    1   8  image  no        25  0 0.618 0.591    1B 100%
   1     1 stencil  2547  3300  -       1   1  ccitt  no        26  0   300   300 45.2K 4.4%
   2     2 image       1     1  gray    1   8  image  no        25  0 0.618 0.591    1B 100%
   2     3 stencil  2547  3303  -       1   1  ccitt  no         3  0   301   301 35.5K 3.5%
   3     4 image       1     1  gray    1   8  image  no        25  0 0.618 0.591    1B 100%
   3     5 stencil  2553  3300  -       1   1  ccitt  no         7  0   301   301 29.1K 2.8%
```
```
$ pdfimages -list new.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2550  3300  rgb     3   8  image  no        11  0   300   300  556K 2.3%
   2     1 image    2552  3303  rgb     3   8  image  no        21  0   301   301  427K 1.7%
   3     2 image    2553  3304  rgb     3   8  image  no        27  0   301   301  387K 1.6%
```

Without --deskew (roughly the same size - 1623.pdf is 120k, new.pdf is 140k)

```
$ ocrmypdf 1623.pdf new.pdf
WARNING -    3: [tesseract] unsure about page orientation
WARNING -    2: [tesseract] unsure about page orientation
   INFO - Output file is a PDF/A-2B (as expected)
```

```
pdfimages -list new.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image       1     1  gray    1   8  image  no   [inline]   0.618 0.591    -    -
   1     1 stencil  2547  3300  -       1   1  ccitt  no        11  0   300   300 45.4K 4.4%
   2     2 image       1     1  gray    1   8  image  no   [inline]   0.618 0.591    -    -
   2     3 stencil  2547  3303  -       1   1  ccitt  no        21  0   301   301 35.8K 3.5%
   3     4 image       1     1  gray    1   8  image  no   [inline]   0.618 0.591    -    -
   3     5 stencil  2553  3300  -       1   1  ccitt  no        27  0   301   301 29.2K 2.8%
```
I am wondering if there is a way to coerce leptonica to return the image without modifying the colormap?  Or perhaps, convert the colormap back to original before returning to pipeline?

**Comment by jbarlow83** [comment]
I believe what's going on was not leptonica. There's a decision that's made about the minimal colorspace needed to represent the images in the file. In the absence of information about the colorspace for stencil masks, it promoted the file to full RGB. I tried rewriting the relevant code to ignore masks.

Please try the test branch in test/ignore-masks.

**Comment by jmrichardson** [comment]
Hi, I updated ocrmypdf to the ignore-masks branch and here are the results:

```
$ ocrmypdf --deskew 1623.pdf new.pdf
WARNING -    2: [tesseract] unsure about page orientation
WARNING -    1: [tesseract] lots of diacritics - possibly poor OCR
   INFO - Output file is a PDF/A-2B (as expected)
WARNING -         The output file size is 7.38× larger than the input file.
        Possible reasons for this include:
The argument --deskew was issued, causing transcoding.


es@es1:/ocr/files/pdfs$ pdfimages -list new.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2550  3300  gray    1   8  image  no        11  0   300   300  343K 4.2%
   2     1 image    2552  3303  gray    1   8  image  no        21  0   301   301  266K 3.2%
   3     2 image    2553  3304  gray    1   8  image  no        27  0   301   301  233K 2.8%
```

I am not sure what a stencil image type is but looks like the images were converted into gray (which is better than rgb).  However, the stencil image type with "ccitt" encoding appears to be much better compression.  

I may be able to get approval to send you some of these PDFs to have a closer look if you believe that will help?

Thank you SO much for your product and support!

**Comment by jbarlow83** [comment]
You're welcome.

Probably not necessary for this file but you seem to keep finding interesting files, so if you can approval send them to me as they appear might help in the future. I do like getting issue reports, because it often means problems get found and fixed before my clients run into them. :)

The original file is drawing a 1x1 pixel image probably stretched over the whole page, and then uses stencil masks to omit some of it Possibly, the intent is to produce a shade of gray rather than pure black and white.

I am adding image optimization as a postprocessing step and that will include color reduction with pngquant, so it would like improve your case, although as currently written is not smart enough to reduce to 1bpp and then apply CCITT or JBIG2. Incidentally, it will do JBIG2, which compresses better than CCITT, provided both programs are available to help out. It's in the develop branch now if you want to peek, although as the name suggests, not entirely finished.

**Comment by randfee** [comment]
I've come across the same/similar behaviour #269

**Comment by jbarlow83** [comment]
@jmrichardson  ocrmypdf 7.0.0 should improve this.

**Comment by AmirthaKrishnan** [comment]
@jbarlow83 May i know why PDF is turning into black background with white text,
**arg passed** - --clean --rotate-pages --force-ocr --deskew --output-type pdf.
I have noticed only in **output-type pdf** am getting this black background with white text not in PDF/A format.

**Comment by jbarlow83** [comment]
@AmirthaKrishnan I think you meant to comment on issue #419 ?

**Comment by AmirthaKrishnan** [comment]
@jbarlow83 Okay!
