### ISSUE TITLE
Bug: Using --clean or --treshhold options break the --tesseract-pagesegmode option

### ISSUE THREAD

**Issue by gabrielmongefranco** [ocrmypdf/OCRmyPDF#345]
**Describe the issue**
I am running version 7.x of ocrmypdf (via PyPi) on Debian 9 Stretch with Tesseract 4 from Debian Stretch Backports. When I add the --clean *OR* the --treshold option, the PDF and sidecar outputs are always identical regardless of what pagesegmode (PSM) I specify with --tesseract-pagesegmode. I took me a little while to rule out the other flags, but I'm pretty sure only --clean and --treshold are causing this.

**To Reproduce**
ocrmypdf --language eng_best --jobs 2 --output-type pdf --sidecar --rotate-pages --rotate-pages-threshold 10.1 --remove-background --deskew --remove-vectors --image-dpi 300 --optimize 1 --tesseract-pagesegmode 3 --tesseract-oem 1 test.jpg test_psm3_ocr.pdf
(Add either --clean or --treshold to the above)

Then compare to:

ocrmypdf --language eng_best --jobs 2 --output-type pdf --sidecar --rotate-pages --rotate-pages-threshold 10.1 --remove-background --deskew --remove-vectors --image-dpi 300 --optimize 1 --tesseract-pagesegmode 11 --tesseract-oem 1 test.jpg test_psm11_ocr.pdf
(Add either --clean or --treshold to the above)

And:

ocrmypdf --language eng_best --jobs 2 --output-type pdf --sidecar --rotate-pages --rotate-pages-threshold 10.1 --remove-background --deskew --remove-vectors --image-dpi 300 --optimize 1 --tesseract-pagesegmode 13 --tesseract-oem 1 test.jpg test_psm13_ocr.pdf
(Add either --clean or --treshold to the above)

The results should be different, and the sidecar outputs should be different in size.

**Example file**
(test.jpg can be any scan you have of DPI 300; mine is just one page of a scan of a junk mail envelope to test).

**Comment by gabrielmongefranco** [comment]
Updated title and description. It looks like both --clean and --treshold options both break the pagesegmod. Or maybe it's just in my system... I haven't tried this in Docker yet...

**Comment by jbarlow83** [comment]
I'll need more information. In particular, your example file, since the file is relevant when you are setting pagesegmode. In many cases of sparse text like an envelope `--psm 3, 11, 13` to actually have quite similar results.

It's also unclear to me what you mean that these options "break". Is there an exception or an unexpected result?

**Comment by jbarlow83** [comment]
You could try the test files in tests/resources to see if one of those produces the problem you are seeing.
