### ISSUE TITLE
pngquant produces PNGs that Leptonica can't figure out

### ISSUE THREAD

**Issue by jbarlow83** [ocrmypdf/OCRmyPDF#411]
**Describe the issue**
`leptonica.CompressedData.open` tries to do a transcode-free load and calls back to transcoding. It seems to do this perhaps more often than needed. Compare how img2pdf does this. As a result we transcode and end up with a larger PNG and wasted effort optimizing it.

(Or does img2pdf inline some PNGs it shouldn't?)

Currently kludged test_optimize.py::test_basic to work around this

**Example file**
test_palette.pdf

**Comment by jbarlow83** [comment]
For clarity, the only known side effect of this issue is that image optimization effort is wasted in some cases. There is no loss of image quality.

**Comment by TheLoser85** [comment]
Sex
