### ISSUE TITLE
Searching math equations

### ISSUE THREAD

**Issue by karasjoh000** [ocrmypdf/OCRmyPDF#495]
This is not an issue just a feature request. 

It will be awesome if math equations and formulas were converted to latex expressions. When highlighting or searching for a formula, search by latex or copy latex. Not sure the difficulty of this task but it will be very useful.

**Comment by karasjoh000** [comment]
https://guillaumegenthial.github.io/image-to-latex.html

**Comment by jbarlow83** [comment]
It is possible to use Tesseract with the pseudo-language "equ" for equation detection. You could do `ocrmypdf -l eng+equ` for that (English + "equation language). I have not tried this before and I don't think it attempts to translate them to a latex representation. I'd be curious to hear how it works.

It sounds really interesting but I don't think I'd be able to seriously consider a project of that size unless someone were prepared to sponsor it.

**Comment by kc9jud** [comment]
The `equ` language has been removed from Tesseract 4+: https://github.com/tesseract-ocr/tessdata_fast/issues/4#issuecomment-572740279

**Comment by kc9jud** [comment]
See also https://github.com/tesseract-ocr/tesseract/issues/3693
