### ISSUE TITLE
simple progress when stderr is piped?

### ISSUE THREAD

**Issue by ajweber** [ocrmypdf/OCRmyPDF#511]
I am piping stderr to try and capture progress during pdf processing.

I do not get any of the progress bars/meters (which I really don't want anyway), and only get output that looks like what --no-progress-bar would give me.

Is there a way to get something simple like "dots" for each page completed or percent completed during OCR (and the other phases, if possible)?  It would look very old-school/console'ish, but it would be effective in monitoring progress when piping the information.

Alternatively, does OCRmyPDF keep running status/progress information like this in one of the temp files that I could monitor?

Thanks for all your work.  It's really great.

**Comment by jbarlow83** [comment]
I deliberately switch off progress bars if the file handle attached to
stderr doesn't look like a terminal device.

There is no way to get progress information short of using the API to
customize how output is handled, or forking. For example you could use the
API to log to a special log handler that extracts progress information by
parsing the output.

**Comment by ajweber** [comment]
Thank you for the quick reply. Yeah, I'm trying using "-v 1" to send additional info to the stderr stream and using that in a "hacky" way to figure out progress.  Could you maybe add DEBUG output to stderr with some special format like "OCR: dd%", or something like that?

Right now I'm regex matching on "_ocr_tess" to get the tesseract execution and using the page number out of that.  Very crude and certainly not accurate (it does not account for any pre- or post-processing steps).

**Comment by jbarlow83** [comment]
That will be too verbose even for debug.

One thing you could do at the moment is use the API version `ocrmypdf.ocr()` and monkeypatch or subclass `tqdm` to intercept progress bar updates. It would make sense to eventually tie with this into the plugin interface I'm planning, but work on that keeps getting delayed.

**Comment by ajweber** [comment]
Those lines are missing when not running inside WSL anyway (the new, native Win install method).

I'm not developing in Python, so it's difficult to use the API.

**Comment by jbarlow83** [comment]
I'll arrange for a plugin hook to replace the standard progress bar.

**Comment by v0idwalker** [comment]
This would be very helpful for my use-case as well. Is there a solution or workaround for ocrmypdf to do this? I just need to forward the current status to a web page. Thank you kindly

**Comment by jbarlow83** [comment]
See documentation on plugins. This is now possible.
