### ISSUE TITLE
remove-background option raises exception for some files

### ISSUE THREAD

**Issue by elumbella** [ocrmypdf/OCRmyPDF#725]
**Describe the bug**
Running ocrmypdf with the --remove-background option produces an error and quits

**To Reproduce**
Run `ocrmypdf --deskew --remove-background --clean-final --force-ocr input.pdf output.pdf`

**Expected behavior**
Background should be removed and the file should be processed

**Screenshots**
No screenshots, but the error message:
```
Scanning contents: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 462/462 [00:27<00:00, 16.53page/s]
    1 page already has text! - rasterizing text and running OCR anyway                                                                                 
    1 Error in numaGetIValue: index not valid                                                                                                          

    1 Error in numaGetIValue: index not valid                                                                                                          

    1 Error in numaGetIValue: index not valid                                                                                                          

OCR:   0%|                                                                                                               | 0.0/462.0 [00:01<?, ?page/s]
An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 190, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 133, in make_intermediate_images
    preprocess_out = preprocess(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 102, in preprocess
    image = preprocess_remove_background(image, page_context)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 462, in preprocess_remove_background
    leptonica.remove_background(input_file, output_file)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/leptonica.py", line 970, in remove_background
    pix = pix.background_norm(tile_size=tile_size).gamma_trc(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/leptonica.py", line 658, in background_norm
    return Pix(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/leptonica.py", line 210, in __exit__
    raise IndexError()
IndexError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 371, in run_pipeline
    exec_concurrent(context)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 272, in exec_concurrent
    exec_progress_pool(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 112, in exec_progress_pool
    for result in results:
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
IndexError
```

**System (please complete the following information):**
 - OS: Archlinux
 - Python version: 3.9.1
 - OCRmyPDF version: 11.4.5

**Comment by jbarlow83** [comment]
The error occurs several functions deep inside a C library. Any chance you have a shareable file? 

If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by elumbella** [comment]
Thanks for taking a look!
I do not feel comfortable with sharing the file publicly. I tried to encrypt my pdf using your instructions but gpg fails to get the key. Can you check if the public key information is still up to date?

**Comment by jbarlow83** [comment]
Some edited the wiki to fix a problem with the commands there. Mind try again?
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by elumbella** [comment]
The file is too big to share it here. I emailed it to you instead.

**Comment by jbarlow83** [comment]
Thanks for sharing your file.

I didn't get the error, but I think the error is preferable to how badly remove-background mangled the cover page of your file. :P It doesn't too badly on the rest. (I'd consider splitting the file into parts with a program like `qpdf` and processing the cover page separately, in the interest of getting you a workable file sooner.)

Would you mind checking what version of leptonica (/usr/lib/liblept*) you have installed? The error may be sensitive to that.

(Lately I've been quite tempted to remove the leptonica library entirely... it's been problematic in various ways, the lack of high quality Python bindings in particular.)

**Comment by elumbella** [comment]
Splitting the file is actually a good idea, that I was too lazy to try :D Will definitely do that in the future.

I'm using leptonica version 1.80.0 on archlinux.

**Comment by jbarlow83** [comment]
Feature is temporarily removed.
