### ISSUE TITLE
Add barcode split preprocessing

### ISSUE THREAD

**Issue by lebochequirit** [ocrmypdf/OCRmyPDF#747]
**Is your feature request related to a problem? Please describe.**
I'd like to stuff a pile of documents divided by blank pages with a QR code into the scanner instead of scanning each document.
Then do what ocrmypdf does.

**Describe the solution you'd like**
Scan each pdf input file for a certain barcode/qr code and split the pdf, omitting the qr code pages. As an option, keep the qr code pages if people opt for stickers instead of papers laid in between.

**Describe alternatives you've considered**
Use a preprocessing script, but why call two scripts after each other.

**Additional context**
https://github.com/jholl404/pdf-splitter/blob/master/pdf-splitter.sh
Does the job (keeping the qr page though), needs to be modified in line 95 to omit the page.

Thanks for considering!

L.B.Q.R.

**Comment by jbarlow83** [comment]
You could use plugins to check for the barcode/qr code, track which pages to split to a separate file (or stuff them in a private PDF metadata field), and then do your splitting after ocrmypdf finishes.

See:
https://ocrmypdf.readthedocs.io/en/latest/plugins.html

You would probably hook @filter_ocr_image to test for barcodes.

This is the sort of behavior that I think fits better in a script that uses the ocrmypdf API. The specific behaviors you'd want are hard to express in a command line. Maybe someone puts the desired output filename in a barcode. As you mentioned, someone might want to keep code pages and someone else might want to cut them. A script can handle all of that. NP-complete customization should not be attempted in command line arguments.

**Comment by gador** [comment]
Interesting idea.
As far as I understand it, this just describes how to hook a script in ocrmypdf. 

The script itself uses ghostscript to convert the pdf to an image. The image gets the Barcode detected by zbar.

I personally would rather use pdf2image as a python library then use a hook to an external Programm (ghostscript) to convert a pdf to an image.
