### ISSUE TITLE
[ENHANCEMENT] Google Colab notebook

### ISSUE THREAD

**Issue by louispaulet** [ocrmypdf/OCRmyPDF#766]
# Google Colab example

Hello, I've made a Google Colab notebook and I think it would be a nice addition to your repo with an "Open in colab" badge so users can test it right away.  

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/louispaulet/OCRmyPDF_google_colab/blob/main/PDF_OCR.ipynb)

I've used the "--force-ocr" param because my PDF files contained text (with a corrupted font issue), feel free to change it.

**Comment by jbarlow83** [comment]
Thank you for the suggestion but I don't think I would be able to maintain this.

**Comment by IlianP** [comment]
But it *does* still work (even without maintaining it), so it seems.
@jbarlow83 I found yours via googling for "ocrmypdf colab"

the following one even installs the chosen tesseract language(s), I haven't tested it yet, though:
https://github.com/karim23657/ocrmypdf/blob/main/OCRmyPDF.ipynb

**Comment by jbarlow83** [comment]
I understand it may work for you. I decided that I don't have time to maintain a Colab notebook and ensure it is up to date. If you or someone else want to submit a pull request and commit to maintaining it, that would be fine.
