### ISSUE TITLE
Is it possible to graft the invisible OCR text layer produced on another PDF?

### ISSUE THREAD

**Issue by macdeport** [ocrmypdf/OCRmyPDF#799]
I was happy to discover OCRmyPDF recently and I try to learn its best use.

I just used it on a B&W text image (as PDF container) containing a small colored area.

The PDF produced is entirely in B&W, presumably to perform the OCR: the colored area is therefore lost while it does not contribute to the OCR text...

Is it possible to graft the invisible OCR text layer produced on another PDF (which could be the color input PDF)?

**Comment by jbarlow83** [comment]
ocrmypdf already products an invisible text layer and grafts it on to the original (unless you use certain arguments to select other behavior - see `--skip-text --redo-ocr --force-ocr`).

It will be easier if I can look at the actual file and exact command line you are using. If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/jbarlow83/OCRmyPDF/wiki

**Comment by macdeport** [comment]
Thank you for your reply.

Unfortunately I destroyed the original input file before your reply and cannot reproduce the previous result. Of course if it happens again I will send you the input file with its command line, if it seems relevant.

Also, regardless of OCRmyPDF, is it possible to graft the PDF containing the OCR text onto a PDF that did not generate it and if so how?

**Comment by jbarlow83** [comment]
Ocrmypdf's *default* behavior is to graft the OCR layer on to the PDF.

Use --output-type pdf to minimize changes since PDF/A conversion does change some things.
