### ISSUE TITLE
Really Quiet Mode

### ISSUE THREAD

**Issue by mmeinesz** [ocrmypdf/OCRmyPDF#869]
**using the -q option doesn't supress errors**
The -q option still keeps listing so called errors, eg if files are encrypted, or are alreaddy ocr'ed

I am running ocrmypdf on large folders every night, most of which have previously been ocr'ed already. The log I am creating has a lot of unecessary messages, that are not real errors in my sense.
I would propose an other option option, eg --supress_errors, that would not show these messages. Besides that many thanks for the great piece of software!

**Comment by jbarlow83** [comment]
Generally the POSIX convention is that `-q` mode does output errors. I see where you're coming from though. If some others chime in I may change something, although probably more like an `--return-zero-if-already-has-ocr` type of argument (with a better name).

You write a little wrapper script that invokes `ocrmypdf.ocr()` and also configures logging however you want it managed. The documentation describes how to set this up. Maybe that would be more suitable?

**Comment by mmeinesz** [comment]
I don't fully understand. You presume I invoke a Python script?
I guess that is beyond my scope. I am just a user. 
For my own usage I could filter out those error messages in a shell script, that wouldn't be to complicated.
Just wanted to let you know about this issue, I think others would find it handy, too.

**Comment by jbarlow83** [comment]
What I am saying is, to customize the logging behavior, one should write a brief Python script. The API is straightforward.
