### ISSUE TITLE
"killed" issue, can not run ocrmypdf

### ISSUE THREAD

**Issue by frank-laemmer** [ocrmypdf/OCRmyPDF#871]
**Describe the bug**  
I can not run ocrmypdf. It always get's "killed". No matter what I try to do (passing files, return version). See the terminal output below. Also the Apple crash reporter opens and reports an issue with Python.

**To Reproduce**  
Not sure. I guess there is something specific to my local config. I tried to Google the error to no avail. I have checked my Python installation (also via homebrew).

**Screenshots**
Terminal output:  
<img width="263" alt="Screenshot 2021-12-12 at 18 57 15" src="https://user-images.githubusercontent.com/962736/145723803-df11790f-e2c2-46ca-81f0-5e3da9d02a64.png">

Crash reporter:  
<img width="959" alt="Screenshot 2021-12-12 at 19 12 18" src="https://user-images.githubusercontent.com/962736/145724426-4ae64659-46a9-4b51-9e15-aa68b4bde482.png">

**System**
 - OS: macOS 12.1
 - MacBook Air m1
 - Python version:
 - OCRmyPDF version: 12.7.2

```
brew info ocrmypdf
ocrmypdf: stable 12.7.2 (bottled)
Adds an OCR text layer to scanned PDF files
https://github.com/jbarlow83/OCRmyPDF
/opt/homebrew/Cellar/ocrmypdf/12.7.2 (1,464 files, 31.7MB) *
  Poured from bottle on 2021-11-07 at 20:32:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ocrmypdf.rb
License: MPL-2.0
==> Dependencies
Build: pkg-config ✔, rust ✔
Required: ghostscript ✔, jbig2enc ✔, leptonica ✔, libffi ✔, libpng ✔, pillow ✔, pngquant ✔, pybind11 ✔, python@3.9 ✔, qpdf ✔, tesseract ✔, unpaper ✔
==> Analytics
install: 2,118 (30 days), 8,647 (90 days), 32,861 (365 days)
install-on-request: 2,117 (30 days), 8,642 (90 days), 32,840 (365 days)
build-error: 1 (30 days)
```

**Installation**  
I installed ocrmypdf and Python via homebrew. 

**Additional context**  
I imagine that this is NOT ocrmypdf-related, but has something to do with my Python installation. 

Feel free to close as hard to reproduce. 
Thanks for your time!

**Comment by jbarlow83** [comment]
ocrmypdf 13.x might help - removes some ABI level binding code that can be fragile.

Also I'd check if you can do things like `python -m ocrmypdf ....` and just `python`.

**Comment by jbarlow83** [comment]
Closing due to lack of additional information and old version

**Comment by frank-laemmer** [comment]
Thanks. Looking forward for 13.x

+ `python` starts the macOS version of Python I believe, states: `WARNING: Python 2.7 is not recommended. ...`
+ `python -m ocrmypdf .....` prints `.../Python.framework/Versions/2.7/...Python: No module named ocrmypdf`

**Comment by jbarlow83** [comment]
Python 2.7 reached end of life in early 2020. It's not supported.

I suggest installing Homebrew and using that to install ocrmypdf which get new a Python and everything else you need. See documentation for detailed instructions.

**Comment by frank-laemmer** [comment]
Thanks for supporting me on this. It becomes even more clear that there is something wrong about my setup. I am sharing this in the case somebody else will run in this. I am still not able to run `ocrmypdf`. Here is what I get:

```shell
$ python3 -m ocrmypdf
/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ocrmypdf
```

```shell
ocrmypdf
[1]    6848 killed     ocrmypdf
```

I also tried passing params.

**Comment by jbarlow83** [comment]
Try `brew reinstall ocrmypdf`? Also `brew doctor` and fix any problems....?
