### ISSUE TITLE
cannot run under python 3.10

### ISSUE THREAD

**Issue by starsareintherose** [ocrmypdf/OCRmyPDF#872]
**Describe the bug**
python 3.10 updated and then it broken

**To Reproduce**
```
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 33, in <module>
    sys.exit(load_entry_point('ocrmypdf==13.1.0', 'console_scripts', 'ocrmypdf')())
  File "/usr/bin/ocrmypdf", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for ocrmypdf
```
**Expected behavior**
can run under 3.10

**System (please complete the following information):**
 - OS:ArchLinux
 - Python version:3.10.1
 - OCRmyPDF version:13.1.0

**Installation**
AUR

**Additional context**

**Comment by jbarlow83** [comment]
CI currently tests Python 3.10 on all three major platforms. The issue is likely local configuration or related to Arch. Perhaps reinstalling Python packages will suffice.

**Comment by pigmonkey** [comment]
This is an Arch specific issue and should be closed here.

Arch pushed a new Python version. AUR Python packages need to be rebuilt whenever this happens. The bump to 13.1.1 will cause this to happen for OCRmyPDF, but there's still a couple AUR Python dependencies that Arch users will need to manually reinstall (python-coloredlogs, python-humanfriendly).

**Comment by starsareintherose** [comment]
okay, thanks for telling me.

**Comment by ki9us** [comment]
I had this error on the first install.  For me, there was no `python-coloredlogs` in pacman, and AUR's `python-coloredlogs` was not recognized by ocrmypdf.  `pip install coloredlogs` worked though.

**Comment by Poorna2211** [comment]
Hi I am same issue I even installed the above libraries coloredlogs and humanfriendly  but I am getting the same error I even uninstalled  all the libraries and reinstalled again  but no use 
The system I am using is acer 
Os windows 11
Python 3.10.7
