### ISSUE TITLE
lept = ffi.dlopen(find_library('lept')) 

### ISSUE THREAD

**Issue by maheshreddy-agi** [ocrmypdf/OCRmyPDF#873]
**Describe the bug**
What's the problem?

I have installed the ocrmypdf using **apt install ocrmypdf** in linux

after that I want to OCR on image pdf  using **ocrmypdf -l eng+jpn --title "My_PDF" --output-type pdfa /Path/EPT20200128-001.pdf /Path/OCR_EPT20200128-001.pdf**

Then I'm getting the error in the image attached

![image](https://user-images.githubusercontent.com/73687288/145749850-26d4c601-b556-4e6c-b170-9359e00e8803.png)

**Comment by jbarlow83** [comment]
Please upgrade to ocrmypdf 13.x. For a variety of reasons that code was scrapped entirely in the latest version. The documentation gives a procedure for installing the latest version with pip.
