### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by lehrling12** [ocrmypdf/OCRmyPDF#875]
**Describe the bug**
Just trying to run a basic python script to ocr a single pdf. 
Importing ocrmypdf works fine, but when running the _ocrmypdf.ocr_ I keep getting the error: _FileNotFoundError: [WinError 2] The system cannot find the file specified_

I have verified that python can access the pdf, so I don't think it's an issue with my path. I am assuming there is something simple I overlooked.

I have also tried on python versions: 3.7.11 , 3.9.7.

I have also just directly tried running:  ocrmypdf 1.pdf 2.pdf  directly in the prompt.

**To Reproduce**
import ocrmypdf
import_path = r'C:\Users\Jee Yun Kim\Documents\book\1.pdf'
save_path = r'C:\Users\Jee Yun Kim\Documents\book\2.pdf'

def ocr(file_path, save_path):
    ocrmypdf.ocr(file_path, save_path, rotate_pages=True,
    remove_background=True,language="en", deskew=True, force_ocr=True)

ocrmypdf.ocr(import_path,save_path) 

**Here is the full traceback **
FileNotFoundError                         Traceback (most recent call last)
C:\Users\JEEYUN~1\AppData\Local\Temp/ipykernel_15212/2827552947.py in <module>
----> 1 ocrmypdf.ocr(import_path,save_path)

~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\api.py in ocr(input_file, output_file, language, image_dpi, output_type, sidecar, jobs, use_threads, title, author, subject, keywords, rotate_pages, remove_background, deskew, clean, clean_final, unpaper_args, oversample, remove_vectors, force_ocr, skip_text, redo_ocr, skip_big, optimize, jpg_quality, png_quality, jbig2_lossy, jbig2_page_group_size, pages, max_image_mpixels, tesseract_config, tesseract_pagesegmode, tesseract_oem, tesseract_thresholding, pdf_renderer, tesseract_timeout, rotate_pages_threshold, pdfa_image_compression, user_words, user_patterns, fast_web_view, plugins, plugin_manager, keep_temporary_files, progress_bar, **kwargs)
    334 
    335         options = create_options(**create_options_kwargs)
--> 336         check_options(options, plugin_manager)
    337         return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
    338 

~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\_validation.py in check_options(options, plugin_manager)
    269 
    270 def check_options(options, plugin_manager):
--> 271     ocr_engine_languages = plugin_manager.hook.get_ocr_engine().languages(options)
    272     _check_options(options, plugin_manager, ocr_engine_languages)
    273 

~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py in languages(options)
    153     @staticmethod
    154     def languages(options):
--> 155         return tesseract.get_languages()
    156 
    157     @staticmethod

~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\_exec\tesseract.py in get_languages()
    112     args_tess = ['tesseract', '--list-langs']
    113     try:
--> 114         proc = run(
    115             args_tess,
    116             text=True,

~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\subprocess\__init__.py in run(args, env, logs_errors_to_stdout, **kwargs)
     50     stderr_name = 'stderr' if not logs_errors_to_stdout else 'stdout'
     51     try:
---> 52         proc = subprocess_run(args, env=env, **kwargs)
     53     except CalledProcessError as e:
     54         stderr = getattr(e, stderr_name, None)

~\Anaconda3\envs\python39\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    503         kwargs['stderr'] = PIPE
    504 
--> 505     with Popen(*popenargs, **kwargs) as process:
    506         try:
    507             stdout, stderr = process.communicate(input, timeout=timeout)

~\Anaconda3\envs\python39\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    949                             encoding=encoding, errors=errors)
    950 
--> 951             self._execute_child(args, executable, preexec_fn, close_fds,
    952                                 pass_fds, cwd, env,
    953                                 startupinfo, creationflags, shell,

~\Anaconda3\envs\python39\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1418             # Start the process
   1419             try:
-> 1420                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                                          # no special security
   1422                                          None, None,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Expected behavior**
Populate 2.pdf 

**System**
 - OS: Windows 10
 - OCRmyPDF Version: 13.1.1
 - How did you install ocrmypdf? pip install ocrmypdf

Thank you in advance!

**Comment by jbarlow83** [comment]
Is Tesseract installed and on the system path?

**Comment by lehrling12** [comment]
I have adjusted to:
import ocrmypdf
import pytesseract
pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
import_path = r'C:\Users\Jee Yun Kim\Documents\book\1.pdf'
save_path = r'C:\Users\Jee Yun Kim\Documents\book\2.pdf'

def ocr(file_path, save_path):
    ocrmypdf.ocr(file_path, save_path, rotate_pages=True,
    remove_background=True,language="en", deskew=True, force_ocr=True)

ocrmypdf.ocr(import_path,save_path) 

- Unfortunately I still get the error:

> FileNotFoundError                         Traceback (most recent call last)
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\subprocess\__init__.py in get_version(program, version_arg, regex, env)
>     138     try:
> --> 139         proc = run(
>     140             args_prog,
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\subprocess\__init__.py in run(args, env, logs_errors_to_stdout, **kwargs)
>      51     try:
> ---> 52         proc = subprocess_run(args, env=env, **kwargs)
>      53     except CalledProcessError as e:
> 
> ~\Anaconda3\envs\python39\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
>     504 
> --> 505     with Popen(*popenargs, **kwargs) as process:
>     506         try:
> 
> ~\Anaconda3\envs\python39\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
>     950 
> --> 951             self._execute_child(args, executable, preexec_fn, close_fds,
>     952                                 pass_fds, cwd, env,
> 
> ~\Anaconda3\envs\python39\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
>    1419             try:
> -> 1420                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>    1421                                          # no special security
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> The above exception was the direct cause of the following exception:
> 
> MissingDependencyError                    Traceback (most recent call last)
> C:\Users\JEEYUN~1\AppData\Local\Temp/ipykernel_14028/2827552947.py in <module>
> ----> 1 ocrmypdf.ocr(import_path,save_path)
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\api.py in ocr(input_file, output_file, language, image_dpi, output_type, sidecar, jobs, use_threads, title, author, subject, keywords, rotate_pages, remove_background, deskew, clean, clean_final, unpaper_args, oversample, remove_vectors, force_ocr, skip_text, redo_ocr, skip_big, optimize, jpg_quality, png_quality, jbig2_lossy, jbig2_page_group_size, pages, max_image_mpixels, tesseract_config, tesseract_pagesegmode, tesseract_oem, tesseract_thresholding, pdf_renderer, tesseract_timeout, rotate_pages_threshold, pdfa_image_compression, user_words, user_patterns, fast_web_view, plugins, plugin_manager, keep_temporary_files, progress_bar, **kwargs)
>     334 
>     335         options = create_options(**create_options_kwargs)
> --> 336         check_options(options, plugin_manager)
>     337         return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
>     338 
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\_validation.py in check_options(options, plugin_manager)
>     270 def check_options(options, plugin_manager):
>     271     ocr_engine_languages = plugin_manager.hook.get_ocr_engine().languages(options)
> --> 272     _check_options(options, plugin_manager, ocr_engine_languages)
>     273 
>     274 
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\_validation.py in _check_options(options, plugin_manager, ocr_engine_languages)
>     265     check_options_advanced(options)
>     266     check_options_pillow(options)
> --> 267     plugin_manager.hook.check_options(options=options)
>     268 
>     269 
> 
> ~\Anaconda3\envs\python39\lib\site-packages\pluggy\_hooks.py in __call__(self, *args, **kwargs)
>     263             firstresult = False
>     264 
> --> 265         return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
>     266 
>     267     def call_historic(self, result_callback=None, kwargs=None):
> 
> ~\Anaconda3\envs\python39\lib\site-packages\pluggy\_manager.py in _hookexec(self, hook_name, methods, kwargs, firstresult)
>      78         # called from all hookcaller instances.
>      79         # enable_tracing will set its own wrapping function at self._inner_hookexec
> ---> 80         return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
>      81 
>      82     def register(self, plugin, name=None):
> 
>     [... skipping hidden 3 frame]
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\builtin_plugins\ghostscript.py in check_options(options)
>      19 @hookimpl
>      20 def check_options(options):
> ---> 21     gs_version = ghostscript.version()
>      22     check_external_program(
>      23         program='gs',
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\_exec\ghostscript.py in version()
>      53 
>      54 def version():
> ---> 55     return get_version(GS)
>      56 
>      57 
> 
> ~\Anaconda3\envs\python39\lib\site-packages\ocrmypdf\subprocess\__init__.py in get_version(program, version_arg, regex, env)
>     148         output: str = proc.stdout
>     149     except FileNotFoundError as e:
> --> 150         raise MissingDependencyError(
>     151             f"Could not find program '{program}' on the PATH"
>     152         ) from e

> MissingDependencyError: Could not find program 'gswin64c' on the PATH


Thanks for the reply!

**Comment by jbarlow83** [comment]
You'll need to make sure you have matching 64 bit or 32 bit versions of everything. Tesseract, Ghostscript, Python should all be the same bit-ness. You may have a mixture based on the paths shown. 

Ocrmypdf does not use pytesseract, it calls Tesseract directly. 

This may be an Anaconda packaging issue.

**Comment by lehrling12** [comment]
Yes that was my issue. I had not installed ghostscript correctly and kept having that issue. As an aside I was still able to run my script with pytesseract. Thank you for your help!
