### ISSUE TITLE
Page numbers doubled by error

### ISSUE THREAD

**Issue by rostam2000** [ocrmypdf/OCRmyPDF#876]
I am running the last 13.1.1 build on mac OS Monterey, and I get a strange error at the start: All page numbers are doubled after the first run through the PDF file I intend to OCR. This is without any --redo-ocr or --force-ocr command being applied. This means that the OCR will drag on with hundreds of 'empty' pages after all the real ones have been processed. Could anyone kindly point me out to why this might be the case?

Many thanks

**Comment by jbarlow83** [comment]
It will be easier if I can look at the actual file. If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/ocrmypdf/OCRmyPDF/wiki

You could also try running `qpdf --json` to generate a structural JSON. This is sometimes enough to find problems in the file and it also removes all text and images.

**Comment by rostam2000** [comment]
Thanks, this happens with virtually all PDFs at present, here is one. I think there is something which triggers it in the 13.x code, as it never happened with 12.x builds.

[test.pdf.gpg.zip](https://github.com/ocrmypdf/OCRmyPDF/files/7740611/test.pdf.gpg.zip)

**Comment by jbarlow83** [comment]
Thanks, fixed it. This was purely, 100% a display and presentation issue. No extra work was actually being done, the progress bar just updated extra times in some cases. Every file processed this should be fine.
