### ISSUE TITLE
How can I use parameter --author if value has spaces?

### ISSUE THREAD

**Issue by geimist** [ocrmypdf/OCRmyPDF#878]
**Describe the bug**
I like to set metadata with argument --author. This works fine. But when I use a value, who has spaces, ocrmypdf can't read the parameters.

```
ocropt="-dcs -l deu+eng --author \"John Doe\""

cat "$input" | docker run --network none --rm -i -log-driver=none -a stdin -a stdout -a stderr $dockercontainer $ocropt - - | cat - > "$outputtmp"

    usage: ocrmypdf [-h] [-l LANGUAGES] [--image-dpi DPI] 
                    …
    ocrmypdf: error: unrecognized arguments: -
```
❌ The same with this variants:
```
ocropt="-dcs -l deu+eng --author 'John Doe'"
ocropt="-dcs -l deu+eng --author \'John Doe\'"
ocropt="-dcs -l deu+eng --author 'John\ Doe'"
ocropt="-dcs -l deu+eng --author \"John\ Doe\"" 
```

✅ This works fine:
`ocropt="-dcs -l deu+eng --author John_Doe"`

**System (please complete the following information):**
 - OS: linux docker x86_64
 - OCRmyPDF version: all

**Comment by jbarlow83** [comment]
This is a shell expansion issue.

I believe you should instead make a bash array with each argument as one string, then insert the array. 

See

https://opensource.com/article/18/5/you-dont-know-bash-intro-bash-arrays

**Comment by geimist** [comment]
Thanks for your answer.
Arrays are not completely foreign to me, but perhaps I didn't fully understand your approach:

```
ocropt=( "-dcs" "-l deu+eng" "--author 'John Doe'" )
cat "$input" | docker run --name synOCR --network none --rm -i -log-driver=none -a stdin -a stdout -a stderr $dockercontainer ${ocropt[@]} - - | cat - > "$outputtmp"
```

The result is the same.

**Comment by jbarlow83** [comment]
Try:

```bash

ocropt=( "-dcs" "-l" "deu+eng" "--author" "John Doe" )

```

**Comment by geimist** [comment]
Once you get it right, it works 
weird 🤣

Thank you very much - not only for this answer, but for the entire project 👍
