### ISSUE TITLE
Horizontal and vertical Text on same page

### ISSUE THREAD

**Issue by numerys** [ocrmypdf/OCRmyPDF#883]
I have pages with horizontal and vertical text. Horizontal detection is good, is it possible to have vertical text, mixed with horizontal text inside the same PDF-page?
Vertical text as attached...
![screenshot](https://user-images.githubusercontent.com/17107201/147689481-39d3ff57-3915-493f-b171-f52a2901364b.png)

**Comment by jbarlow83** [comment]
This depends on Tesseract OCR, which currently does not do a great job when there are multiple orientations on a page. ocrmypdf cannot do much when Tesseract messes up the OCR such as in this case.
