### ISSUE TITLE
tesseract-config disregarded?

### ISSUE THREAD

**Issue by femifrak** [ocrmypdf/OCRmyPDF#885]
When I use` --tesseract-config my.cfg`
with my.cfg like:

`language_model_penalty_non_dict_word 0.15`

the value of the penalty (0.15) seems to be disregarded. Any value leads to the same outcome of `--sidecar result.txt`, although there are several misspelled words.

Do I miss something or how can I reduce misspelled word outcome?

additional info:

- Misspelling `language_model_penalty_non_dict_word` leads to this error:
`[tesseract] Warning: Parameter not found` => file is used.

- Replacing the numerical value 0.15 by a string (e.g. `xxx`) does **not** lead to an error.

- OCRmyPDF version: 13.2

- tesseract version: 5.0.0

**Comment by jbarlow83** [comment]
Maybe see if you can get a difference in behavior using Tesseract on its own? Run with `-k ` to get the temporarily files and command lines send to Tesseract in debug.log.

**Comment by femifrak** [comment]
similar behaviour in tesseract directly:

- misspelled parameter (e.g. lllllanguage_model_penalty_non_dict_word) leads to a warning. 
- string instead of float has no effect (even no warning)
- different floats have as well no effect.

**Comment by femifrak** [comment]
found a hint at:

https://github.com/tesseract-ocr/tesseract/issues/2940


> language_model_penalty_non_dict_word
> language_model_penalty_non_freq_dict_word
> 
> Note that these parameter are used only by the legacy engine.
> 
> 

That's really a pity. Don't know how to avoid misspelled words now ...

**Comment by femifrak** [comment]
As tesseract 5 with LSTM does not allow for these configurations, this is not ocrmypdf issue.
