### ISSUE TITLE
Not able to remove grey background

### ISSUE THREAD

**Issue by maiiabocharova** [ocrmypdf/OCRmyPDF#886]
Hello, I have a scanned PDF which has a dirty-grey background, I am trying to get rid of it (convert to white). I tried using PIL and it does the job, but the quality after converting PDF to jpg or png decreases considerably, so I tried using OCRmyPDF, but faced an issue:
`ocrmypdf -l eng+chi_sim --remove-background --clean-final input.pdf output.pdf`
gives me an error
`NotImplementedError: --remove-background is temporarily not implemented`

Please can you suggest what can I do? (Basically I just want to make grey dirty background white without losing the quality)

Upd. Saw that the feature --remove-background is temporarily removed. But maybe there is an alternative that I can use?

**Comment by jbarlow83** [comment]
As the error says this feature was temporarily removed for reasons outlined in the change log. 

Most likely it will become an optional plugin in a future release, because it will require large dependencies. 

You could try downgrading to v12.

**Comment by jhult** [comment]
Just linking related info:

- Commit: https://github.com/ocrmypdf/OCRmyPDF/commit/59642a98b2e0d8a3b60f2dbd5cdf525fb2d9c48a
- Related issue: #884 
- Change log: https://ocrmypdf.readthedocs.io/en/latest/release_notes.html#v13-0-0
