### ISSUE TITLE
Exception when processing certain files with --clean option

### ISSUE THREAD

**Issue by Caleb13-2** [ocrmypdf/OCRmyPDF#887]
I've encounterd exceptions while processing two PDF files with over-saturated scan. They occur only when the --clean option is enabled. Originally, the PDFs had 60 pages, but I found that only one page in then caused problems. I extracted the problem pages with Adobe Acrobat, I'm attaching them below.  Overally, I processed about 800 pages with such bad scan quality, but only these two caused problems. I'm also attaching TXT file with error messages from the console. I've used these parameters:

ocrmypdf --clean --output-type pdf -l ces+slk

I don't use Linux much, so I've run it in Ubuntu 21.04 on a virtual machine (VirtualBox) hosted in Windows 10. OCRmyPDF version is 13.2.0, I installed it about a week ago via commands recommended on the docs page.

BTW, OCRmyPDF has much better recognition accuracy than OCR built in latest Adobe Acrobat DC while processing these old and poorly scanned docs. Thanks for creating it!

[PE_90-P33.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7824256/PE_90-P33.pdf)
[KP_89-P38.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7824257/KP_89-P38.pdf)
[Console_output2.txt](https://github.com/ocrmypdf/OCRmyPDF/files/7824289/Console_output2.txt)

**Comment by jbarlow83** [comment]
Fixed in ea69e868

**Comment by Caleb13-2** [comment]
Today, I've tried the problematic files 

> Fixed in [ea69e86](https://github.com/ocrmypdf/OCRmyPDF/commit/ea69e868ed95a335b362a3708628c0372cb7abb8)

Today, I've tried the problematic files in version 13.4.0+dfsg-1 on Ubuntu 22.04LTS, but both caused exceptions again. Are you sure your fix made it to the correct branch?

**Comment by jbarlow83** [comment]
The "fix" (sorry) was to provide a more accurate error message. `unpaper` can't process large images beyond a certain size, and there's no option I'm aware of to override its internal limits. The best we can do is inform the user that the image is too large to be cleaned by unpaper.

**Comment by Caleb13-2** [comment]
That's odd. I mean, I processed literally thousands of pages with the same resolution and bit depth, but only these two caused problems. Also, their resolution is 3300 by 4600 pixels, which is nothing by today's standards.

To test this, I extracted the scanned image as PNG with pdfimages utility (it's stored as CCITT in the source PDFs). Then I created a single-page PDF from it with img2pdf. When I fed that to ocrmypdf, no error occured. So it's not about image size, there is some other problem.

**Comment by jbarlow83** [comment]
It's possible ocrmypdf is deciding it needs to render a large version of the image and then feeding that image to unpaper.
Have a look here to find the temporary file that ocrmypdf is feeding to unpaper.
https://ocrmypdf.readthedocs.io/en/latest/advanced.html#debugging-the-intermediate-files

**Comment by Caleb13-2** [comment]
Resolution is not the issue. I used the -k argument as you suggested, but the temporary PNG image has the same resolution as the internal CCITT data. I'm attaching it along with the resulting log.
![000001_rasterize](https://user-images.githubusercontent.com/70209677/177058001-b2479e06-be14-4f0f-a2a3-2ade392e8b98.png)
[debug.log](https://github.com/ocrmypdf/OCRmyPDF/files/9035526/debug.log)

**Comment by jbarlow83** [comment]
Looks like this another manifestation of #665. I implemented a workaround for the next release.
