### ISSUE TITLE
[Question] --remove-vectors what does it do?

### ISSUE THREAD

**Issue by Mark-Joy** [ocrmypdf/OCRmyPDF#890]
1. Is it correct that `--remove-vectors` only remove vector graphics for OCR processing and not the final output?

2. Does vector graphics include Searchable Text, Hightlights and Annotations?

I have documents that have some Highlights and Annotations. I want to remove them for OCR process but not final pdf. 

Thank You.

**Comment by jbarlow83** [comment]
1. Correct
2. It might include highlights and annotations, but it depends. We use Ghostscript's `-dFILTERVECTOR` argument to actually do the work, which you can use a PDF separately to see what it does. Or use ocrmypdf's `--keep-temporary-files` and review the intermediate images to see the intermediate behavior. (Sometimes highlights and annotations are "burned into" to the PDF such that they can't be removed easily anymore, etc.)
