### ISSUE TITLE
[Question] optimize by grouping existing jbig2 files

### ISSUE THREAD

**Issue by Mark-Joy** [ocrmypdf/OCRmyPDF#891]
It seems that if existing jbig2 files in pdf were not grouped (not shared a common symbol-table file) then `optimize` will not try to group them either.
Does pikepdf (or any tool) support this? 
It can easily save 15-25% storage space.

**Comment by jbarlow83** [comment]
This is provided in a way through `--jbig2-lossy -O3`.

Unfortunately the jbig2enc program does not provide a lossless and grouped jbig2 mode so we cannot use it in normal cases. 

I'm not aware of any other open source implementation of jbig2enc.

**Comment by jbarlow83** [comment]
I should add that if you do `--output pdf` any existing grouped jbig2 optimization will be preserved. The default behaviour, PDF/A conversion, will convert jbig2 to ccitt unfortunately. That's a limitation of Ghostscript.

**Comment by Mark-Joy** [comment]
> This is provided in a way through `--jbig2-lossy -O3`.
> 
> Unfortunately the jbig2enc program does not provide a lossless and grouped jbig2 mode so we cannot use it in normal cases.

@jbarlow83 Thank you for your answer.
What I meant was how to convert several [`lossless` jbig2 files] into [`lossy` jbig2 files that shared a symbol-table file]?

If jbig2 files are already exist as lossless ones in the pdf, then even `--jbig2-lossy -O3` option could not make them into lossy. Or am I missing something?

**Comment by jbarlow83** [comment]
With `--output-type pdfa --jbig2-lossy -O3`, all mono JBIG2 images may be lossy re-encoded.
