### ISSUE TITLE
-O9: Convert all images to JBIG2

### ISSUE THREAD

**Issue by Mark-Joy** [ocrmypdf/OCRmyPDF#893]
**Is your feature request related to a problem? Please describe.**
I am trying to optimize pdf files that should be in black and white only. Even if they have some color images, I want to convert all of them to JBIG2.

**Describe the solution you'd like**
I add [optimization level 9](https://github.com/Mark-Joy/OCRmyPDF/commit/53494ee707853ff33db05af217ec3311f4406a66) which should do the above job.
1. `extract_images_generic` will return empty if -O9
2. Let `extract_image_jbig2` handle all images if -O9 even color images.

Used command: 
`ocrmypdf --skip-text --jbig2-lossy --optimize=9 --output-type=pdf --lang=eng "/sdcard/Download/test-jbig2-opt/in.pdf" "/sdcard/Download/test-jbig2-opt/out.pdf" --keep-temporary-files`

However the images in the output pdf are messed up when viewing in most of the pdf reader app.

**Example file**
Input:
![IMG_20220110_184441](https://user-images.githubusercontent.com/22109528/148761204-f6221769-6833-4052-ab09-27997b6295d6.jpg)
Output:
![IMG_20220110_184512](https://user-images.githubusercontent.com/22109528/148761294-ada17c34-d7da-46d2-ac50-7ad4ec441a53.jpg)

However in one specific app: `ebook Reader - Mixplorer`, images are showing up correctly ( or... Incotrectly !??)
![IMG_20220110_184533](https://user-images.githubusercontent.com/22109528/148761684-18a70c82-a201-4bd4-8c36-d097703d983a.jpg)

That's why I know I was doing it partly correct, but maybe missing something.

Please help review [my code](https://github.com/Mark-Joy/OCRmyPDF/commit/53494ee707853ff33db05af217ec3311f4406a66). It's only some simple modifications.

Here are the test files: 
[test-jbig2-opt.zip](https://github.com/ocrmypdf/OCRmyPDF/files/7838638/test-jbig2-opt.zip)

Thank you.

**Comment by jbarlow83** [comment]
Your input file contains color text rather than images. The optimizer only looks for images, and has no way of replacing introduced in this way. `--force-ocr` would convert this text to images, apply OCR, and then your strategy would probably work.

To make a portable version of your work, you could write a plugin that hooks `filter_ocr_image` and `filter_page_image`, replacing both with a black and white version of the page, perhaps produced by Ghostscript with the raster device set to `pngmonod`. Then using your plugin and `--force-ocr`, you'd force everything to 1 bit images and the optimizer would automatically handle the JBIG2 conversion.

**Comment by Mark-Joy** [comment]
Thank you for valuable insight.
And sorry for not being clear. When I said black and white, I meant images, not the text.
Images (color jpg, png) were converted to JBIG2 in `optimize.convert_to_jbig2` function. Check temporary folder for intermedia files: group00000000.0000, group00000000.0001, group00000000.sym.
I can convert them back to png format by below command: 
```shell
jbig2dec -o group0.png group00000000.sym group00000000.0000
jbig2dec -o group1.png group00000000.sym group00000000.0001
```
![group0](https://user-images.githubusercontent.com/22109528/148849281-663b4c56-9f72-4483-baa6-38033d78c773.png)
![group1](https://user-images.githubusercontent.com/22109528/148849309-91f8ba44-8e99-4f28-a42d-123e39b8759a.png)
 
[images.zip](https://github.com/ocrmypdf/OCRmyPDF/files/7842310/images.zip)

Since they were converted from color images to JBIG2 correctly, I thought some things in the `remain pdf presentation of the image` were not taken care of when they were converted. A pdf tag or something..
I really hope that was the case, wouldn't you agree?

**Comment by jbarlow83** [comment]
My guess is that there's some part of the XObject that isn't being adjusted correctly in your code, and the viewer happens to ignore that setting. Maybe BitsPerComponent? 

Unless this is an issue in standard ocrmypdf (without your customizations) I don't think I can look into this. My recommendation would be to use plugins to change the images before the optimizer runs.

**Comment by Mark-Joy** [comment]
OMG, previously I set `im_obj.bits_per_component = 1` copied from existing code without checking if the key was correct. Turn out it must be: `im_obj.BitsPerComponent = 1`
Here is the [working code!](https://github.com/Mark-Joy/OCRmyPDF/commit/1ee68f6eb7e0b0e8d3e031be5c1ab2e2c6e06f4d)

Thank you!
