### ISSUE TITLE
"img2pdf.ExifOrientationError: Invalid rotation (0)" is easily fixable

### ISSUE THREAD

**Issue by eulores** [ocrmypdf/OCRmyPDF#894]
Several images have a wrongly encoded rotation value of 0. This is not conform and produces an error with `img2pdf`, unless the parameter `--rotation=ifvalid` is passed.

The value `ifvalid` acts like auto but ignores invalid EXIF rotation values and only issues a warning instead of throwing an error. This is useful because many devices like Android phones, Canon cameras or scanners emit an invalid Orientation tag value of zero.

`ocrmypdf` uses the API of `img2pdf`. The equivalent would be passing this keyword argument `rotation=Rotation.ifvalid` to `convert()`

**Comment by jbarlow83** [comment]
Thanks - will do.

It's an easy fix on paper, but this feature was only added to img2pdf 0.4.3, and we support older versions so it needed some retrofitting.

**Comment by eulores** [comment]
Thanks!
