### ISSUE TITLE
--pages

### ISSUE THREAD

**Issue by Ludek007** [ocrmypdf/OCRmyPDF#895]
Hello,
all function perfect.
My interest PDF > read-only text to file.TXT only first page
param **--pages** do not function me.

ocrmypdf --pages 1 --output-type pdf --optimize 0  --deskew  --force-ocr --oversample 300  --sidecar /var/www/html/test.txt /var/www/html/test2.pdf /var/www/html/test_output.pdf

usage: ocrmypdf [-h] [-l LANGUAGE] [--image-dpi DPI]
                [--output-type {pdfa,pdf,pdfa-1,pdfa-2,pdfa-3}]
                [--sidecar [FILE]] [--version] [-j N] [-q] [-v [VERBOSE]]
                [--title TITLE] [--author AUTHOR] [--subject SUBJECT]
                [--keywords KEYWORDS] [-r] [--remove-background] [-d] [-c]
                [-i] [--oversample DPI] [--remove-vectors] [--mask-barcodes]
                [--threshold] [-f] [-s] [--redo-ocr] [--skip-big MPixels]
                [-O {0,1,2,3}] [--jpeg-quality Q] [--png-quality Q]
                [--jbig2-lossy] [--max-image-mpixels MPixels]
                [--tesseract-config CFG] [--tesseract-pagesegmode PSM]
                [--tesseract-oem MODE] [--pdf-renderer {auto,hocr,sandwich}]
                [--tesseract-timeout SECONDS]
                [--rotate-pages-threshold CONFIDENCE]
                [--pdfa-image-compression {auto,jpeg,lossless}]
                [--user-words FILE] [--user-patterns FILE] [-k]
                [--flowchart FLOWCHART]
                input_pdf_or_image output_pdf

ocrmypdf: error: unrecognized arguments: --pages /var/www/html/parse/test_output.pdf

**Comment by jbarlow83** [comment]
Based on the output that is an old version of ocrmypdf that I can't support anymore. Probably around v6. We're at v13 now.
