### ISSUE TITLE
OCR gets stuck at 0.5 or 1.0/x pages, creates some but not all temp files for all pages, then hangs

### ISSUE THREAD

**Issue by eggplantedd** [ocrmypdf/OCRmyPDF#898]
**Describe the bug**
I set it going on a pdf (can upload if you want), it scans 100% with no errors, then proceeds to OCR, but gets stuck/'freezes' on 1.0 or 0.5 out of however many pages.
![image](https://user-images.githubusercontent.com/96150927/149834443-4ad41092-9839-4a75-a42a-ab34e19b68b5.png)

However, if I go to the temp folder, I can see the program producing _some_ but not _all_ the necessary files. This is what it produces for each page:

000005_ocr.png
000005_ocr_tess.pdf
000005_ocr_tess.txt
000005_rasterize.png

It works through all the pages like this, but then doesn't do anything with them. 

**To Reproduce**
To get it to run I had to use the following script, cribbed from this: https://github.com/ocrmypdf/OCRmyPDF/issues/517

import ocrmypdf
if __name__ == "__main__":
    ocrmypdf.ocr('input.pdf', 'output.pdf')

Ran from the command line, not in admin mode.

**Expected behavior**
produce 'output.pdf'.

**Screenshots**
At the bottom I've attached the verbose output, (with my hard drive letter stripped).
This is how it's left after working through all the pages.
[input.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7884245/input.pdf)

**System (please complete the following information):**
 - OS: Windows 7 Professional 64-bit
 - Python version: 3.8
 - OCRmyPDF version: latest

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

Installed via PIP, fresh install of Python, Tesseract, Ghostscript.

-------------------
\Desktop\Uni\WIP2\out\350dpi - Copy>run.py
  DEBUG ocrmypdf.subprocess - Running: ['Program Files\\Tesseract-OCR\\tesse
ract.EXE', '--list-langs']
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available langua
ges (2):
eng
osd

  DEBUG ocrmypdf._validation - No language specified; assuming --language eng
  DEBUG ocrmypdf.subprocess - Running: ['Program Files\\Tesseract-OCR\\tesse
ract.EXE', '--version']
  DEBUG ocrmypdf.subprocess - Found tesseract 5.0.0-alpha.20210506
  DEBUG ocrmypdf.subprocess - Running: ['Program Files\\gs\\gs9.55.0\\bin\\g
swin64c.EXE', '--version']
  DEBUG ocrmypdf.subprocess - Found gs 9.55.0
Scanning contents: 100%|ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ| 326/326 [00:02<00:00, 113.98page/s]
  DEBUG ocrmypdf.builtin_plugins.tesseract_ocr - Using Tesseract OpenMP thread l
imit 1
   INFO ocrmypdf._sync - Start processing 4 pages concurrently
OCR:   0%|                                       | 0.0/326.0 [00:00<?, ?page/s]
 DEBUG ocrmypdf._pipeline -    2  Rasterize with pngmono, rotation 0
  DEBUG ocrmypdf._pipeline -    1  Rasterize with pngmono, rotation 0
  DEBUG ocrmypdf.subprocess -    2  Running: ['Program Files\\gs\\gs9.55.0\\
bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolate
Control=-1', '-sDEVICE=pngmono', '-dFirstPage=2', '-dLastPage=2', '-r350.000000x
350.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', 'Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\origin.pdf']
  DEBUG ocrmypdf.subprocess -    1  Running: ['Program Files\\gs\\gs9.55.0\\
bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolate
Control=-1', '-sDEVICE=pngmono', '-dFirstPage=1', '-dLastPage=1', '-r350.000000x
350.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', 'Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\origin.pdf']
  DEBUG ocrmypdf._pipeline -    3  Rasterize with pngmono, rotation 0
  DEBUG ocrmypdf.subprocess -    3  Running: ['Program Files\\gs\\gs9.55.0\\
bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolate
Control=-1', '-sDEVICE=pngmono', '-dFirstPage=3', '-dLastPage=3', '-r350.000000x
350.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', 'Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\origin.pdf']
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2296
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'default_gray.icc'
  DEBUG PIL.PngImagePlugin -    2  Compression method 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2349 9
  DEBUG PIL.PngImagePlugin -    2  STREAM b'tEXt' 2370 31
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2413 7805
  DEBUG ocrmypdf._exec.ghostscript -    2  Rotating output by 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2291
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    2  Compression method 0
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2344 9
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2365 7996
  DEBUG ocrmypdf._pipeline -    2  resolution (350.012, 350.012)
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2296
  DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'default_gray.icc'
  DEBUG PIL.PngImagePlugin -    1  Compression method 0
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2349 9
  DEBUG PIL.PngImagePlugin -    1  STREAM b'tEXt' 2370 31
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2413 8192
  DEBUG ocrmypdf._exec.ghostscript -    1  Rotating output by 0
  DEBUG ocrmypdf._pipeline -    4  Rasterize with pngmono, rotation 0
  DEBUG ocrmypdf.subprocess -    4  Running: ['Program Files\\gs\\gs9.55.0\\
bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolate
Control=-1', '-sDEVICE=pngmono', '-dFirstPage=4', '-dLastPage=4', '-r350.000000x
350.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', 'Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\origin.pdf']
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    1  STREAM b'iCCP' 41 2291
  DEBUG PIL.PngImagePlugin -    1  iCCP profile name b'ICC Profile'
  DEBUG ocrmypdf.subprocess -    2  Running: ['Program Files\\Tesseract-OCR\
\tesseract.EXE', '-l', 'eng', '-c', 'textonly_pdf=1', 'Users\\User\\AppDat
a\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000002_ocr.png', 'Users\\User\\AppDa
ta\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000002_ocr_tess', 'pdf', 'txt']
  DEBUG PIL.PngImagePlugin -    1  Compression method 0
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 2344 9
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 2365 14856
  DEBUG ocrmypdf._pipeline -    1  resolution (350.012, 350.012)
  DEBUG PIL.PngImagePlugin -    3  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    3  STREAM b'iCCP' 41 2296
  DEBUG PIL.PngImagePlugin -    3  iCCP profile name b'default_gray.icc'
  DEBUG PIL.PngImagePlugin -    3  Compression method 0
  DEBUG PIL.PngImagePlugin -    3  STREAM b'pHYs' 2349 9
  DEBUG PIL.PngImagePlugin -    3  STREAM b'tEXt' 2370 31
  DEBUG PIL.PngImagePlugin -    3  STREAM b'IDAT' 2413 8192
  DEBUG ocrmypdf._exec.ghostscript -    3  Rotating output by 0
  DEBUG ocrmypdf.subprocess -    1  Running: ['Program Files\\Tesseract-OCR\
\tesseract.EXE', '-l', 'eng', '-c', 'textonly_pdf=1', 'Users\\User\\AppDat
a\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000001_ocr.png', 'Users\\User\\AppDa
ta\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000001_ocr_tess', 'pdf', 'txt']
  DEBUG PIL.PngImagePlugin -    3  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    3  STREAM b'iCCP' 41 2291
  DEBUG PIL.PngImagePlugin -    3  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    3  Compression method 0
  DEBUG PIL.PngImagePlugin -    3  STREAM b'pHYs' 2344 9
  DEBUG PIL.PngImagePlugin -    3  STREAM b'IDAT' 2365 15771
  DEBUG ocrmypdf._pipeline -    3  resolution (350.012, 350.012)
  DEBUG PIL.PngImagePlugin -    4  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    4  STREAM b'iCCP' 41 2296
  DEBUG PIL.PngImagePlugin -    4  iCCP profile name b'default_gray.icc'
  DEBUG PIL.PngImagePlugin -    4  Compression method 0
  DEBUG PIL.PngImagePlugin -    4  STREAM b'pHYs' 2349 9
  DEBUG PIL.PngImagePlugin -    4  STREAM b'tEXt' 2370 31
  DEBUG PIL.PngImagePlugin -    4  STREAM b'IDAT' 2413 8192
  DEBUG ocrmypdf._exec.ghostscript -    4  Rotating output by 0
  DEBUG ocrmypdf.subprocess -    3  Running: ['Program Files\\Tesseract-OCR\
\tesseract.EXE', '-l', 'eng', '-c', 'textonly_pdf=1', 'Users\\User\\AppDat
a\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000003_ocr.png', 'Users\\User\\AppDa
ta\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000003_ocr_tess', 'pdf', 'txt']
  DEBUG PIL.PngImagePlugin -    4  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -    4  STREAM b'iCCP' 41 2291
  DEBUG PIL.PngImagePlugin -    4  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -    4  Compression method 0
  DEBUG PIL.PngImagePlugin -    4  STREAM b'pHYs' 2344 9
  DEBUG PIL.PngImagePlugin -    4  STREAM b'IDAT' 2365 15857
  DEBUG ocrmypdf._pipeline -    4  resolution (350.012, 350.012)
  DEBUG ocrmypdf.subprocess -    4  Running: ['Program Files\\Tesseract-OCR\
\tesseract.EXE', '-l', 'eng', '-c', 'textonly_pdf=1', 'Users\\User\\AppDat
a\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000004_ocr.png', 'Users\\User\\AppDa
ta\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\000004_ocr_tess', 'pdf', 'txt']
OCR:   0%|                               | 0.5/326.0 [00:02<32:10,  5.93s/page]
 DEBUG ocrmypdf._graft -    2  Text rotation: (text, autorotate, content) -> tex
t misalignment = (0, 0, 0) -> 0
  DEBUG ocrmypdf._graft -    2  Grafting
  DEBUG ocrmypdf._graft -    2  Page rotation: (content, auto) -> page = (0, 0)
-> 0
  DEBUG ocrmypdf._pipeline -    5  Rasterize with pngmono, rotation 0
  DEBUG ocrmypdf.subprocess -    5  Running: ['Program Files\\gs\\gs9.55.0\\
bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolate
Control=-1', '-sDEVICE=pngmono', '-dFirstPage=5', '-dLastPage=5', '-r350.000000x
350.000000', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', 'Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.uo5mom5g\\origin.pdf']

**Comment by jbarlow83** [comment]
I tested your file on Windows 10 (w/Python 3.10, Tesseract 5, installed using Choco) and ocrmypdf seems to work correctly. Also tested on Ubuntu with Python 3.9 and Tesseract 5.

I hope you can understand that I don't support end of life operating systems or third party software, which currently includes Windows 7. Wish I could do more, but I have to draw the line somewhere.

If you have an older machine (in particular, one without the AVX2 and AVX-512 instruction set - that includes many Windows 7 era machines) it's quite possible that the OCR is just very slow, easily taking well over a minute per page so you won't notice any progress on a large file. Tesseract 4 and newer rely heavily on the AVX instructions and fall back on quite slow methods without them. Try a single page file to see if it gets anywhere.

Your best bet to get results from an older machine it to use a paid OCR service.
