### ISSUE TITLE
skip-text and force-ocr are not working properly 

### ISSUE THREAD

**Issue by typeoo** [ocrmypdf/OCRmyPDF#903]
**Describe the bug**
Hi,
When I use skip-text even the pages that have pictures will be skipped. I created a pdf file via ms word some pages just have one picture and some pages have text, pages that have pictures are skipped also without OCR performing.

Also when I use --force-ocr, output pdf will not be selectable and every page turns to an image.

**To Reproduce**
Pictures are skipped:
`ocrmypdf -l fas+eng  -k --skip-text --optimize 0 --sidecar pdfpic.txt pdfpic.pdf o/pdfpic.pdf `

forec-ocr:
`ocrmypdf -l fas+eng  -k --force-ocr  --sidecar /var/www/html/o/t.txt picandtxt.pdf o/picandtxt.pdf `

**The created pdf is not searchable** 

**Example file**

Input:
[picandtxt.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7967158/picandtxt.pdf)

[picandtxt.docx](https://github.com/ocrmypdf/OCRmyPDF/files/7967159/picandtxt.docx)

**Screenshots**

![t](https://user-images.githubusercontent.com/66176156/151721928-f8ab344a-b0a1-4b2d-920b-092836d108de.PNG)

**System**
 - OS:Linux Ubuntu 20.4
 - OCRmyPDF Version: ``v13.3.0``
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image? pip

Thanks for making this great project.

**Comment by jbarlow83** [comment]
This isn't a common situation - if you have the docx you can insert the text directly. But you have your reasons.  

`--redo-ocr` may fit the bill, despite the name, since what it actually does is try to filter out printable text and OCR the remainder.

**Comment by typeoo** [comment]
I will check redo-ocr  and share the result, But if a pdf has been made by MS Word and it contains both text and picture, how can I use skip-text in this case ? 
And why sometimes the output  doesn't  have the ocr layer ? 
Also mentioning  some common  pdf files will be appreciated.

Thanks  a lot

**Comment by typeoo** [comment]
So it means when I insert an Image inside a page, that page will be treated as a text?
After upgrading to v13.3.0 my pdf output doesn't have ocr text layer and nothing is selectable. Should I change my code or it is a new change in this version?
This is my input:
[oneimage.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7977881/oneimage.pdf)
This my command:
`ocrmypdf -l fas+eng  --force-ocr --sidecar /var/www/html/o/t.txt oneimage.pdf o/oneimage.pdf
`
I also tried **--redo-ocr** but still no ocr layout.

Thanks for your attention.

**Comment by jbarlow83** [comment]
We don't look for images on pages. We look for text. If there's text on a page that is generally a signal that we do not want to run OCR on that page or even that file. --skip-text and --redo-ocr are the instructions you give to handle pages with text.

--force-ocr means you don't care about existing text, and you want everything converted to images and then OCRed.

Hmm, it works for me. I suggest trying Tesseract 5 which I'm using. For Ubuntu you need to set up a PPA for it. https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-devel

Tesseract 4 has problems with low contrast text like your oneimage.pdf - it probably can't see the text at all.
[_.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7980812/_.pdf)

**Comment by typeoo** [comment]
Hello again,
I tried Tesseract 5 also but still I can't get a text layout inside my pdf as the file you sent. 
I remember I could do it before, but now it doesn't work.
From which version you got that output?
Also ocrmypdf creates the sidecar file with no problem. 
I check versions 13.3.0 and 12.7.1
Thank you.
