### ISSUE TITLE
support monochromatic conversion

### ISSUE THREAD

**Issue by jknockaert** [ocrmypdf/OCRmyPDF#906]
**Is your feature request related to a problem? Please describe.**
My scanner produces grayscale tiff files which I am converting in searchable pdfs. In order to control for file size I convert the scan to monochromatic (bitonal) with Group4 compression in the pdf. But for the OCR I prefer to use the original grayscale scan as it carries more information. I scripted everything together with imagemagick, tesseract and pdftk, producing 300dpi monochromatic searchable scans with a small file size (like 70KB for a one page document).

**Describe the solution you'd like**
Everything to happen in OCRmyPDF. So feeding a grayscale PDF and producing a text-searchable bitonal pdf. Perhaps with an extra option to set the dpi resolution of the output pdf.
In an initial version this could be limited to one colour, but I've seen high-end scanners produce multi-color 300dpi pdf files with very small filesize (less than 50KB for a one page text document). What they do is segment the page in a number of printed areas of homogenous colour, and then for each area produce a bitonal image. Then in the pdf everything is patched together. This is quite efficient for printed text documents which are often using a very limited number of primary colours. The OCRmyPDF documentation makes reference to such optimisation in section 1.2:
> A PDF page might contain multiple images, even if it only appears to have one image. Some scanners or scanning software will segment pages into monochromatic text and color regions for example, to improve the compression ratio and appearance of the page.

I think that support for such optimisation falls within the scope of OCRmyPDF, as you will want to run the OCR operation on the original image rather than the (monochromatic) optimised one.

**Describe alternatives you've considered**
As described above I scripted everything together with imagemagick, tesseract and pdftk. But that way I'm missing out on the other features of OCRmyPDF (such as further optimisations and the desired pdf format such as PDF/A).

**Comment by jbarlow83** [comment]
See issue #541 for some discussion on this in the past, in particular for page segmentation. For a while my reply was that I needed someone to sponsor the work given the time commitment to implement this feature. 

I expected I'd need to read a few research papers to find a good algorithm, so I figured it would take a few weeks full time. It's  a encoding problem: finding an optimal (possibly lossy) encoding that can be efficient encoded by a combination of existing encoders. Individually image encoders already good at segmenting internally. (A PNG showing a blank page with a color logo in the corner is going to be almost the same file size as one cropped to the corner.)

Also there is an interesting proposed from an archive.org developer to use their existing open source solution, but it's not license compatible and depends on a static library so it cannot be packaged in a way that would make our downstream packages happy, but they are interested in finding a solution to those obstacles.

OCRmyPDF's existing optimizer does attempt to quantize images. If it's able to quantize a PNG type image in a PDF to a 1 bit per pixel image, it will then convert to CCITT or JBIG2 if available. It currently does this for each image on the page and does not try to segment the page or images. You can tune the settings to make it do so more aggressively, but it's often reluctant to go all the way to 1 bit. (I'd probably still stick to image segmentation, just replacing images with a composite image.)

Note Tesseract internally converts the input image to monochrome if given grayscale. Tesseract 4 used a really simple algorithm, that made some images unreadable. Tesseract 5 offers choices and has a better default algorithm. But it still does this anyway. (Of necessity. OCR neural nets just end up "learning" to threshold if the input isn't thresholded, i.e. it's fundamental to text recognition to discriminate text from background.) OCRmyPDF generates a special image for Tesseract based on your settings which is not necessarily the same as the page image.

**Comment by jknockaert** [comment]
The segmentation solution would be a powerful tool for small size full colour scans at high resolution (say 300dpi). But it's quite a bit of work as well to get there.
What I'm doing now (for text documents) is scan grayscale at 300dpi  and then convert it to monochromatic (black/white). It's very efficient as it results in small filesizes and it still produces very good quality scans. Much better than using the grayscale scans at `-O3` in ocrmypdf. Perhaps a specific optimisation option could be implemented that handles all the conversion to monochromatic at 300dpi; it would be left to the user to decide if monochromatic is a proper format for the type of document being processed (for instance in the case of scanning monochromatic text documents, which are quite common).

**Comment by rdiez** [comment]
The problem with your suggestion is the user intervention. In a small organisation, nobody has time to select the right method for the current document. Sometimes, documents are collected and scanned at once in large quantities, often on a scanner with an automatic paper feeder. The commercial solutions I have seen handle the colour and black-and-white areas automatically, which is a great advantage.

I was hoping that the implementation wouldn't be too hard. After all, the following open-source examples have been mentioned in other GitHub Issues:
https://github.com/jwilk/didjvu
https://github.com/internetarchive/archive-pdf-tools

**Comment by jknockaert** [comment]
I agree that it would be preferable to avoid user intervention. I was more thinking of an initial implementation as a quick win. And as well as to provide the option of forcing monochromatic in case the user really wants it.

**Comment by jknockaert** [comment]
> Note Tesseract internally converts the input image to monochrome if given grayscale. Tesseract 4 used a really simple algorithm, that made some images unreadable. Tesseract 5 offers choices and has a better default algorithm. But it still does this anyway. (Of necessity. OCR neural nets just end up "learning" to threshold if the input isn't thresholded, i.e. it's fundamental to text recognition to discriminate text from background.) OCRmyPDF generates a special image for Tesseract based on your settings which is not necessarily the same as the page image.

Seems like Tesseract uses the monochrome image only for layout analysis, whereas for the identified text areas the OCR is run on the original grayscale; see https://github.com/tesseract-ocr/tesseract/issues/1780#issuecomment-405288249

The only way to produce high quality monochromatic searchable pdfs seems to be to script it for now (missing out on the other optimisation algorithms that ocrmypdf provides).

**Comment by jbarlow83** [comment]
This is now supported by using `ocrmypdf --color-conversion-strategy Gray ...` which would convert all color objects to gray.
