### ISSUE TITLE
Support multiple image filters, or at least the common combination /FlateDecode/DCTDecode

### ISSUE THREAD

**Issue by rdiez** [ocrmypdf/OCRmyPDF#910]
OCRmyPDF skips processing PDF images that use more than 1 filter. The log message is "Skipping multiply filtered image". It should actually read "multiply-filtered image", for the hyphen makes it easier to understand.

Apparently, it is quite common to compress an image first with JPEG, and then with Deflate. I thought that compressing a JPEG wouldn't achieve anything, but I saw a 20 % space reduction on a test JPEG generated by a commercial scanner/OCR software.

Such images use both "/FlateDecode/DCTDecode" filters. This article explains the matter:

https://kb.itextpdf.com/home/it7kb/faq/how-to-add-jpeg-images-that-are-multi-stage-filtered-dctdecode-and-flatedecode

When I do a first pass with Ghostscript, the resulting images (and overall PDF) get bigger, even though the images are not recoded. I guess that Ghostscript does not support or apply multiple filters to the images, at least by default. When I then process the intermediate PDF with OCRmyPDF "--optimize 3", then the images are optimised as expected, and the PDF file decreases nicely.

I wonder what would happen if OCRmyPDF were to try to Deflate the JPEG streams. Perhaps it would further save space, at least with some JPEGs where big areas are empty.

**Comment by jbarlow83** [comment]
My recollection is that saving JPEGs in Pillow with optimize=True was pretty much equivalent to multi staged compression so generating images this way does not help. 

Adding the ability to inspect /FlateDecode/DCTDecode images may be worthwhile because we might be able to optimize the DCTDecode and currently skip that opportunity.

**Comment by rdiez** [comment]
I am not familiar with Pillow (or even with Python) and I couldn't find quickly a description about what "optimize=True" does in detail.

It is also hard to measure whether Deflate after JPEG would save space, because neither Ghostscript nor OCRmyPDF support it.

But I made the following simple test with the PDF file that I attached to this comment.
```
$ pdfimages -list input.pdf 
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1240  1753  rgb     3   8  jpeg   no         8  0   150   150 76.5K 1.2%
   1     1 stencil  1896  2628  -       1   1  ccitt  no         9  0   300   300 33.8K 5.6%
   1     2 stencil   184    72  -       1   1  ccitt  no   [inline]     300   300   24B 1.4%

$ sudo docker container run --rm --interactive  jbarlow83/ocrmypdf  --tesseract-timeout=0 --output-type pdf --optimize 3 - - <input.pdf >output.pdf

$ pdfimages -list output.pdf
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    1240  1753  rgb     3   8  jpeg   no        12  0   150   150 59.3K 0.9%
   1     1 stencil  1896  2628  -       1   1  jbig2  no        13  0   300   300 23.4K 3.8%
   1     2 stencil   184    72  -       1   1  ccitt  no   [inline]     300   300   24B 1.4%
```
So OCRmyPDF did re-encode both the JPEG and the CCITT images.
```
$ zip DeflateTest.zip output.pdf 
  adding: output.pdf (deflated 12%)
```
The resulting files are:
```
123.134  input.pdf
 94.381  output.pdf
 82.777  DeflateTest.zip
```
Therefore, the old 'zip' compressor managed to compress the PDF by 12 %.

I then extracted the JPEG image like this:

`$ pdfimages -all output.pdf Image`

And compressed it like this:
```
$ zip DeflateImageTest.zip Image-000.jpg 
  adding: Image-000.jpg (deflated 17%)
```
This yields (among other files):
```
60.757  Image-000.jpg
50.357  DeflateImageTest.zip
```
So it seems that the JPEG stream can be compressed by a surprising 17 %, just by using the old 'zip' compressor with standard options.

[input.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8014596/input.pdf)

**Comment by jbarlow83** [comment]
Thanks for doing the legwork to demonstrate an improvement. Shouldn't be hard to do so I will look into.

> couldn't find quickly a description about what "optimize=True" does in detail.

Enables better Huffman encoding not supported by the earliest JPEG decoders but now widely supported. Normally this makes further attempts to losslessly encode pointless.

**Comment by jbarlow83** [comment]
ocrmypdf 13.4.0 now considers /FlateDecode/DCTDecode images for optimization instead of skipping them, and tries to apply /FlateDecode to all /DCTDecode images. Seems to work well.

**Comment by rdiez** [comment]
Brilliant, many thanks!
