### ISSUE TITLE
Using Ubuntu Snap as packaging format

### ISSUE THREAD

**Issue by alexanderlanganke** [ocrmypdf/OCRmyPDF#914]
I took the liberty of creating a snap application recipe "snapcraft.yaml" which enables snapcraft's build plattform to build a working snap application for ocrmypdf.

Take a look here:
https://github.com/alexanderlanganke/ocrmypdf-snap

While building it pulls in the application using PIP so that it always uses the most recent version. This may make it easier for users to access ocrmypdf.

So far I am getting the application to build and run but am running into a missing dependancy during runtime. I believe I need to adjust the path for one or two libraries.

I have also registered this snap (private for now) on snapcraft.

If you are interested, and I get it working, I would offer to maintain this snap for you or pass it on to you if you wish to do it yourself. Credit for the application will of course go to you!
Snapcraft pulls from github so you basically need to get it working once and never touch it again. It will rebuild whenever you push to the linked repository (version bump for example).

**Comment by jbarlow83** [comment]
This is a good idea - ocrmypdf's non-Python dependencies need better packaging. Too busy to get involved right now I'm afraid. Maybe look at the Makefile for pikepdf and install docs for ideas on working around the runtime dependency issue if that's where it is coming from.

When it's ready I can set it up under the ocrmypdf organization.

**Comment by alexanderlanganke** [comment]
Just ran into a problem with apparmor. The snap itself runs fine as long as it is not in "strict" confinement. 
Need to fix this before it can run in sandboxed mode.

**Comment by jbarlow83** [comment]
How is the apparmor problem?

**Comment by alexanderlanganke** [comment]
Have not had time to look into it further unfortunately..

**Comment by alexanderlanganke** [comment]
I have been working on it again and believe I am getting close, hopefully..

right now I am stuck trying to get the snapcraft build system to build ocrmypdf from source using your github repository as a source.

The snap is built successfully and includes ocrmypdf as a "part" BUT does not have your program actually installed inside.
I am following these instructions here: https://snapcraft.io/docs/python-apps
which state: 

> The source keyword points to the root of your Python project and can be a local directory or remote Git repository. Note that your Python project should be using setuptools and you should be able to run python setup.py bdist_wheel without errors

Is that the case for you? your setup.py looks a lot different than I am used to so this may the culprit here. Perhaps I can get the snap sorted out if you can point me in the right direction.

**Comment by jbarlow83** [comment]
Yes, it uses setuptools and setup.py bdist_wheel should work fine. It may be that snapcraft's tooling uses older versions of setuptools or something along those lines. In newer releases setuptools is moving towards static configuration files like setup.cfg and pyproject.toml. I've often had good luck with this sort of problem by trying to find a similar program to crib from, i.e. you want a Python command line program that makes subprocess calls. Maybe look at asciinema?

**Comment by alexanderlanganke** [comment]
I believe I figured it out. The problem was with my snapcraft.yaml and some unexpected behavior in core20.
I was able to build a working snap on my local machine. I am currently waiting for it to build on the snap build service. If that works then we have a snap package in the store (private for now).

**Comment by alexanderlanganke** [comment]
Bump ;-)

**Comment by jbarlow83** [comment]
I made a few comments in snapcraft.yaml, mainly tidying up.

How should install it for testing? Currently I get

```
> snap install --devmode --edge ocrmypdf
error: snap "ocrmypdf" not found
```

I suggest next step should be making it public and then you setting up a GitHub Actions workflow to automatically run the build and publish on commit (or maybe published on tagged commit).

After that we could try the process outlined [here](https://github.community/t/triggering-by-other-repository/16163/12), i.e. main ocrmypdf, on successful build, would trigger a new build in the snapcraft repo.

**Comment by alexanderlanganke** [comment]
You cannot install it for testing right now because the snap is set to Private.

I did Not want to publish anything without your approvel. 

If I understand you correctly you are ok with me doing that?

**Comment by alexanderlanganke** [comment]
I put it in "unlisted" mode. You can download and install it
via: `sudo snap install ocrmypdf`

**Comment by alexanderlanganke** [comment]
If you have gotten around to testing it.. we should probably discuss automation as you mentioned above.

Just to clarify. I already have an automatic connection to snapcraft set up. When I commit to the repo, snapcraft automatically builds a new snap. I then manually promote that snap to one of the snap branches (i.e. edge, beta, candidate, stable).

The easiest thing would be for you to put my snapcraft.yaml into your repo with minimal changes (version number to match yours etc.). After that I change the snapcraft build target to your repo. That way you will trigger a build when you commit something. I can then either hand off the ownership of the snap to you or add you as a collaborator, whichever you prefer.

I am of course open to a different path.

**Comment by jbarlow83** [comment]
Ok, I added and pushed snapcraft.yaml, with the version set to "git". That is supposed to use `git describe` to resolve the version.

It would be ideal for snapcraft to only trigger on tagged versions if there's a way to do that. Either way, what you propose is better than my multi-repo method, although the drawback is I might not get feedback if the snap is broken.

Please add me as a collaborator to the snap.

**Comment by alexanderlanganke** [comment]
I just tried to add your repo but unfortunately it does seem to want
access..

Lets add you as a collaborator first so that you can add your repo yourself.

I need an email Adress  for that. What should I use?

**Comment by jbarlow83** [comment]
I think I've got it set up now. Take a look.

**Comment by jbarlow83** [comment]
Yes, the snap works for me. Thanks for putting it together.

I think I set it up so that the metadata including icons etc just gets pulled from snapcraft.yaml.

**Comment by alexanderlanganke** [comment]
I just made it public.

The store pulls in Metadata as in Text from the snapcraft.yaml. it does not
pull in Icons or Screenshots. This can be done manually.

**Comment by alexanderlanganke** [comment]
I just made it public.

The store pulls in Metadata as in Text from the snapcraft.yaml. it does not
pull in Icons or Screenshots. This can be done manually.

I put in the logo_square.png which probably suffices.

Currently Metadata such as description etc. Is very short in your snapcraft.yaml. Since the store pulls this in, perhaps you want to copy and paste something like:



OCRmyPDF adds an OCR text layer to scanned PDF files, allowing them to be searched or copy-pasted.

ocrmypdf # it's a scriptable command line program -l eng+fra # it supports multiple languages --rotate-pages # it can fix pages that are misrotated --deskew # it can deskew crooked PDFs! --title "My PDF" # it can change output metadata --jobs 4 # it uses multiple cores by default --output-type pdfa # it produces PDF/A by default input_scanned.pdf # takes PDF input (or images) output_searchable.pdf # produces validated PDF output

See the release notes for details on the latest changes.

Main features

Generates a searchable PDF/A file from a regular PDF

Places OCR text accurately below the image to ease copy / paste

Keeps the exact resolution of the original embedded images

When possible, inserts OCR information as a "lossless" operation without disrupting any other content

Optimizes PDF images, often producing files smaller than the input file

If requested, deskews and/or cleans the image before performing OCR

Validates input and output files

Distributes work across all available CPU cores

Uses Tesseract OCR engine to recognize more than 100 languages

Scales properly to handle files with thousands of pages

Battle-tested on millions of PDFs

For details: please consult the documentation.


Also you should give yourself Credit somewhere in there. Right now it looks as if ocrmypdf were my creation. The store only displays my Name because I registered the snap.


You can See the listing here:
`https://snapcraft.io/ocrmypdf`

**Comment by jbarlow83** [comment]
Thanks, this is great!

Maybe there's a way you can make me owner of the snap to switch the name? I wouldn't mind if it more clearly identified as the maintainer of the snap but it does present it as if you were the project owner and that's probably not what either of us want, e.g. people might come to you with not-snap-related issues.

**Comment by alexanderlanganke** [comment]
Yes it can be done.

Look here:
https://forum.snapcraft.io/t/how-to-change-owner-of-a-snap/12329

**Comment by jbarlow83** [comment]
My snapcraft ID is shael7aerien.
(Sounds elvish. I think I used a random generator....)

**Comment by alexanderlanganke** [comment]
https://forum.snapcraft.io/t/please-transfer-ownership-of-ocrmypdf-snap/30584

Have put in the request
