### ISSUE TITLE
Add the possibility to OCR in external websites to have more accuracy

### ISSUE THREAD

**Issue by All3xJ** [ocrmypdf/OCRmyPDF#915]
**Is your feature request related to a problem? Please describe.**
Handwriting text OCF is not accurate at all, unluckily. Websites like google has very good accuracy. 

**Describe the solution you'd like**
It would be cool to add an option to upload and do the OCR in external websites like google, and take the results and paste it in the PDF as invisible layer text, like ocrmypdf already does.

**Describe alternatives you've considered**

**Example file**

Please provide an input file with no personal or confidential information. At your option you may [GPG-encrypt the file](https://github.com/jbarlow83/OCRmyPDF/wiki) for OCRmyPDF's author only.

Links to files hosted elsewhere are perfectly acceptable. You could also look in ``tests/resources`` and see if any of those files reproduce your issue.

**Additional context**

**Comment by jbarlow83** [comment]
Would be nice to have but I won't have time to implement it in the near future. Just too busy.

**Comment by All3xJ** [comment]
> Would be nice to have but I won't have time to implement it in the near future. Just too busy.

okok. do you know if there is a program that does what I asked?

**Comment by All3xJ** [comment]
also why isn't this https://github.com/ocrmypdf/OCRmyPDF/issues/595 closed but mine is?

**Comment by jbarlow83** [comment]
Both are pretty much duplicate issues to add cloud support plugins.
