### ISSUE TITLE
How to change the tesseractOCR Engine to another OcrEngine?

### ISSUE THREAD

**Issue by DAAworld** [ocrmypdf/OCRmyPDF#918]
**Is your feature request related to a problem? Please describe.**
I want to change the tesseractOCR Engine to our own OCR Engine.But I don't know where to start.
So I hope you can give me some guidance

**Comment by jbarlow83** [comment]
The current Tesseract engine is implemented as a default plugin to ocrmypdf so there is a well defined interface that you need to implement. The test suite uses the plugin interface to replace Tesseract with no-op OCR engine, caching, and simulating errors; so it demonstrates how Tesseract can be replaced. I think there are enough examples of what needs to be done.

See:
https://ocrmypdf.readthedocs.io/en/latest/plugins.html

Your plugin should operate on the assumption that it will be called in a child process, as explained above.

I'll close the ticket but feel free to comment if you have further questions.
