### ISSUE TITLE
SubprocessOutputError processing specific PDF

### ISSUE THREAD

**Issue by marcorighi** [ocrmypdf/OCRmyPDF#920]
**Describe the bug**
SubprocessOutputError

**To Reproduce**

```bash
ocrmypdf -lita spinoza_baruch_breve_trattato_su_dio_luomo_e_la.pdf spinoza_baruch_breve_trattato_su_dio_luomo_e_la.ocr.pdf
```

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.

**Example file**
file attached

[spinoza_baruch_breve_trattato_su_dio_luomo_e_la.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8079520/spinoza_baruch_breve_trattato_su_dio_luomo_e_la.pdf)/spinoza_baruch_breve_trattato_su_dio_luomo_e_la.pdf)

**Screenshots**

**System**
 
    OS:
    lsb_release -a |

LSB Version: n/a
Distributor ID: ManjaroLinux
Description: Manjaro Linux
Release: 21.2.3
Codename: Qonos

    OCRmyPDF Version:
    ocrmypdf --version

13.3.0

    How did you install ocrmypdf?
    yay -Suuyy
    yay -S ocrmypdf
    (AUR repository)

**Comment by jbarlow83** [comment]
You probably have pikepdf 5.0.0 which introduced this type of error.
Upgrading to ocrmypdf 13.4.0 and pikepdf 5.0.1 should resolve the issue. I confirmed it works fine in this setting.

I'll close the issue for now. Write back if upgrading does not fix it.
