### ISSUE TITLE
Output has overlapping texts

### ISSUE THREAD

**Issue by MKatereggaExigent** [ocrmypdf/OCRmyPDF#921]
**Describe the bug**
The ocrmypdf works fine, however, the output pdf has overlapping texts. What flag can I use to have a clean output without this overlap. `--clean` is not it?
<img width="840" alt="Screenshot 2022-02-17 at 13 34 16" src="https://user-images.githubusercontent.com/64529557/154473728-76691cd6-8fbc-4e0e-84a7-f545ab0f935c.png">

I have attached a sample output for clarity.

**Comment by jbarlow83** [comment]
I'm going to close this because you omitted almost all of the information that the issue template asked for. I can't begin to explore this issue without the courtesy of an input file, output file, and the command line you used to get from one to the other.
