### ISSUE TITLE
Test failures with pikepdf 5.0.0

### ISSUE THREAD

**Issue by dotlambda** [ocrmypdf/OCRmyPDF#922]
**Describe the bug**
After upgrading to pikepdf 4.5.0 or 5.0.0 some tests fail.

**To Reproduce**
Run pytest with an up-to-date version of pikepdf.

**Screenshots**
[log.txt](https://github.com/ocrmypdf/OCRmyPDF/files/8101494/log.txt)

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.10.2
 - OCRmyPDF version: 13.3.0

**Installation**
Nix: https://github.com/NixOS/nixpkgs/pull/158961

**Comment by jbarlow83** [comment]
Oof.

Fortunately this looks like a spurious warning with an easy fix.

**Comment by jbarlow83** [comment]
Should be fixed with ocrmypdf 13.4 and pikepdf 5.0.1
