### ISSUE TITLE
ImageMagick + OCRmyPDF

### ISSUE THREAD

**Issue by thejamesheard** [ocrmypdf/OCRmyPDF#923]
**Is your feature request related to a problem? Please describe.**
I'm a grad student and do most of my reading digitally. This has only become more important over the last two years with restricted travel, as archives have gotten much better at providing scans of material remotely. This also means that I receive a lot of poorly white balanced PDFs (usually a result of material quality rather than scan quality). The unpaper cleaning functionality in OCRmyPDF doesn't handle sepia or grey backgrounds well and I've just been living with the problem until the other day when I discovered [Fred's ImageMagick textcleaner script](http://www.fmwconcepts.com/imagemagick/textcleaner/index.php). He was kind enough to integrate PDF functionality and I was able to cobble together an automator script to work on multi-page PDFs. It works really well. I've attached before and after examples that were run on the default settings for the script (except for a density setting of 300 to maintain quality).

**Describe the solution you'd like**
Integrate Fred's textcleaner ImageMagick script into OCRmyPDF (similar to how unpaper has been integrated) to add better cleaning functionality.

**Describe alternatives you've considered**
The main issue is that the script I've put together is not that great. It creates a subfolder within the folder of the selected PDF, splits the PDF into pages, runs Fred's textcleaner script on each page, and then re-merges the files into a very large PDF which I then manually run through OCRmyPDF to reduce to a smaller size. It works, it's just not an elegant solution.

[BK_IN.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104866/BK_IN.pdf)
[BK_OUT.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104867/BK_OUT.pdf)
[CR_IN.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104868/CR_IN.pdf)
[CR_OUT.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104869/CR_OUT.pdf)
[REC_IN.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104870/REC_IN.pdf)
[REC_OUT.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8104871/REC_OUT.pdf)

**Comment by jbarlow83** [comment]
You can create a plugin to modify images while they are in the ocrmypdf pipeline
https://ocrmypdf.readthedocs.io/en/latest/plugins.html

You probably want `filter_page_image` specifically.
https://ocrmypdf.readthedocs.io/en/latest/plugins.html#ocrmypdf.pluginspec.filter_page_image

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
