### ISSUE TITLE
Process several files in a single invocation

### ISSUE THREAD

**Issue by rdiez** [ocrmypdf/OCRmyPDF#924]
OCRmyPDF has a rather high start-up cost. More than 300 ms have been observed just to print its version number, see this issue:

Allow reusing the Docker container
https://github.com/ocrmypdf/OCRmyPDF/issues/909

That time > 300 ms is without Docker, just locally running the script, and without doing anything else like querying Tesseract. It may be a Python issue, but I don't know much about Python yet.

Such high start-up costs unnecessarily waste time and electricity. It may not be important if you are OCR'ing, which is very slow, but OCRmyPDF can also be used to just recompress PDFs. If you have many small PDF files, start-up costs may become relevant in this scenario, especially due to this limitation:

Add command to skip all processing related to OCR
https://github.com/ocrmypdf/OCRmyPDF/issues/650

One way to overcome this issue is to allow OCRmyPDF to process several PDFs in a row (sequentially). Then you could use GNU Parallel to distribute the work and still avoid high start-up costs.

**Comment by jbarlow83** [comment]
If startup cost of Python is a concern, use a script to call ocrmypdf.ocr. I cannot improve the startup time of the Python interpreter.

**Comment by rdiez** [comment]
I do not know Python, but I grepped the sources and I guess you mean function 'ocr' in source file ocrmypdf/api.py

My guess is that function 'ocr' would still probe for Tesseract etc. My suggestion does not cover just the Python interpreter start-up time, but any other environment probing before starting the actual PDF processing.

Besides, using this method requires Python knowledge, not just any general scripting skills.

I am writing this comment only for future reference, in case anybody else happens to wonder about these matters later on.
