### ISSUE TITLE
Content overflow after ocr scan

### ISSUE THREAD

**Issue by arunzz** [ocrmypdf/OCRmyPDF#928]
After the ocr runs for a japanese pdf using japanese language settings, the content overflows to the border of the document if there are some drawings in the pdf. Any fix for this or workaround for this issue? Pls let know
![image](https://user-images.githubusercontent.com/21121989/157012816-4b2f26f3-1a05-40fc-a6a9-d6a3f7524f3a.png)

**Comment by jbarlow83** [comment]
Won't be fixable without the input PDF.

**Comment by arunzz** [comment]
This issue can be closed. The issue was at the source generating the pdf itself.

**Comment by arunzz** [comment]
This issue can be closed. The issue was at the source generating the pdf itself.
