### ISSUE TITLE
Release v13.4.2 to PyPi

### ISSUE THREAD

**Issue by pigmonkey** [ocrmypdf/OCRmyPDF#937]
Release v13.4.2 was committed last week in 04996ca but has yet to be pushed to PyPi.

**Comment by jbarlow83** [comment]
The test suite inexplicably fails on macOS now and I don't have time to investigate.
https://github.com/ocrmypdf/OCRmyPDF/actions/runs/2026583129

**Comment by jbarlow83** [comment]
To explain more clearly, I haven't actually tagged a v13.4.2 release. I did update the release notes to describe what ought to be in that release, but until the test suite passes I won't tag it. My build is setup to automatically deploy tagged releases to PyPI.

**Comment by jbarlow83** [comment]
Done!
