### ISSUE TITLE
import ocrmypdf

### ISSUE THREAD

**Issue by dmacobr** [ocrmypdf/OCRmyPDF#939]
im trying import ocrmydpdf in my python's script and it breakes when i call the ocr command

import ocrmypdf

if __name__ == '__main__': 
    ocrmypdf.ocr('xxx.pdf', 'aaa.pdf')

obs.: in my comand line it works perfectly
ocrmypdf --sidecar  out3.txt dec3.pdf output.pdf --force-ocr

how can i call in my python the ocrmypdf?

Windows 10

edit.:

import logging

import ocrmypdf

def DoOCR(filePath, fileName):
    print("Processing {}".format(fileName))
    fullPath = os.path.join(filePath, fileName)
    ocrmypdf.ocr(fullPath, fullPath, deskew=True, clean=True, language="pt")
    

if __name__ == '__main__':
    # Setup logging.
    logging.basicConfig(level=logging.DEBUG)
    #logging.basicConfig(level=logging.INFO)
    DoOCR("dec.pdf", "aa.pdf")

error:

module 'ocrmypdf' has no attribute 'ocr'

**Comment by jbarlow83** [comment]
Please fill out the issue template.
