### ISSUE TITLE
Skip rotating if first page is correct

### ISSUE THREAD

**Issue by DAThosting** [ocrmypdf/OCRmyPDF#943]
Hi,

I use the following command to rotate pages:
`ocrmypdf --l deu --skip-text --rotate-pages-threshold 1.5 --rotate-pages %%f C:\ocr\%%~nf_%datetimef%.pdf`

This works like a charme but take some minutes if the pdf is large.
To shrink the time it would be awesome if I could skip rotating pages if first page is correct, or first page have to be rotated and all other pages rotates the same.

**Comment by jbarlow83** [comment]
You can use Ghostscript to rewrite the PDF and use its algorithm to address page rotations
See the option `-dAutoRotatePages`.

ocrmypdf's current strategy is to rotate pages individually based on the recommendations of the OCR engine.
