### ISSUE TITLE
test_xml_metadata_preserved failures

### ISSUE THREAD

**Issue by spwhitton** [ocrmypdf/OCRmyPDF#945]
Thanks for making a release including a workaround for the Ghostscript bug.  I'm trying to update Debian but I'm seeing other test suite failures.  Any ideas?

    autopkgtest [14:14:17]: test test-suite: [-----------------------
    ============================= test session starts ==============================
    platform linux -- Python 3.10.4, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
    rootdir: /tmp/autopkgtest.fTy6Mn/build.Kho/src, configfile: pyproject.toml, testpaths: tests
    plugins: cov-3.0.0
    collected 318 items
    
    tests/test_acroform.py ..                                                [  0%]
    tests/test_api.py ....                                                   [  1%]
    tests/test_check_pdf.py .                                                [  2%]
    tests/test_completion.py x.                                              [  2%]
    tests/test_concurrency.py s                                              [  3%]
    tests/test_ghostscript.py .......                                        [  5%]
    tests/test_graft.py ..                                                   [  5%]
    tests/test_helpers.py .........s.                                        [  9%]
    tests/test_hocrtransform.py .s                                           [ 10%]
    tests/test_image_input.py .....x                                         [ 11%]
    tests/test_logging.py .                                                  [ 12%]
    tests/test_main.py ......................................ss........ss... [ 28%]
    ................s................                                        [ 39%]
    tests/test_metadata.py .....ssss....FFFF....                             [ 45%]
    tests/test_optimize.py ....sss...                                        [ 49%]
    tests/test_page_numbers.py ....................                          [ 55%]
    tests/test_pdfa.py ......                                                [ 57%]
    tests/test_pdfinfo.py ............F..                                    [ 61%]
    tests/test_pipeline.py ...............                                   [ 66%]
    tests/test_preprocessing.py ..x........................                  [ 75%]
    tests/test_quality.py .                                                  [ 75%]
    tests/test_rotation.py .ss...xssssssssssssssss..                         [ 83%]
    tests/test_stdio.py ..s.                                                 [ 84%]
    tests/test_tesseract.py ...................                              [ 90%]
    tests/test_unpaper.py .......                                            [ 92%]
    tests/test_userunit.py ...                                               [ 93%]
    tests/test_validation.py ....................                            [100%]
    
    =================================== FAILURES ===================================
    __________________ test_xml_metadata_preserved[graph.pdf-pdf] __________________
    
    test_file = 'graph.pdf', output_type = 'pdf'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_gr0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
    >           from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
    E           ModuleNotFoundError: No module named 'libxmp'
    
    tests/test_metadata.py:189: ModuleNotFoundError
    
    During handling of the above exception, another exception occurred:
    
    test_file = 'graph.pdf', output_type = 'pdf'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_gr0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
                from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
            except Exception:  # pylint: disable=broad-except
    >           pytest.skip(reason="libxmp not available or libexempi3 not installed")
    E           TypeError: skip() got an unexpected keyword argument 'reason'
    
    tests/test_metadata.py:191: TypeError
    --------------------------- Captured stderr teardown ---------------------------
    PDF/A conversion: 100%|██████████| 1/1 [00:00<00:00, 21.54page/s]
    _________________ test_xml_metadata_preserved[graph.pdf-pdfa] __________________
    
    test_file = 'graph.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_gr1/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
    >           from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
    E           ModuleNotFoundError: No module named 'libxmp'
    
    tests/test_metadata.py:189: ModuleNotFoundError
    
    During handling of the above exception, another exception occurred:
    
    test_file = 'graph.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_gr1/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
                from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
            except Exception:  # pylint: disable=broad-except
    >           pytest.skip(reason="libxmp not available or libexempi3 not installed")
    E           TypeError: skip() got an unexpected keyword argument 'reason'
    
    tests/test_metadata.py:191: TypeError
    ________________ test_xml_metadata_preserved[overlay.pdf-pdfa] _________________
    
    test_file = 'overlay.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_ov0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
    >           from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
    E           ModuleNotFoundError: No module named 'libxmp'
    
    tests/test_metadata.py:189: ModuleNotFoundError
    
    During handling of the above exception, another exception occurred:
    
    test_file = 'overlay.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_ov0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
                from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
            except Exception:  # pylint: disable=broad-except
    >           pytest.skip(reason="libxmp not available or libexempi3 not installed")
    E           TypeError: skip() got an unexpected keyword argument 'reason'
    
    tests/test_metadata.py:191: TypeError
    _________________ test_xml_metadata_preserved[3small.pdf-pdfa] _________________
    
    test_file = '3small.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_3s0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
    >           from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
    E           ModuleNotFoundError: No module named 'libxmp'
    
    tests/test_metadata.py:189: ModuleNotFoundError
    
    During handling of the above exception, another exception occurred:
    
    test_file = '3small.pdf', output_type = 'pdfa'
    resources = PosixPath('/tmp/autopkgtest.fTy6Mn/build.Kho/src/tests/resources')
    outpdf = PosixPath('/tmp/pytest-of-spwhitton/pytest-0/test_xml_metadata_preserved_3s0/out.pdf')
    
        @pytest.mark.parametrize(
            'test_file,output_type',
            [
                ('graph.pdf', 'pdf'),  # PDF with full metadata
                ('graph.pdf', 'pdfa'),  # PDF/A with full metadata
                ('overlay.pdf', 'pdfa'),  # /Title()
                ('3small.pdf', 'pdfa'),
            ],
        )
        def test_xml_metadata_preserved(test_file, output_type, resources, outpdf):
            input_file = resources / test_file
        
            try:
                from libxmp.utils import file_to_dict  # pylint: disable=import-outside-toplevel
            except Exception:  # pylint: disable=broad-except
    >           pytest.skip(reason="libxmp not available or libexempi3 not installed")
    E           TypeError: skip() got an unexpected keyword argument 'reason'
    
    tests/test_metadata.py:191: TypeError
    _______________________________ test_stack_abuse _______________________________
    
        def test_stack_abuse():
            p = pikepdf.Pdf.new()
        
            stream = pikepdf.Stream(p, b'q ' * 35)
            with pytest.warns(UserWarning, match="overflowed"):
                pdfinfo.info._interpret_contents(stream)
        
            stream = pikepdf.Stream(p, b'q Q Q Q Q')
            with pytest.warns(UserWarning, match="underflowed") as record:
                pdfinfo.info._interpret_contents(stream)
        
            stream = pikepdf.Stream(p, b'q ' * 135)
    >       with pytest.warns():
    E       TypeError: warns() missing 1 required positional argument: 'expected_warning'
    
    tests/test_pdfinfo.py:184: TypeError
    =============================== warnings summary ===============================
    <frozen importlib._bootstrap>:283
      <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
    
    -- Docs: https://docs.pytest.org/en/stable/warnings.html
    =========================== short test summary info ============================
    FAILED tests/test_metadata.py::test_xml_metadata_preserved[graph.pdf-pdf] - T...
    FAILED tests/test_metadata.py::test_xml_metadata_preserved[graph.pdf-pdfa] - ...
    FAILED tests/test_metadata.py::test_xml_metadata_preserved[overlay.pdf-pdfa]
    FAILED tests/test_metadata.py::test_xml_metadata_preserved[3small.pdf-pdfa]
    FAILED tests/test_pdfinfo.py::test_stack_abuse - TypeError: warns() missing 1...
    = 5 failed, 275 passed, 34 skipped, 4 xfailed, 1 warning in 209.26s (0:03:29) ==
    autopkgtest [14:17:47]: test test-suite: -----------------------]
    autopkgtest [14:17:47]: test test-suite:  - - - - - - - - - - results - - - - - - - - - -
    test-suite           FAIL non-zero exit status 1
    autopkgtest [14:17:47]: @@@@@@@@@@@@@@@@@@@@ summary
    test-suite           FAIL non-zero exit status 1

**Comment by jbarlow83** [comment]
13.4.3 should address the `TypeError: skip()...` exception and resolve the issue.

 `ModuleNotFoundError: No module named 'libxmp'` is handling an expected error that just indicates Debian is not installing an optional, for testing only package. I don't think it's necessary for Debian or any other downstream to install this.

**Comment by spwhitton** [comment]
Thanks, uploaded!

On Thu 14 Apr 2022 at 08:49PM -07, jbarlow83 wrote:

> 13.4.3 should address the `TypeError: skip()...` exception and resolve the issue.
>
>  `ModuleNotFoundError: No module named 'libxmp'` is handling an expected error that just indicates Debian is not installing an optional, for testing only package. I don't think it's necessary for Debian or any other downstream to install this.

-- 
Sean Whitton
