### ISSUE TITLE
Save text to input file (in-place update)

### ISSUE THREAD

**Issue by githubkusi** [ocrmypdf/OCRmyPDF#946]
### Feature request
Often a scanned pdf already has a proper filename. I'd like to add the text detected by OCR to the existing input file without the need of specifying again a new output name.

### Current situation

    ocrmypdf myscan.pdf myscan.pdf

### Solution 1
If parameter ```--in-place``` is specified, no output parameter is needed

    ocrmypdf --in-place myscan.pdf

### Solution 2
Automatic in-place update if the output name is missing

    ocrmypdf myscan.pdf

**Comment by jbarlow83** [comment]
Why does `ocrmypdf x.pdf x.pdf` not work for you?

I should mention ocrmypdf does not do (rude IMHO) things like overwrite the destination with an empty file on failure. The destination is only modified on success.
