### ISSUE TITLE
OCRmyPDF does not include text layer when producing PDF/A-2B output

### ISSUE THREAD

**Issue by pwoehrer** [ocrmypdf/OCRmyPDF#947]
When using OCRmyPDF without specifying an output format it produces a valid PDF/A-2B file that does not include any text.
Checking the temporary files it turns out, the last file to contain the text layer is "graft_layers.pdf". There is no text layer in "metafix.pdf", "pdfa.pdf" or any of the subsequent temporary optimization files.

The final file has the text layer when OCRmyPDF is run with the "--output-type pdf" switch.

**To Reproduce**
ocrmypdf -l deu --title "Texttitel" --clean -i input.pdf output.pdf

**Expected behavior**
The output file should be PDF/A with text layer.

 - OS: Manjaro Linux 21.2.6
 - Python version: 3.10.4
 - OCRmyPDF version: 13.2.0

**Installation**
Manjaro package manager pacman, package name: ocrmypdf

**Comment by jbarlow83** [comment]
You probably have Ghostscript 9.56 which deletes ocr layers. Upgrade to latest ocrmypdf which includes a workaround.

**Comment by pwoehrer** [comment]
@jbarlow83 : Yes, you are right, I do run Ghostscript 9.56.
Thank you for the tip.

Unfortunately OCRmyPDF is plagued by third party issues for more than a month now and by this has turned into being almost inusable.
