### ISSUE TITLE
Build issues with derivative docker file due to debian bookworm using a new syscall

### ISSUE THREAD

**Issue by sihil** [ocrmypdf/OCRmyPDF#949]
**Describe the bug**
I'm having some difficulties with installing packages using apt-get in a Dockerfile that uses `jbarlow83/ocrmypdf` as a starting point. It works on my machine (Docker Desktop on macOS) and a colleagues machine (Ubuntu 20.04) but fails on our CI systems (Amazon Linux 2.1) . We get a lot of errors about permission denied to public keys which I think I've traced to bookworm using a new syscall which isn't supported on the 4.14 machine. 

See https://github.com/concourse/concourse/issues/7905 and https://github.com/concourse/concourse/issues/6044 for some very similar behaviour.

I would ask that you change the verison of Debian you are building on to be `stable` (currently bullseye) rather than `testing` (bookworm).

**To Reproduce**
Try and build a derivative docker from from `jbarlow83/ocrmypdf` or `debian/bookworm-slim` on a sufficiently old Linux kernel which contains `RUN apt-get update`.

e.g.
```
FROM debian:bookworm-slim

RUN apt-get update
```

result: 
```
[ec2-user@ip-10-0-4-11 ~]$ docker build .
Sending build context to Docker daemon  50.18kB
Step 1/2 : FROM debian:bookworm-slim
 ---> 9548e22a990d
Step 2/2 : RUN apt-get update
 ---> Running in 0ebc53d595ca
Get:1 http://deb.debian.org/debian bookworm InRelease [130 kB]
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [35.6 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [36.8 kB]
Err:1 http://deb.debian.org/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Err:2 http://security.debian.org/debian-security bookworm-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 112695A0E562B32A NO_PUBKEY 54404762BBB6E853
Err:3 http://deb.debian.org/debian bookworm-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Reading package lists...
```

**Expected behavior**
It's possible to derive a docker image from `jbarlow83/ocrmypdf` and add packages to it on all platforms.

Note that changing the above Dockerfile to the following debian version makes everything happy again.
```
FROM debian:bullseye-slim

RUN apt-get update
```

**System (please complete the following information):**
 - OS: Amazon Linux 2.1
 - Python version: n/a
 - OCRmyPDF version: n/a

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
Docker

**Additional context**

**Comment by jbarlow83** [comment]
I think I'll switch to Ubuntu 22.04 now that it's out and "stable", and I was previously using Ubuntu.
Of course, you may still see the syscall issue.

**Comment by sihil** [comment]
Thanks for the heads up. As you surmise, Ubuntu 22.04 exhibits exactly the same syscall issue as bookworm. The future is coming :)
