### ISSUE TITLE
Public API to use other OCR results to create PDF/A files

### ISSUE THREAD

**Issue by angel-langdon** [ocrmypdf/OCRmyPDF#954]
**Is your feature request related to a problem? Please describe.**

Now we can only use tesseract OCR to create PDF/A files. I think it would be very useful if `ocrmypdf` had a public API to pass other OCR results such as `textract`, `azure`, `google`, etc...

**Describe the solution you'd like**

There could be a public API function that receives a PDF path and any OCR text boxes in a specified format.

Something like this:

```python
boxes = [
    [ {"left": 10, "top": 10, "width": 20, "height":20, text:"Hello, world!"}], # page 1 boxes
    [ {"left": 10, "top": 10, "width": 20, "height":20, text:"Hello, world!"}], # page 2 boxes
    # other page boxes
]
pdf_path = "mypdf.pdf"
dest_path = "searchable.pdf"
create_pdfa_file(pdf_path, dest_path, boxes)
```

**Describe alternatives you've considered**
We could also implement different pipelines for each OCR, one for `textract`, another for `azure`, etc...

**Additional context**
If `ocrmypdf` could have a public API in order to use different OCRs I think it would be very very useful for lots of users (especially software companies) and It will bring lots of value to this amazing library

**Comment by jbarlow83** [comment]
You can currently use the plugin interface to create a new OCR engine. The test suite uses this internally to bypass OCR and test OCR failures.
https://ocrmypdf.readthedocs.io/en/latest/plugins.html#ocr-engine

While it's not part of the public API, you can also call `ocrmypdf._exec.ghostscript.generate_pdfa` to create a PDF/A.

**Comment by jbarlow83** [comment]
I'll assume what's already available is sufficient but if you have further thoughts please elaborate here or open a new more specific issue.

**Comment by shreevatsa** [comment]
Related older issue: https://github.com/ocrmypdf/OCRmyPDF/issues/36
