### ISSUE TITLE
Setting Overprint Mode to 1  not permitted in PDF/A-2, overprint mode not set

### ISSUE THREAD

**Issue by maikonayres** [ocrmypdf/OCRmyPDF#955]
co related in - https://github.com/ocrmypdf/OCRmyPDF/issues/107

I use tesseract 5.1.0 to generate pdf in separate process

input image => https://github.com/AlexanderP/tesseract-appimage/blob/master/Apache.tif
output image => [output0.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8644039/output0.pdf)

tesseract comand
tesseract input.tif output --oem 1 --psm 11 -l por --dpi 300 pdf

tesseract bin
https://github.com/AlexanderP/tesseract-appimage

when try Ghostscript in output i see this

CMD gs -dPDFACompatibilityPolicy=1 -dPDFA=2 -dBATCH -dNOPAUSE -sColorConversionStrategy=RGB -sDEVICE=pdfwrite -sOutputFile=output.pdf input.pdf

```bash
$ gs -dPDFACompatibilityPolicy=1 -dPDFA=2 -dBATCH -dNOPAUSE -sColorConversionStrategy=RGB -sDEVICE=pdfwrite -sOutputFile=output.pdf input.pdf
GPL Ghostscript 9.50 (2019-10-15)
Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GPL Ghostscript 9.50: UTF16BE text string detected in DOCINFO cannot be represented in XMP for PDF/A1, discarding DOCINFO
Processing pages 1 through 4.
Page 1
GPL Ghostscript 9.50: Setting Overprint Mode to 1
 not permitted in PDF/A-2, overprint mode not set

Page 2
Page 3
Page 4

```

**Comment by jbarlow83** [comment]
Closing because:
- Issue template deleted
- No ocrmypdf version
- No test file provided
- No report if this is a warning or error
