### ISSUE TITLE
OCRmyPDF conflicts with pdfminer.six's latest version v20220506

### ISSUE THREAD

**Issue by zeshuaro** [ocrmypdf/OCRmyPDF#956]
**Describe the bug**
pdfminer.six has released a new version v20220506 but OCRmyPDF doesn't mark it as compitable.

**To Reproduce**
```
pip install OCRmyPDF==13.4.3
pip install pdfminer.six==v20220506
```

**Expected behavior**
OCRmyPDF should support pdfminer.six's latest version v20220506

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Any OS
 - Python version: Any Python version
 - OCRmyPDF version: 13.4.3

**Installation**
pip

**Additional context**
N/A

**Comment by jbarlow83** [comment]
Fixed in 1ca327e1
