### ISSUE TITLE
ERROR] Ghostscript rasterizing failed - [ocrmypdf._exec.ghostscript] Error: /ioerror in --showpage--

### ISSUE THREAD

**Issue by upuldi** [ocrmypdf/OCRmyPDF#962]
**Describe the bug**
The following error occurred. This is related to the closed defect https://github.com/ocrmypdf/OCRmyPDF/issues/952
Herewith I am providing the test file.

**To Reproduce**
Use the following PDF. - https://drive.google.com/file/d/16mHk7_HICNOpJk9JoHot5-NiEnLaGTKf/view?usp=sharing
I have used the PDF with PaperlessNGX

**System**
 - OS: Unraid, Paperless NGX
 - OCRmyPDF Version: 13.4.3

**Error Stacktrace**

today at 13:44:5313:44:53 [Q] INFO Process-1:5 processing [220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf]
today at 13:44:53[2022-05-14 13:44:53,536] [INFO] [paperless.consumer] Consuming 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf
today at 13:45:11[2022-05-14 13:45:11,252] [ERROR] [ocrmypdf._exec.ghostscript] Error: /ioerror in --showpage--
today at 13:45:11Operand stack:
today at 13:45:11   1   true
today at 13:45:11Execution stack:
today at 13:45:11   %interp_exit   .runexec2   --nostringval--   showpage   --nostringval--   2   %stopped_push   --nostringval--   showpage   showpage   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1977   1   3   %oparray_pop   1978   1   3   %oparray_pop   showpage   showpage   3   1   2   showpage   %for_pos_int_continue   1981   1   7   %oparray_pop   showpage   showpage   1840   0   9   %oparray_pop   showpage   showpage
today at 13:45:11Dictionary stack:
today at 13:45:11   --dict:738/1123(ro)(G)--   --dict:1/20(G)--   --dict:80/200(L)--   --dict:80/200(L)--   --dict:133/256(ro)(G)--   --dict:320/325(ro)(G)--   --dict:33/64(L)--   --dict:6/9(L)--   --dict:6/20(L)--
today at 13:45:11Current allocation mode is local
today at 13:45:11GPL Ghostscript 9.53.3: Unrecoverable error, exit code 1
today at 13:45:11
today at 13:45:17[2022-05-14 13:45:17,716] [ERROR] [paperless.consumer] Error while consuming document 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: SubprocessOutputError: Ghostscript rasterizing failed
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf
today at 13:45:17    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
today at 13:45:17    proc = subprocess_run(args, env=env, **kwargs)
today at 13:45:17  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
today at 13:45:17    raise CalledProcessError(retcode, process.args,
today at 13:45:17subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=2', '-dLastPage=2', '-r4973.684211x4973.684211', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.syvt4fqv/origin.pdf']' returned non-zero exit status 1.
today at 13:45:17
today at 13:45:17During handling of the above exception, another exception occurred:
today at 13:45:17
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
today at 13:45:17    ocrmypdf.ocr(**args)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
today at 13:45:17    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
today at 13:45:17    exec_concurrent(context, executor)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
today at 13:45:17    executor(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
today at 13:45:17    self._execute(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
today at 13:45:17    result = future.result()
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
today at 13:45:17    return self.__get_result()
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
today at 13:45:17    raise self._exception
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
today at 13:45:17    result = self.fn(*self.args, **self.kwargs)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync
today at 13:45:17    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview
today at 13:45:17    page_context.plugin_manager.hook.rasterize_pdf_page(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
today at 13:45:17    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
today at 13:45:17    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
today at 13:45:17    return outcome.get_result()
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
today at 13:45:17    raise ex[1].with_traceback(ex[2])
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
today at 13:45:17    res = hook_impl.function(*args)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page
today at 13:45:17    ghostscript.rasterize_pdf(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf
today at 13:45:17    raise SubprocessOutputError('Ghostscript rasterizing failed')
today at 13:45:17ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed
today at 13:45:17
today at 13:45:17During handling of the above exception, another exception occurred:
today at 13:45:17
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
today at 13:45:17    document_parser.parse(self.path, mime_type, self.filename)
today at 13:45:17  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
today at 13:45:17    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
today at 13:45:17documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed
today at 13:45:1713:45:17 [Q] INFO Process-1:5 stopped doing work
today at 13:45:1713:45:17 [Q] ERROR Failed [220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf] - 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: Error while consuming document 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: SubprocessOutputError: Ghostscript rasterizing failed : Traceback (most recent call last):
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf
today at 13:45:17    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
today at 13:45:17    proc = subprocess_run(args, env=env, **kwargs)
today at 13:45:17  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
today at 13:45:17    raise CalledProcessError(retcode, process.args,
today at 13:45:17subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=2', '-dLastPage=2', '-r4973.684211x4973.684211', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.syvt4fqv/origin.pdf']' returned non-zero exit status 1.
today at 13:45:17
today at 13:45:17During handling of the above exception, another exception occurred:
today at 13:45:17
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
today at 13:45:17    ocrmypdf.ocr(**args)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
today at 13:45:17    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
today at 13:45:17    exec_concurrent(context, executor)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
today at 13:45:17    executor(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
today at 13:45:17    self._execute(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
today at 13:45:17    result = future.result()
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
today at 13:45:17    return self.__get_result()
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
today at 13:45:17    raise self._exception
today at 13:45:17  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
today at 13:45:17    result = self.fn(*self.args, **self.kwargs)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync
today at 13:45:17    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview
today at 13:45:17    page_context.plugin_manager.hook.rasterize_pdf_page(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
today at 13:45:17    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
today at 13:45:17    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
today at 13:45:17    return outcome.get_result()
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
today at 13:45:17    raise ex[1].with_traceback(ex[2])
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
today at 13:45:17    res = hook_impl.function(*args)
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page
today at 13:45:17    ghostscript.rasterize_pdf(
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf
today at 13:45:17    raise SubprocessOutputError('Ghostscript rasterizing failed')
today at 13:45:17ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed
today at 13:45:17
today at 13:45:17During handling of the above exception, another exception occurred:
today at 13:45:17
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 275, in main_wrap
today at 13:45:17    raise exc_info[1]
today at 13:45:17  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
today at 13:45:17    document_parser.parse(self.path, mime_type, self.filename)
today at 13:45:17  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
today at 13:45:17    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
today at 13:45:17documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed
today at 13:45:17
today at 13:45:17During handling of the above exception, another exception occurred:
today at 13:45:17
today at 13:45:17Traceback (most recent call last):
today at 13:45:17  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
today at 13:45:17    res = f(*task["args"], **task["kwargs"])
today at 13:45:17  File "/usr/src/paperless/src/documents/tasks.py", line 298, in consume_file
today at 13:45:17    document = Consumer().try_consume_file(
today at 13:45:17  File "/usr/src/paperless/src/documents/consumer.py", line 280, in try_consume_file
today at 13:45:17    self._fail(
today at 13:45:17  File "/usr/src/paperless/src/documents/consumer.py", line 81, in _fail
today at 13:45:17    raise ConsumerError(f"{self.filename}: {log_message or message}")
today at 13:45:17documents.consumer.ConsumerError: 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: Error while consuming document 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: SubprocessOutputError: Ghostscript rasterizing failed

**Comment by jbarlow83** [comment]
paperless's ocrmypdf tried to run the following command:

```
gs -dQUIET -dSAFER -dBATCH -dNOPAUSE -dInterpolateControl=-1 -sDEVICE=jpeggray -dFirstPage=2 -dLastPage=2 -r4973.684211x4973.684211 -o output.jpg -sstdout=%stderr -dAutoRotatePages=/None -f /path/to/your/input.pdf
```

paperless does not seem to be using ocrmypdf 13.4.3. The current version of ocrmypdf works fine on your file, and uses different arguments when it calls ghostscript (`'-sDEVICE=png16m', '-dFirstPage=2', '-dLastPage=2', '-r949.189692x949.189692',`). 

paperless probably has a virtual environment or some sort of container set up and is using its own, older version of ocrmypdf. You will need to find a way to upgrade. I can only help if you can give me a command line that causes problems for the latest version of ocrmypdf.

(According to the stack trace you have ghostscript 9.53.1. I tested with ghostscript 9.56.0 and the issue was not reproducible. I do not know if ghostscript 9.53.1 has issues or not. Upgrading ghostscript is another option.)

**Comment by upuldi** [comment]
I have raised a defect on the paperless board. Hopefully, this will be fixed. I just checked the version of the ocrmypdf, it looks like they are using the same version 13.4.3. Probably the values passed to it should change. Thank you.
