### ISSUE TITLE
Compression artifacts

### ISSUE THREAD

**Issue by cloakedch** [ocrmypdf/OCRmyPDF#964]
I am using ocrmypdf 13.4.4.post1+g603da520 like so:
`ocrmypdf --optimize 0 input.pdf output.pdf`

The OCR works fine, but the image quality of the output PDF is a lot worse than the quality of the input PDF.
I tried:
- Installing the JBIG2 encoder as documented here: https://ocrmypdf.readthedocs.io/en/latest/jbig2.html
- Using unpaper flags such as `--clean` and `--clean-final`
- Specifying image DPI such as `--image-dpi 300` (for testing purposes only)

An example PDF i use is 1.7MB in size. When running `ocrmypdf`, it shrinks to 0.6MB.
Below is an illustration of the problem. The upper text line is from the input PDF i use. The lower text line is from the output PDF. There are some heavy (compression?) artifacts around the text.

![image](https://user-images.githubusercontent.com/32439069/168609595-00907e6e-2c96-47ba-8447-6363d80e5e2c.png)

What am I missing? Ideally I would like the images to remain untouched in the output PDF.

**Comment by jbarlow83** [comment]
You can try `--output-type pdf` to turn off PDF/A conversion in case Ghostscript is responsible.

**Comment by cloakedch** [comment]
That did the trick, thank you!
The following two options worked:
- `--output-type pdf`
- ` --pdfa-image-compression lossless`

**Comment by ByteSizedMarius** [comment]
I had the same issue. Setting the output-type to pdf fixed it. Maybe a note about this behavior could be added here? https://ocrmypdf.readthedocs.io/en/latest/optimizer.html
