### ISSUE TITLE
LookupError: setuptools-scm was unable to detect version for 

### ISSUE THREAD

**Issue by AIYA-ai** [ocrmypdf/OCRmyPDF#965]
**Describe the bug**
When this problem happens, what should I do

**To Reproduce**
when I run setup.py will happen this problem

**Screenshots**
![image](https://user-images.githubusercontent.com/59281637/168775265-96182224-164b-4081-bf7e-3a3a9efc502f.png)

**System (please complete the following information):**
 - OS:windows11
 - Python version:3.8
 - OCRmyPDF version:13.4.4

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?use pip

**Comment by jbarlow83** [comment]
The error message in the screenshot explains what is wrong and what you need to do. 

Don't run setup.py directly. Use pip to install.

**Comment by AIYA-ai** [comment]
Thank you very much for your answer
