### ISSUE TITLE
How can I programmatically get the work folder?

### ISSUE THREAD

**Issue by lotif** [ocrmypdf/OCRmyPDF#975]
This is more like a question, so let me know if this is the best place to ask it.

**Is your feature request related to a problem? Please describe.**
I want to programmatically have access to the temporary work folder after I run `ocr()`. I am aware I can use the `keep_temporary_files` option but the only way I can think of programmatically access the work folder path is through parsing the `stderr` which seems like a very fragile solution. Let me know if there is a better way to do this.

The reason I need this is I want to access the hOCR file produced by tesseract, and since I am running many `ocr()` calls in a loop, it would be good to have a reliable way to get the path for the work folder so I can get have access to that file in my code. 

**Describe the solution you'd like**
Maybe save the work folder into a variable that can be accessed right after I run `ocr()`? I am not super advanced in python so I don't know exactly which solution would be best.

**Describe alternatives you've considered**
Mentioned above, I am parsing the stderr output which seems very fragile.

**Comment by jbarlow83** [comment]
You could create a plugin similar to the built in Tesseract OCR engine plugin that sets aside the hocr files as you require.

**Comment by lotif** [comment]
Ok, thanks for the idea! That worked on my end here.
