### ISSUE TITLE
remove unnecessary --sidecar argument constraint with --output-type=none

### ISSUE THREAD

**Issue by damonhart** [ocrmypdf/OCRmyPDF#983]
The addition of --output-type=none (referenced in https://github.com/ocrmypdf/OCRmyPDF/issues/787) as a valid argument is helpful to suppress unwanted generation of an output PDF, but it appears that the restriction on --sidecar argument naming is still enforced even if ocrmypdf is never going to open a file for output. For instance, one intuitive command line to quickly see the OCR quality of a given PDF results in an error:

[1851]$ ocrmypdf test.pdf - --output-type none --sidecar -
--sidecar file must be different from the input and output files

Admittedly, it's easy enough to designate a file for --sidecar output and then view that file, but allowing the above command line would be marginally more convenient. Trying another tack of simply supplying a dummy file name for output file also runs into an error:

[1853]$ ocrmypdf test.pdf dummy.pdf  --output-type none --sidecar -
Since you specified `--output-type none`, the output file dummy.pdf cannot be produced. Set the output file to `-` to suppress this message.

**Comment by jbarlow83** [comment]
I see what you're saying, but the result is that some command line options sometimes require a parameter, and sometimes don't, depending on other arguments. That's far from ideal. I don't believe that `argparse` allows this kind of interaction.

We also have plugins that can interact with the command line and install their arguments, and shell scripts completions that would get more complicated.

I think it would be better to use a shell alias. For bash: 
```bash
alias ocrmypdf-text=ocrmypdf --output-type=none --sidecar=- "$1" /dev/null
ocrmypdf-text test.pdf
```
