### ISSUE TITLE
unexpected ocrmypdf behavior on PDF file consisting (mostly) of native text, duplicate text present in output

### ISSUE THREAD

**Issue by damonhart** [ocrmypdf/OCRmyPDF#984]
Running ocrmypdf on a PDF file containing predominantly native text and minimal graphics does not abort with PriorOcrFoundError, but rather proceeds to apply OCR, apparently to the whole document, and includes both the original text and OCR results in the output file. This behavior is not altered by supplying an explicit --skip-text argument.

System is Linux Debian 11.3 with stock distribution packages installed for ocrmypdf and dependencies.
```
[1891]$ cat /etc/debian_version  
11.3

[1892]$ ocrmypdf --version 
13.4.6

[705]# apt list tesseract-ocr ghostscript 
Listing... Done 
ghostscript/stable,stable-security,now 9.53.3~dfsg-7+deb11u2 amd64 [installed,automatic] 
tesseract-ocr/stable,now 4.1.1-2.1 amd64 [installed]
```
Background: In order to maximize the amount of text available for text indexing and searching system, a Python cron job regularly traverses server file systems, making ocrmypdf API calls to apply OCR to PDF files found without accessible text.

In PDF files composed exclusively of native text, the API call to ocrmypdf triggers an exception (ocrmypdf.exceptions.PriorOcrFoundError). 

Demonstrating with the equivalent command line operations on “all_text.pdf”:
```
[1893]$ ocrmypdf all_text.pdf all_text_output.pdf 
Scanning contents: 100%|██████████ 1/1 [00:00<00:00, 153.25page/s] 
OCR:   0%|                                                                                                                                                                               | 0.0/1.0 [00:00<?, ?page/s] 
PriorOcrFoundError: page already has text! - aborting
.
.
.
```
Problem: When encountering a file that’s almost all text with a few graphical elements (e.g. firm logo, bar chart), ocrmypdf proceeds to apply OCR to the whole document (the logo *is* repeated on each page, if that matters) and the output PDF appears to include both the original text and the OCR results.

The expected/desired result is to skip such a file altogether since the original file is preferable for our indexing purposes. This result seemed to be the case with ocrmypdf earlier (at least before an update to 12.7.2, see below). Failing that, it would be preferred to retain only the original text rather than include OCR results in the output file. The documentation suggests that –skip-text should trigger retaining the original text for pages with substantial native text present, but that isn’t the case (regardless of –skip-text presence, ocrmypdf generates identical sidecar file and text extracted from output PDFs is also identical).

Demonstrating with the equivalent command line operations on “almost_all_text.pdf”:
```
[1894]$ ocrmypdf  --sidecar almost_all_text.txt almost_all_text.pdf almost_all_text_output.pdf 
Scanning contents: 100%|██████████████████| 6/6 [00:00<00:00, 14.02page/s] 
Start processing 6 pages concurrently 
OCR: 100%|████████████████| 6.0/6.0 [00:18<00:00,  3.11s/page] 
Postprocessing... 
PDF/A conversion: 100%|██████████████| 6/6 [00:01<00:00,  3.71page/s] 
Recompressing JPEGs: 0image [00:00, ?image/s] 
Deflating JPEGs: 0image [00:00, ?image/s] 
JBIG2: 0item [00:00, ?item/s] 
Optimize ratio: 1.00 savings: 0.1% 
Output file is a PDF/A-2B (as expected)

[1896]$ ocrmypdf --skip-text --sidecar almost_all_text_skip.txt almost_all_text.pdf almost_all_text_output_skip.pdf 
Scanning contents: 100%|██████████████| 6/6 [00:00<00:00, 14.56page/s] 
Start processing 6 pages concurrently 
OCR: 100%|█████████████████████| 6.0/6.0 [00:20<00:00,  3.39s/page] 
Postprocessing... 
PDF/A conversion: 100%|███████████████████| 6/6 [00:01<00:00,  3.64page/s] 
Recompressing JPEGs: 0image [00:00, ?image/s] 
Deflating JPEGs: 0image [00:00, ?image/s] 
JBIG2: 0item [00:00, ?item/s] 
Optimize ratio: 1.00 savings: 0.1% 
Output file is a PDF/A-2B (as expected)
```
Sidecar files are identical:
```
[1898]$ diff -s almost_all_text.txt almost_all_text_skip.txt  
Files almost_all_text.txt and almost_all_text_skip.txt are identical
```
Extracted text from output files is identical:
```
[1951]$ pdftotext -layout almost_all_text_output.pdf  
[1952]$ pdftotext -layout almost_all_text_output_skip.pdf 

[1955]$ diff -s almost_all_text_output.txt almost_all_text_output_skip.txt 
Files almost_all_text_output.txt and almost_all_text_output_skip.txt are identical
```
Demonstrate a sample phrase appears once in the sidecar file and twice in the output file:
```
[1958]$ grep neither almost_all_text.txt       
neither endorses nor recommends any particular Advisor or its investment 

[1959]$ grep neither almost_all_text_output.txt  
neither endorses 
neither      endorses nor     nor recommends
```
Files referenced above are attached in an encrypted zip file. (Note that almost_all_text.pdf is a financial statement, but sampled from a number of years ago for an account since closed, so there’s no concern for confidentiality or identity compromise.)

Release note for 2.112 v7.0.0 suggest that a heuristic helps prevent “[s]mall amounts of text in the margins of a page, such as watermarks, page numbers, or digital stamps” from inhibiting the page being OCRed when --skip-text is issued, but the text on all pages (save for the last) of almost_all_text.pdf is substantial and presumably wouldn’t fit the heuristic.

From reviewing historical files, it looks like this behavior (ocrmypdf API not raising PriorOcrFoundError on a file that’s almost all native text) may date to a different computer’s ocrmypdf upgrade from 11.5.0 to 12.7.2 (as part of a Fedora 33 → Fedora 35 update). Files similar to almost_all_text.pdf processed with 12.7.2 after that update appear not to abort but rather generate an output file including the OCR text layer in place of the original native text.

The duplicate text issue has been observed only with command line 13.4.6 running on Debian 11.3 as demonstrated above.
```
[ocrmypdf_sample_PDFs.zip.gpg.zip](https://github.com/ocrmypdf/OCRmyPDF/files/9058179/ocrmypdf_sample_PDFs.zip.gpg.zip)
```

**Comment by damonhart** [comment]
Testing from yet another machine indicates the expected/desired behavior was present in 11.7.3:

[10140]$ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)

[10141]$ ocrmypdf --version
11.7.3

[10142]$ ocrmypdf almost_all_text.pdf almost_all_text_output.pdf
Scanning contents: 100%|█████████████████| 6/6 [00:00<00:00,  8.30page/s]
Start processing 6 pages concurrently
OCR:   0%|                                                                                                                                              | 0.0/6.0 [00:00<?, ?page/s]
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force OCR;  see also help for the arguments --skip-text and --redo-ocr

Note also, for this version,  that --skip-text triggers an output file to be generated, but that runtime diagnostic messages suggest the original text is being retained:

xw22:/tmp/ocrmypdf2[10143]$ ocrmypdf --skip-text almost_all_text.pdf almost_all_text_output.pdf
Scanning contents: 100%|█████████████████████████| 6/6 [00:00<00:00,  8.22page/s]
Start processing 6 pages concurrently
    3 skipping all processing on this page                                                                                                                                          
    1 skipping all processing on this page                                                                                                                                          
    5 skipping all processing on this page                                                                                                                                          
    4 skipping all processing on this page                                                                                                                                          
    2 skipping all processing on this page                                                                                                                                          
OCR: 100%|███████████████████| 6.0/6.0 [00:03<00:00,  1.66page/s]
Postprocessing...
PDF/A conversion: 100%|███████████████████████| 6/6 [00:01<00:00,  5.46page/s]
JPEGs: 0image [00:00, ?image/s]
JBIG2: 100%|███████████████████████████████| 1/1 [00:00<00:00, 49.87item/s]
Optimize ratio: 1.00 savings: 0.4%
Output file is a PDF/A-2B (as expected)

Presence of the original text is confirmed by examining the text in almost_all_text_output.pdf and seeing no OCR errors.

**Comment by jbarlow83** [comment]
Thank you for the thorough issue report and analysis.

My analysis it that upgrading to pikepdf 5.3.1 resolves the issue. (Unfortunately, due to https://github.com/pikepdf/pikepdf/issues/367, pikepdf 5.3.1's sdist is broken due to an unrelated. Hopefully that will be resolved soon. The wheels are fine.) With pikepdf 5.3.1, the latest ocrmypdf returns PriorOcrFoundError for almost_all_text_output.pdf as expected.

In almost_all_text.pdf, the images are mostly presented as inline images. pikepdf < 5.3.1 had a problem with its content stream parser inline images that could discard text that followed an inline image without noticing it. So most likely, the inline image comes first, followed by text, because of the parsing problem, ocrmypdf didn't "see" any text, so it saw a file that needed OCR.

I have not checked when the error in pikepdf's parser was introduced, but the problems you observed from ocrmypdf 11.5.0 to 12.7.2 were probably due to coinciding pikepdf upgrades.
