### ISSUE TITLE
Conda Repository not working

### ISSUE THREAD

**Issue by PiegoIlTempo** [ocrmypdf/OCRmyPDF#985]
The conda repository is not working, and I really need it because it seems like the only way to make this work on CentOS without root access...

![image](https://user-images.githubusercontent.com/40637700/178112709-4c99adca-fb2d-4df4-89da-d1c47ff9e7fc.png)

**Comment by jbarlow83** [comment]
Please report with conda. A lot of people have found ocrmypdf useful and packaged it for other systems and distribution channels - more than I could possibly keep with up with. I don't know how conda's packaging works so I can't be of much help.
