### ISSUE TITLE
AttributeError: module 'ocrmypdf' has no attribute 'ocr'

### ISSUE THREAD

**Issue by arcontechnologies** [ocrmypdf/OCRmyPDF#999]
**Describe the bug**
When trying to use ocrmypdf.ocr api it generates an error :

`AttributeError: module 'ocrmypdf' has no attribute 'ocr'`

the code is :
```
import ocrmypdf

if __name__ == '__main__':  # To ensure correct behavior on Windows and macOS
    ocrmypdf.ocr('pdfin.pdf', 'pdfout.pdf', deskew=True)
```

**To Reproduce**
everytime when trying to run the script

**Expected behavior**
getting a new pdf out

**Screenshots**
not applicable

**System (please complete the following information):**
 - OS: WSL under Windows 10 
 - Python version: 3.9.12
 - OCRmyPDF version: 13.6.2

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
using pip install ocrmypdf

**Additional context**
nothing

**Comment by jbarlow83** [comment]
Are you sure Python is running in the same virtual environment that ocrmypdf was installed to? 
Most likely you installed the system ocrmypdf, so Python is picking up an older ocrmypdf as installed by Ubuntu.

**Comment by arcontechnologies** [comment]
Sure. Here is my screenshot :
![image](https://user-images.githubusercontent.com/17960609/181481644-a0267a2b-6d97-4456-99ed-b2071883ae5d.png)
